#!/usr/bin/env node
// Validate bundled content and generate typed Flutter content. Optional ingestion converts local originals to bundled sRGB assets; --rn enables reference outputs.

//   node design-system/scripts/build-content.mjs --ingest --only camera-placeholder.jpg

import { execFileSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generatedComments } from './generated-comments.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const CHECK = process.argv.includes('--check');
const INGEST = process.argv.includes('--ingest');

const ONLY = new Set(process.argv.flatMap((a, i, all) => (a === '--only' && all[i + 1] ? [all[i + 1]] : [])));

const CONTENT_DIR = resolve(root, 'design-system/content');
const IMAGES_DIR = resolve(CONTENT_DIR, 'images');
const MANIFEST = resolve(CONTENT_DIR, 'manifest.json');
const CONTENT = resolve(CONTENT_DIR, 'lab-content.json');
const RN_ASSETS = resolve(root, 'apps/rn/assets/content');
const FL_ASSETS = resolve(root, 'apps/flutter/assets/content');
const OUT_TS = resolve(root, 'apps/rn/src/content/lab.generated.ts');
const OUT_DART = resolve(root, 'apps/flutter/lib/content/lab.g.dart');
const HEADER =
  'GENERATED by design-system/scripts/build-content.mjs from design-system/content/lab-content.json + manifest.json — DO NOT EDIT';
const SRGB_PROFILE = '/System/Library/ColorSync/Profiles/sRGB Profile.icc';

const ALLOWED_META_GROUPS = new Set(['ExifTool', 'File', 'Composite', 'PNG', 'JPEG']);

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));
const isAppleDouble = (name) => name.startsWith('._');
const fail = (msg) => {
  console.error(`✗ ${msg}`);
  process.exit(1);
};

const manifest = readJson(MANIFEST);
if (!Array.isArray(manifest.images) || manifest.images.length === 0) fail('manifest.json: images[] 가 비어 있음');
const imageByFile = new Map(manifest.images.map((img) => [img.file, img]));
if (imageByFile.size !== manifest.images.length) fail('manifest.json: 파일명이 중복됨');

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
function run(cmd, args) {
  return execFileSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}

function pixelSize(file) {
  const out = run('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', file]);
  const w = Number(/pixelWidth:\s*(\d+)/.exec(out)?.[1]);
  const h = Number(/pixelHeight:\s*(\d+)/.exec(out)?.[1]);
  if (!w || !h) throw new Error(`sips: 크기를 읽지 못함 ${file}`);
  return { width: w, height: h };
}

function assertNoMetadata(file) {
  const gps = run('exiftool', ['-s', '-s', '-s', '-gps:all', file]).trim();
  if (gps) throw new Error(`GPS 잔존: ${file}\n${gps}`);
  const groups = run('exiftool', ['-a', '-G0', '-s', file])
    .split('\n')
    .map((l) => /^\[([^\]]+)\]/.exec(l)?.[1])
    .filter(Boolean);
  const leftover = [...new Set(groups)].filter((g) => !ALLOWED_META_GROUPS.has(g));
  if (leftover.length) throw new Error(`메타데이터 잔존 (${leftover.join(', ')}): ${file}`);
}

function ingest() {
  for (const tool of ['sips', 'exiftool']) {
    try {
      execFileSync('which', [tool], { stdio: 'ignore' });
    } catch {
      fail(`--ingest 에는 ${tool} 이 필요합니다 (macOS sips, brew install exiftool)`);
    }
  }
  mkdirSync(IMAGES_DIR, { recursive: true });
  for (const f of ONLY) if (!imageByFile.has(f)) fail(`--only ${f}: manifest.json 에 없는 이미지`);
  const tmp = mkdtempSync(join(tmpdir(), 'cameo-content-'));
  try {
    for (const img of manifest.images) {
      if (ONLY.size && !ONLY.has(img.file)) continue;
      // Redacted mock slots must never be re-ingested from personal originals.
      if (img.source.kind === 'placeholder') continue;
      const src = resolve(root, img.source.path);
      if (!existsSync(src)) throw new Error(`원본 없음: ${img.source.path}`);

      const p = img.process;
      const ext = p.encode === 'png' ? 'png' : 'jpg';
      if (!img.file.endsWith(`.${ext}`)) throw new Error(`확장자와 encode 불일치: ${img.file} (${p.encode})`);

      const input = join(tmp, `in-${img.file}.${img.source.format === 'png' ? 'png' : 'jpg'}`);
      const output = join(tmp, img.file);
      copyFileSync(src, input);

      if (p.rotate != null && ![90, 180, 270].includes(p.rotate)) {
        throw new Error(`rotate 는 90 | 180 | 270 (시계 방향): ${img.file} (${p.rotate})`);
      }
      if (p.encode === 'copy') {
        if (img.source.format !== 'jpeg' || p.toSrgb || p.resizeToWidth || p.rotate) {
          throw new Error(`encode=copy 는 무변환 JPEG 에만 허용: ${img.file}`);
        }
        copyFileSync(input, output);
      } else {

        const args = [];
        if (p.toSrgb) args.push('--matchTo', SRGB_PROFILE);
        if (p.rotate) args.push('--rotate', String(p.rotate));
        if (p.resizeToWidth) args.push('--resampleWidth', String(p.resizeToWidth));
        if (p.encode === 'jpeg85') args.push('-s', 'format', 'jpeg', '-s', 'formatOptions', '85');
        else if (p.encode === 'png') args.push('-s', 'format', 'png');
        else throw new Error(`알 수 없는 encode: ${p.encode}`);
        run('sips', [...args, input, '--out', output]);
      }
      run('exiftool', ['-q', '-all=', '-overwrite_original', output]);
      assertNoMetadata(output);

      const buf = readFileSync(output);
      const size = pixelSize(output);
      if (p.resizeToWidth && size.width !== p.resizeToWidth) throw new Error(`축소 실패: ${img.file}`);
      img.output = {
        format: p.encode === 'png' ? 'png' : 'jpeg',
        width: size.width,
        height: size.height,
        bytes: buf.length,
        metadata: 'none (exiftool -all=; GPS verified absent)',
      };

      writeFileSync(join(IMAGES_DIR, img.file), buf);
      console.log(`ingested ${img.file} ${size.width}x${size.height} ${buf.length}B`);
    }
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }

  for (const f of readdirSync(IMAGES_DIR)) {
    if (!imageByFile.has(f) || isAppleDouble(f)) rmSync(join(IMAGES_DIR, f), { force: true });
  }
  writeFileSync(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(`wrote ${MANIFEST}`);
}

if (INGEST) {
  if (CHECK) fail('--ingest 와 --check 는 함께 쓸 수 없음');
  ingest();
}

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
const imageBytes = new Map();
for (const img of manifest.images) {
  const p = join(IMAGES_DIR, img.file);
  if (!img.output) fail(`manifest.json: ${img.file} 에 output 없음 — \`--ingest\` 필요`);
  if (!existsSync(p)) fail(`이미지 없음: design-system/content/images/${img.file} — \`--ingest\` 필요`);
  const buf = readFileSync(p);
  imageBytes.set(img.file, buf);
}

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
const raw = readJson(CONTENT);
const where = [];
const at = () => where.join('.');
function field(obj, key, kind) {
  where.push(key);
  if (!(key in obj)) fail(`lab-content.json: ${at()} 없음`);
  const v = obj[key];
  check(v, kind);
  where.pop();
  return v;
}
function check(v, kind) {
  if (kind === 'string' && typeof v !== 'string') fail(`${at()}: string 이어야 함`);
  if (kind === 'number' && typeof v !== 'number') fail(`${at()}: number 이어야 함`);
  if (kind === 'int' && !Number.isInteger(v)) fail(`${at()}: 정수여야 함`);
  if (kind === 'bool' && typeof v !== 'boolean') fail(`${at()}: boolean 이어야 함`);
  if (kind === 'array' && !Array.isArray(v)) fail(`${at()}: array 여야 함`);
  if (kind === 'object' && (typeof v !== 'object' || v === null || Array.isArray(v))) fail(`${at()}: object 여야 함`);
  if (kind === 'image' && !imageByFile.has(v)) fail(`${at()}: manifest 에 없는 이미지 '${v}'`);
  if (kind === 'image?' && v !== null && !imageByFile.has(v)) fail(`${at()}: manifest 에 없는 이미지 '${v}'`);
  if (Array.isArray(kind) && !kind.includes(v)) fail(`${at()}: ${kind.join(' | ')} 중 하나여야 함 (현재 ${JSON.stringify(v)})`);
}
function each(obj, key, fn) {
  const arr = field(obj, key, 'array');
  where.push(key);
  const out = arr.map((item, i) => {
    where.push(String(i));
    const r = fn(item);
    where.pop();
    return r;
  });
  where.pop();
  return out;
}
function sub(obj, key, fn, nullable = false) {
  where.push(key);
  if (!(key in obj)) fail(`lab-content.json: ${at()} 없음`);
  const v = obj[key];
  if (v === null && nullable) {
    where.pop();
    return null;
  }
  check(v, 'object');
  const r = fn(v);
  where.pop();
  return r;
}
const round6 = (n) => Math.round(n * 1e6) / 1e6;
function fraction(obj, key, px, total) {
  const v = field(obj, key, 'number');
  if (Math.abs(v - round6(px / total)) > 1e-6) fail(`${at()}.${key}: ${px}/${total} = ${round6(px / total)} 이어야 함 (현재 ${v})`);
  return v;
}

const TONES = ['dark', 'light'];
const WEIGHTS = ['regular', 'medium'];
const ALIGNS = ['left', 'right'];
const DIRECTIONS = ['outgoing', 'incoming', 'missed'];
const CAMERA_MODES = ['photo', 'video'];

const grid = (g) => {
  const columns = field(g, 'columns', 'int');
  const rows = each(g, 'rows', (row) => {
    check(row, 'array');
    if (row.length === 0 || row.length > columns) fail(`${at()}: 행의 칸 수는 1..${columns}`);
    row.forEach((f) => check(f, 'image'));
    return row;
  });
  return { columns, rows };
};

const LIKED_SPAN = 2;

function gridPhotos(g, featured = []) {
  const anchors = new Map();
  const covered = new Set();
  const cellAt = (r, c) => g.rows[r]?.[c];
  where.push('featured');
  featured.forEach((t, i) => {
    where.push(String(i));
    if (t.rowSpan !== LIKED_SPAN || t.colSpan !== LIKED_SPAN) fail(`${at()}: rowSpan·colSpan 은 ${LIKED_SPAN} 이어야 함 (2x2 = 좋아요)`);
    if (!t.liked) fail(`${at()}.liked: 2x2 추천 타일 = 좋아요한 사진 (interaction-spec §1) → true 여야 함`);
    const r0 = t.row - 1;
    const c0 = t.col - 1;
    for (let dr = 0; dr < LIKED_SPAN; dr++) {
      for (let dc = 0; dc < LIKED_SPAN; dc++) {
        const key = `${r0 + dr}:${c0 + dc}`;
        if (cellAt(r0 + dr, c0 + dc) === undefined) fail(`${at()}: 타일이 그리드 밖 칸 r${r0 + dr + 1}c${c0 + dc + 1} 을 덮음`);
        if (anchors.has(key) || covered.has(key)) fail(`${at()}: 다른 추천 타일과 겹침 (r${r0 + dr + 1}c${c0 + dc + 1})`);
        if (dr === 0 && dc === 0) anchors.set(key, t);
        else covered.add(key);
      }
    }
    where.pop();
  });
  where.pop();
  const photos = [];
  g.rows.forEach((row, r) =>
    row.forEach((image, c) => {
      const key = `${r}:${c}`;
      if (covered.has(key)) return;
      const t = anchors.get(key);
      photos.push(t ? { image: t.image, liked: true } : { image, liked: false });
    }),
  );
  return photos;
}
const withPhotos = (g, featured) => (g === null ? null : { ...g, photos: gridPhotos(g, featured) });

const gradient = (g) => {
  const solidUntil = field(g, 'solidUntil', 'number');
  if (solidUntil <= 0 || solidUntil >= 1) fail(`${at()}.solidUntil: 0..1 사이 분수`);
  return { solidUntil };
};
const nodeIds = (o) => ({ light: field(o, 'light', 'string'), dark: field(o, 'dark', 'string') });

const TOKENS = readJson(resolve(root, 'design-system/tokens.json'));
const COLOR_ROLES = new Set(Object.keys(TOKENS.color.roles));
const GRADIENT_NAMES = new Set(Object.keys(TOKENS.gradient).filter((k) => !k.startsWith('$')));
const ICON_KEYS = new Set([...TOKENS.icon.used.outline, ...TOKENS.icon.used.filled.map((s) => `${s}-filled`)]);
const SECTION_KINDS = ['photosCalls', 'callsOnly', 'photosOnly'];
const CARD_VARIANTS = ['default', 'scrim', 'failed'];
const ORIENTATIONS = ['portrait', 'landscape'];

const ICON_OF_DIRECTION = { outgoing: 'arrow-up-right', incoming: 'arrow-down-left', missed: 'arrow-down-left' };
function member(obj, key, set, what) {
  const v = field(obj, key, 'string');
  if (!set.has(v)) fail(`lab-content.json: ${at()}.${key}: tokens.json 에 없는 ${what} '${v}'`);
  return v;
}
const iconList = (obj, key) =>
  each(obj, key, (v) => {
    check(v, 'string');
    if (!ICON_KEYS.has(v)) fail(`lab-content.json: ${at()}: tokens.json icon.used 에 없는 아이콘 '${v}'`);
    return v;
  });
const toastOf = (t) => ({
  screenNodeId: field(t, 'screenNodeId', 'string'),
  nodeId: field(t, 'nodeId', 'string'),
  text: field(t, 'text', 'string'),
  icon: member(t, 'icon', ICON_KEYS, '아이콘'),
  iconIsPlaceholder: field(t, 'iconIsPlaceholder', 'bool'),
});
const featuredTile = (t) => ({
  nodeId: field(t, 'nodeId', 'string'),
  image: field(t, 'image', 'image'),
  row: field(t, 'row', 'int'),
  col: field(t, 'col', 'int'),
  rowSpan: field(t, 'rowSpan', 'int'),
  colSpan: field(t, 'colSpan', 'int'),
  liked: field(t, 'liked', 'bool'),
});

const playerV5 = (p) => {
  const trackWidthPx = field(p, 'trackWidthPx', 'number');
  const progressWidthPx = field(p, 'progressWidthPx', 'number');
  const thumbLeftPx = field(p, 'thumbLeftPx', 'number');
  const thumbSizePx = field(p, 'thumbSizePx', 'number');
  const thumbCenterPx = field(p, 'thumbCenterPx', 'number');
  if (thumbCenterPx !== thumbLeftPx + thumbSizePx / 2) fail(`${at()}.thumbCenterPx: thumbLeftPx + thumbSizePx/2 이어야 함`);
  return {
    nodeId: field(p, 'nodeId', 'string'),
    currentTime: field(p, 'currentTime', 'string'),
    duration: field(p, 'duration', 'string'),
    durationSeconds: field(p, 'durationSeconds', 'int'),
    playing: field(p, 'playing', 'bool'),
    trackWidthPx,
    progressWidthPx,
    progress: fraction(p, 'progress', progressWidthPx, trackWidthPx),
    thumbLeftPx,
    thumbSizePx,
    thumbCenterPx,
    thumbCenter: fraction(p, 'thumbCenter', thumbCenterPx, trackWidthPx),
    markers: each(p, 'markers', (m) => {
      const leftPx = field(m, 'leftPx', 'number');
      const widthPx = field(m, 'widthPx', 'number');
      return {
        nodeId: field(m, 'nodeId', 'string'),
        leftPx,
        widthPx,
        start: fraction(m, 'start', leftPx, trackWidthPx),
        width: fraction(m, 'width', widthPx, trackWidthPx),
      };
    }),
  };
};

function photoSheet(p) {
  const g = sub(p, 'grid', grid);
  const liveCell = sub(p, 'liveCell', (l) => ({
    nodeId: field(l, 'nodeId', 'string'),
    image: field(l, 'image', 'image'),
    row: field(l, 'row', 'int'),
    col: field(l, 'col', 'int'),
    rowSpan: field(l, 'rowSpan', 'int'),
  }));
  const covered = new Set();
  for (let dr = 0; dr < liveCell.rowSpan; dr++) {
    const r = liveCell.row - 1 + dr;
    if (g.rows[r]?.[liveCell.col - 1] === undefined) fail(`${at()}.liveCell: 그리드 밖 칸 r${r + 1}c${liveCell.col} 을 덮음`);
    covered.add(`${r}:${liveCell.col - 1}`);
  }
  const selected = each(p, 'selected', (s) => {
    const row = field(s, 'row', 'int');
    const col = field(s, 'col', 'int');
    if (g.rows[row - 1]?.[col - 1] === undefined) fail(`${at()}: 그리드 밖 칸 r${row}c${col}`);
    if (covered.has(`${row - 1}:${col - 1}`)) fail(`${at()}: 실시간 칸이 덮은 칸 r${row}c${col} 은 선택할 수 없다`);
    return `${row - 1}:${col - 1}`;
  });
  const photos = [];
  g.rows.forEach((row, r) =>
    row.forEach((image, c) => {
      if (!covered.has(`${r}:${c}`)) photos.push({ image, selected: selected.includes(`${r}:${c}`) });
    }),
  );
  return {
    screenNodeId: field(p, 'screenNodeId', 'string'),
    nodeId: field(p, 'nodeId', 'string'),
    title: field(p, 'title', 'string'),
    liveCell,
    columns: g.columns,
    rows: g.rows,
    photos,
  };
}

function albumV5Section(s) {
  const kind = field(s, 'kind', SECTION_KINDS);
  const tint = member(s, 'tint', COLOR_ROLES, '색 역할');
  where.push('heroGradient');
  if (!('heroGradient' in s)) fail(`lab-content.json: ${at()} 없음`);
  where.pop();
  const heroGradient = s.heroGradient === null ? null : member(s, 'heroGradient', GRADIENT_NAMES, '그라데이션');
  const cover = field(s, 'cover', 'image?');
  const callCards = each(s, 'callCards', (c) => {
    const direction = field(c, 'direction', DIRECTIONS);
    const icon = field(c, 'icon', ['arrow-up-right', 'arrow-down-left']);
    if (icon !== ICON_OF_DIRECTION[direction]) fail(`${at()}.icon: ${direction} 카드 아이콘은 ${ICON_OF_DIRECTION[direction]} (E4 — 방향 데이터로)`);
    const variant = field(c, 'variant', CARD_VARIANTS);
    if ((variant === 'failed') !== (direction === 'missed')) fail(`${at()}.variant: 부재중(missed) ⇔ failed`);
    return {
      nodeId: field(c, 'nodeId', 'string'),
      variant,
      direction,
      icon,
      title: field(c, 'title', 'string'),
      subtitle: each(c, 'subtitle', (sp) => ({ text: field(sp, 'text', 'string'), weight: field(sp, 'weight', WEIGHTS) })),
    };
  });
  const featured = each(s, 'featured', featuredTile);
  const g = sub(s, 'grid', grid, true);
  const hasHero = cover !== null && heroGradient !== null;
  if ((cover === null) !== (heroGradient === null)) fail(`${at()}: cover 와 heroGradient 는 함께 있거나 함께 null`);
  if (kind === 'callsOnly' && (hasHero || g !== null || callCards.length === 0))
    fail(`${at()}: callsOnly = 히어로 · 그리드 없음 + 카드 1장 이상 (Figma 2232:2165)`);
  if (kind === 'photosOnly' && (!hasHero || g === null || callCards.length > 0)) fail(`${at()}: photosOnly = 히어로 + 그리드, 카드 없음`);
  if (kind === 'photosCalls' && (!hasHero || g === null || callCards.length === 0)) fail(`${at()}: photosCalls = 히어로 + 카드 + 그리드`);
  if (featured.length && g === null) fail(`${at()}.featured: 그리드 없는 섹션`);
  return {
    id: field(s, 'id', 'string'),
    figmaName: field(s, 'figmaName', 'string'),
    nodeId: field(s, 'nodeId', 'string'),
    kind,
    tint,
    heroGradient,
    cover,
    title: field(s, 'title', 'string'),
    subtitle: field(s, 'subtitle', 'string'),
    stats: sub(s, 'stats', (st) => ({ photos: field(st, 'photos', 'string'), calls: field(st, 'calls', 'string') })),
    callCards,
    grid: g === null ? null : withPhotos(g, featured),
    featured,
  };
}

const content = {
  albumDay: sub(raw, 'albumDay', (a) => ({
    screenNodeId: field(a, 'screenNodeId', 'string'),
    sections: each(a, 'sections', (s) => ({
      id: field(s, 'id', 'string'),
      figmaName: field(s, 'figmaName', 'string'),
      nodeId: field(s, 'nodeId', 'string'),
      tone: field(s, 'tone', TONES),
      cover: field(s, 'cover', 'image?'),
      title: field(s, 'title', 'string'),
      subtitle: field(s, 'subtitle', 'string'),
      stats: sub(s, 'stats', (st) => ({ photos: field(st, 'photos', 'string'), calls: field(st, 'calls', 'string') })),
      callCards: each(s, 'callCards', (c) => ({
        nodeId: field(c, 'nodeId', 'string'),
        direction: field(c, 'direction', DIRECTIONS),
        icon: field(c, 'icon', ['arrow-up-right', 'arrow-down-left']),
        title: field(c, 'title', 'string'),
        subtitle: each(c, 'subtitle', (sp) => ({ text: field(sp, 'text', 'string'), weight: field(sp, 'weight', WEIGHTS) })),
      })),
      grid: withPhotos(sub(s, 'grid', grid, true)),
    })),
  })),
  albumGangneung: sub(raw, 'albumGangneung', (a) => {
    const g = sub(a, 'grid', grid);
    const featured = each(a, 'featured', (t) => ({
      nodeId: field(t, 'nodeId', 'string'),
      image: field(t, 'image', 'image'),
      row: field(t, 'row', 'int'),
      col: field(t, 'col', 'int'),
      rowSpan: field(t, 'rowSpan', 'int'),
      colSpan: field(t, 'colSpan', 'int'),
      liked: field(t, 'liked', 'bool'),
    }));
    return {
      screenNodeId: field(a, 'screenNodeId', 'string'),
      title: field(a, 'title', 'string'),
      date: field(a, 'date', 'string'),
      cover: field(a, 'cover', 'image'),
      grid: withPhotos(g, featured),
      featured,
      quoteCard: sub(a, 'quoteCard', (q) => ({
        nodeId: field(q, 'nodeId', 'string'),
        label: field(q, 'label', 'string'),
        labelAlign: field(q, 'labelAlign', ALIGNS),
        lines: each(q, 'lines', (l) => ({
          nodeId: field(l, 'nodeId', 'string'),
          text: field(l, 'text', 'string'),
          align: field(l, 'align', ALIGNS),
          gradient: sub(l, 'gradient', gradient, true),
        })),
      })),
      tabBar: sub(a, 'tabBar', (t) => ({
        nodeId: field(t, 'nodeId', 'string'),
        selectedIndex: field(t, 'selectedIndex', 'int'),
        avatar: field(t, 'avatar', 'image'),
      })),
    };
  }),
  transcript: sub(raw, 'transcript', (t) => ({
    screenNodeIds: sub(t, 'screenNodeIds', nodeIds),
    title: field(t, 'title', 'string'),
    date: field(t, 'date', 'string'),
    darkBackground: field(t, 'darkBackground', 'image'),
    lines: each(t, 'lines', (l) => ({
      id: field(l, 'id', 'string'),
      nodeIds: sub(l, 'nodeIds', nodeIds),
      text: field(l, 'text', 'string'),
      side: field(l, 'side', ALIGNS),
      inHighlight: field(l, 'inHighlight', 'bool'),
      current: field(l, 'current', 'bool'),
      gradient: sub(l, 'gradient', gradient, true),
    })),
    player: sub(t, 'player', (p) => {
      const trackWidthPx = field(p, 'trackWidthPx', 'number');
      const progressWidthPx = field(p, 'progressWidthPx', 'number');
      const thumbLeftPx = field(p, 'thumbLeftPx', 'number');
      const thumbSizePx = field(p, 'thumbSizePx', 'number');
      const thumbCenterPx = field(p, 'thumbCenterPx', 'number');
      if (thumbCenterPx !== thumbLeftPx + thumbSizePx / 2) fail(`${at()}.thumbCenterPx: thumbLeftPx + thumbSizePx/2 이어야 함`);
      return {
        nodeIds: sub(p, 'nodeIds', nodeIds),
        currentTime: field(p, 'currentTime', 'string'),
        duration: field(p, 'duration', 'string'),
        durationSeconds: field(p, 'durationSeconds', 'int'),
        playing: field(p, 'playing', 'bool'),
        trackWidthPx,
        trackWidthPxDark: field(p, 'trackWidthPxDark', 'number'),
        progressWidthPx,
        progress: fraction(p, 'progress', progressWidthPx, trackWidthPx),
        thumbLeftPx,
        thumbSizePx,
        thumbCenterPx,
        thumbCenter: fraction(p, 'thumbCenter', thumbCenterPx, trackWidthPx),
        markers: each(p, 'markers', (m) => {
          const leftPx = field(m, 'leftPx', 'number');
          const widthPx = field(m, 'widthPx', 'number');
          return {
            nodeIds: sub(m, 'nodeIds', nodeIds),
            leftPx,
            widthPx,
            start: fraction(m, 'start', leftPx, trackWidthPx),
            width: fraction(m, 'width', widthPx, trackWidthPx),
          };
        }),
      };
    }),
  })),
  inCall: sub(raw, 'inCall', (c) => {
    const toast = (t) => ({
      screenNodeId: field(t, 'screenNodeId', 'string'),
      nodeId: field(t, 'nodeId', 'string'),
      text: field(t, 'text', 'string'),
      icon: field(t, 'icon', 'string'),
      iconIsPlaceholder: field(t, 'iconIsPlaceholder', 'bool'),
    });
    return {
      screenNodeIds: each(c, 'screenNodeIds', (id) => (check(id, 'string'), id)),
      name: field(c, 'name', 'string'),
      timer: field(c, 'timer', 'string'),
      background: field(c, 'background', 'image'),
      toasts: sub(c, 'toasts', (t) => ({
        systemMessage: sub(t, 'systemMessage', toast),
        sleepModeRequest: sub(t, 'sleepModeRequest', toast),
      })),
    };
  }),
  photoBoothSample: sub(raw, 'photoBoothSample', (p) => ({
    nodeId: field(p, 'nodeId', 'string'),
    image: field(p, 'image', 'image'),
  })),
  camera: sub(raw, 'camera', (c) => {
    const modes = each(c, 'modes', (m) => ({
      id: field(m, 'id', CAMERA_MODES),
      nodeId: field(m, 'nodeId', 'string'),
      labelNodeId: field(m, 'labelNodeId', 'string'),
      label: field(m, 'label', 'string'),
    }));
    const ids = modes.map((m) => m.id);
    if (new Set(ids).size !== ids.length) fail(`${at()}.modes: id 중복`);
    const initialMode = field(c, 'initialMode', CAMERA_MODES);
    if (!ids.includes(initialMode)) fail(`${at()}.initialMode: modes 에 없는 id '${initialMode}'`);
    return {
      screenNodeId: field(c, 'screenNodeId', 'string'),
      placeholderNodeId: field(c, 'placeholderNodeId', 'string'),
      placeholder: field(c, 'placeholder', 'image'),
      initialMode,
      modes,
    };
  }),
  // ---- v5 (reference/figma-v5) ----
  inCallV5: sub(raw, 'inCallV5', (c) => ({
    screenNodeIds: each(c, 'screenNodeIds', (id) => (check(id, 'string'), id)),
    name: field(c, 'name', 'string'),
    timer: field(c, 'timer', 'string'),
    background: field(c, 'background', 'image'),
    toasts: sub(c, 'toasts', (t) => ({ sleep: sub(t, 'sleep', toastOf), highlight: sub(t, 'highlight', toastOf) })),
    photoSheet: sub(c, 'photoSheet', photoSheet),
    capturedCard: sub(c, 'capturedCard', (k) => ({
      nodeId: field(k, 'nodeId', 'string'),
      image: field(k, 'image', 'image'),
      orientation: field(k, 'orientation', ORIENTATIONS),
    })),
  })),
  cameraV5: sub(raw, 'cameraV5', (c) => ({
    screenNodeId: field(c, 'screenNodeId', 'string'),
    viewfinderNodeId: field(c, 'viewfinderNodeId', 'string'),
    viewfinder: field(c, 'viewfinder', 'image'),
    thumbnailNodeId: field(c, 'thumbnailNodeId', 'string'),
    thumbnail: field(c, 'thumbnail', 'image'),
    toast: sub(c, 'toast', toastOf),
  })),
  viewerV5: sub(raw, 'viewerV5', (v) => {
    const viewer = (x) => ({
      screenNodeId: field(x, 'screenNodeId', 'string'),
      cardNodeId: field(x, 'cardNodeId', 'string'),
      image: field(x, 'image', 'image'),
      date: field(x, 'date', 'string'),
      actions: iconList(x, 'actions'),
    });
    return { photo: sub(v, 'photo', viewer), instant: sub(v, 'instant', viewer) };
  }),
  tabBarV5: sub(raw, 'tabBarV5', (t) => ({ nodeId: field(t, 'nodeId', 'string'), avatar: field(t, 'avatar', 'image') })),
  albumV5: sub(raw, 'albumV5', (a) => ({
    screenNodeId: field(a, 'screenNodeId', 'string'),
    contentNodeId: field(a, 'contentNodeId', 'string'),
    nav: sub(a, 'nav', (n) => ({ selectLabel: field(n, 'selectLabel', 'string'), actions: iconList(n, 'actions') })),
    selectNav: sub(a, 'selectNav', (n) => ({ actions: iconList(n, 'actions') })),
    sections: each(a, 'sections', albumV5Section),
  })),
  settingsV5: sub(raw, 'settingsV5', (s) => {
    const days = field(s, 'days', 'int');
    const dayCount = field(s, 'dayCount', 'string');
    if (dayCount !== `${days}일째`) fail(`${at()}.dayCount: '${days}일째' 여야 함 (days 와 같은 수)`);
    const action = (x) => ({ nodeId: field(x, 'nodeId', 'string'), label: field(x, 'label', 'string'), icon: member(x, 'icon', ICON_KEYS, '아이콘') });
    return {
      screenNodeId: field(s, 'screenNodeId', 'string'),
      hero: field(s, 'hero', 'image'),
      names: field(s, 'names', 'string'),
      days,
      dayCount,
      daySuffix: field(s, 'daySuffix', 'string'),
      editProfile: sub(s, 'editProfile', action),
      disconnect: sub(s, 'disconnect', action),
    };
  }),
  transcriptV5: sub(raw, 'transcriptV5', (t) => {
    const lines = each(t, 'lines', (l) => ({
      id: field(l, 'id', 'string'),
      nodeId: field(l, 'nodeId', 'string'),
      text: field(l, 'text', 'string'),
      side: field(l, 'side', ALIGNS),
      inHighlight: field(l, 'inHighlight', 'bool'),
      current: field(l, 'current', 'bool'),
    }));
    if (lines.filter((l) => l.current).length !== 1) fail(`${at()}.lines: current 줄은 정확히 하나 (카라오케 — gradient.karaokeV5)`);
    if (new Set(lines.map((l) => l.id)).size !== lines.length) fail(`${at()}.lines: id 중복`);
    const inlinePhoto = sub(t, 'inlinePhoto', (p) => ({
      nodeId: field(p, 'nodeId', 'string'),
      image: field(p, 'image', 'image'),
      afterLineId: field(p, 'afterLineId', lines.map((l) => l.id)),
    }));
    return {
      screenNodeId: field(t, 'screenNodeId', 'string'),
      variantNodeIds: each(t, 'variantNodeIds', (id) => (check(id, 'string'), id)),
      title: field(t, 'title', 'string'),
      date: field(t, 'date', 'string'),
      navActions: iconList(t, 'navActions'),
      lines,
      inlinePhoto,
      player: sub(t, 'player', playerV5),
    };
  }),
};
if (content.inCallV5.name !== content.inCall.name) fail(`lab-content.json: inCallV5.name '${content.inCallV5.name}' 은 inCall.name '${content.inCall.name}' 과 같아야 한다`);

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------
const files = [...imageByFile.keys()].sort();
const camelFile = (f) =>
  f
    .replace(/\.[a-z]+$/, '')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
const tsJson = (v) => JSON.stringify(v, null, 2);

const ts = `// ${HEADER}
// 콘텐츠는 Figma 원문 그대로 (오타 '자긴 전 대화', 시간 표기 불일치 포함 — 수정 금지).
// 색은 없다 (색은 tokens.json 색 역할 — Figma 값·모드). 이미지는 파일명(LabImageFile)으로 참조하고 labImages[file] 로 source 를 얻는다.
// 그리드 row/col 은 1-based (파일명 rRcC 와 동일). PhotoGridContent.photos = 그리드 순서 사진 목록 (배치는 layoutPhotoGrid).
import type { ImageSourcePropType } from 'react-native';
import type { ColorRole, GradientName } from '../design-system/tokens.generated';

export type LabImageFile =
${files.map((f) => `  | '${f}'`).join('\n')};

export const labImageFiles: readonly LabImageFile[] = ${tsJson(files)};

/** Metro 번들용 정적 require 맵 (apps/rn/assets/content/). */
export const labImages: Readonly<Record<LabImageFile, ImageSourcePropType>> = {
${files.map((f) => `  '${f}': require('../../assets/content/${f}'),`).join('\n')}
};

/** 처리 후 실제 픽셀 크기 (aspect ratio 계산용). */
export const labImageSize: Readonly<Record<LabImageFile, { readonly width: number; readonly height: number }>> = {
${files.map((f) => `  '${f}': { width: ${imageByFile.get(f).output.width}, height: ${imageByFile.get(f).output.height} },`).join('\n')}
};

export type LabTone = 'dark' | 'light';
export type LabTextWeight = 'regular' | 'medium';
export type LabAlign = 'left' | 'right';
export type CallDirection = 'outgoing' | 'incoming' | 'missed';

/** 한 문단 안의 스타일 구간 (Figma span). weight 는 Interlude Medium/Regular. */
export interface LabTextSpan {
  readonly text: string;
  readonly weight: LabTextWeight;
}

/** 텍스트 그라데이션: 텍스트 박스 폭 기준 0..solidUntil 은 강조 색, solidUntil..1 에서 기본 색으로 페이드 (색은 role). */
export interface GradientTextContent {
  readonly solidUntil: number;
}

export interface LabNodeIds {
  readonly light: string;
  readonly dark: string;
}

export interface CallCardContent {
  readonly nodeId: string;
  readonly direction: CallDirection;
  /** Tabler 아이콘 키 */
  readonly icon: 'arrow-up-right' | 'arrow-down-left';
  readonly title: string;
  readonly subtitle: readonly LabTextSpan[];
}

export interface AlbumStatsContent {
  readonly photos: string;
  readonly calls: string;
}

/** 그리드 사진 한 장. liked = 2x2 로 크게 (좋아요 — docs/interaction-spec.md §1). */
export interface GridPhotoContent {
  readonly image: LabImageFile;
  /** 초기 좋아요 상태 (16-3 추천 타일 2장 = true, 그 외 false) */
  readonly liked: boolean;
}

export interface PhotoGridContent {
  readonly columns: number;
  /**
   * Figma 셀 배치 row-major (추천 타일이 덮은 칸 포함). 마지막 행은 columns 보다 짧을 수 있다 (왼쪽부터 채움).
   * 레거시 — 현재 PhotoGrid 가 사용. 배치 엔진은 photos 를 쓴다.
   */
  readonly rows: readonly (readonly LabImageFile[])[];
  /**
   * 그리드 순서 사진 목록 + 초기 좋아요. 배치 = layoutPhotoGrid(photos.map((p) => p.liked), columns) (photoGridLayout.ts).
   * 추천 타일이 있으면 Figma 에 보이는 사진만 (덮인 칸 제외, 타일 사진은 앵커 자리에 liked) — 16-3 = 24장, #1·#14 liked.
   */
  readonly photos: readonly GridPhotoContent[];
}

export interface AlbumSectionContent {
  readonly id: string;
  readonly figmaName: string;
  readonly nodeId: string;
  /** 섹션 배경 명암 (dark = 사진 배경 섹션, light = 밝은 배경 섹션) */
  readonly tone: LabTone;
  /** 히어로 커버 (없으면 텍스트 헤더만) */
  readonly cover: LabImageFile | null;
  readonly title: string;
  readonly subtitle: string;
  readonly stats: AlbumStatsContent;
  readonly callCards: readonly CallCardContent[];
  readonly grid: PhotoGridContent | null;
}

export interface AlbumDayContent {
  readonly screenNodeId: string;
  readonly sections: readonly AlbumSectionContent[];
}

export interface FeaturedTileContent {
  readonly nodeId: string;
  readonly image: LabImageFile;
  /** 1-based 시작 셀 */
  readonly row: number;
  readonly col: number;
  readonly rowSpan: number;
  readonly colSpan: number;
  readonly liked: boolean;
}

export interface QuoteLineContent {
  readonly nodeId: string;
  readonly text: string;
  readonly align: LabAlign;
  readonly gradient: GradientTextContent | null;
}

export interface QuoteCardContent {
  readonly nodeId: string;
  readonly label: string;
  readonly labelAlign: LabAlign;
  readonly lines: readonly QuoteLineContent[];
}

export interface TabBarContent {
  readonly nodeId: string;
  readonly selectedIndex: number;
  readonly avatar: LabImageFile;
}

export interface AlbumGangneungContent {
  readonly screenNodeId: string;
  readonly title: string;
  readonly date: string;
  readonly cover: LabImageFile;
  readonly grid: PhotoGridContent;
  /** 2x2 추천 타일 — 덮는 일반 셀은 그리지 않는다. 레거시 (현재 PhotoGrid 가 사용) — 같은 정보가 grid.photos 의 liked 로 들어 있다 */
  readonly featured: readonly FeaturedTileContent[];
  readonly quoteCard: QuoteCardContent;
  readonly tabBar: TabBarContent;
}

export interface TranscriptLineContent {
  readonly id: string;
  readonly nodeIds: LabNodeIds;
  /** '\\n' = Figma 의 강제 줄바꿈 */
  readonly text: string;
  /** 화자: left / right 정렬 */
  readonly side: LabAlign;
  /** 하이라이트 카드 안의 줄인지 */
  readonly inHighlight: boolean;
  /** 현재 재생 중인 줄 (카라오케 그라데이션) */
  readonly current: boolean;
  readonly gradient: GradientTextContent | null;
}

export interface PlayerMarkerContent {
  readonly nodeIds: LabNodeIds;
  readonly leftPx: number;
  readonly widthPx: number;
  /** trackWidthPx 기준 분수 (0..1) */
  readonly start: number;
  readonly width: number;
}

export interface PlayerContent {
  readonly nodeIds: LabNodeIds;
  readonly currentTime: string;
  readonly duration: string;
  readonly durationSeconds: number;
  /** 일시정지 아이콘 표시 = 재생 중 */
  readonly playing: boolean;
  /** Figma 트랙 폭 (light 2042:3224 metadata). 분수는 이 값 기준. */
  readonly trackWidthPx: number;
  /** dark 2042:3105 는 렌더 실측 ≈154 (metadata 없음) */
  readonly trackWidthPxDark: number;
  readonly progressWidthPx: number;
  readonly progress: number;
  readonly thumbLeftPx: number;
  readonly thumbSizePx: number;
  readonly thumbCenterPx: number;
  readonly thumbCenter: number;
  readonly markers: readonly PlayerMarkerContent[];
}

export interface TranscriptContent {
  readonly screenNodeIds: LabNodeIds;
  readonly title: string;
  readonly date: string;
  /** dark 테마 풀블리드 배경 (light 는 이미지 없음) */
  readonly darkBackground: LabImageFile;
  /** 읽는 순서 */
  readonly lines: readonly TranscriptLineContent[];
  readonly player: PlayerContent;
}

export interface ToastContent {
  readonly screenNodeId: string;
  readonly nodeId: string;
  readonly text: string;
  /** Tabler 아이콘 키 ('-filled' 접미사 = filled 변형) */
  readonly icon: string;
  /** Figma 'placeholder' 인스턴스 (border-none) — 실제 아이콘 미정 */
  readonly iconIsPlaceholder: boolean;
}

export interface InCallContent {
  readonly screenNodeIds: readonly string[];
  readonly name: string;
  readonly timer: string;
  readonly background: LabImageFile;
  readonly toasts: {
    /** 16-8: 진입 직후 1회 */
    readonly systemMessage: ToastContent;
    /** 16-4: 달 버튼 */
    readonly sleepModeRequest: ToastContent;
  };
}

export interface PhotoBoothSampleContent {
  readonly nodeId: string;
  readonly image: LabImageFile;
}

/** 카메라 촬영 모드 (세그먼트 컨트롤 순서 = modes 순서) */
export type CameraModeId = 'photo' | 'video';

export interface CameraModeContent {
  readonly id: CameraModeId;
  /** 세그먼트 노드 (2056:3394 사진 · 2056:3412 동영상) */
  readonly nodeId: string;
  readonly labelNodeId: string;
  /** Figma 원문 라벨 ('사진' · '동영상') */
  readonly label: string;
}

export interface CameraContent {
  readonly screenNodeId: string;
  /** 뷰파인더 노드 (2058:3415) */
  readonly placeholderNodeId: string;
  /** 뷰파인더 placeholder (768x1024, 3:4) — 카메라가 없으면(시뮬레이터) 촬영 결과로도 쓴다 */
  readonly placeholder: LabImageFile;
  /** Figma 에서 선택된 모드 (사진) */
  readonly initialMode: CameraModeId;
  readonly modes: readonly CameraModeContent[];
}

/** iPhone 16 - 6 (album) */
export const labAlbumDay: AlbumDayContent = ${tsJson(content.albumDay)};

/** iPhone 16 - 3 (album 강릉) */
export const labAlbumGangneung: AlbumGangneungContent = ${tsJson(content.albumGangneung)};

/** iPhone 16 - 13 (dark 모드, nodeIds.light) / 16 - 12 (사진 배경, nodeIds.dark) 통화 기록 상세 */
export const labTranscript: TranscriptContent = ${tsJson(content.transcript)};

/** iPhone 16 - 8…11 / 16 - 4 통화 중 */
export const labInCall: InCallContent = ${tsJson(content.inCall)};

/** Frame 2042:3117 — 화면 아님 (에셋만) */
export const labPhotoBoothSample: PhotoBoothSampleContent = ${tsJson(content.photoBoothSample)};

/** iPhone 16 - 14 카메라 촬영 (v3 신규) */
export const labCamera: CameraContent = ${tsJson(content.camera)};

// ---------------------------------------------------------------------------
// v5 (reference/figma-v5 — 원본 rg1ff6r7hw74V5Cw2Sqazr, 페이지 design 2131:1284)
// ---------------------------------------------------------------------------

/** 앨범 날짜 섹션 종류 (E12): 사진 + 통화 · 통화만 (텍스트 헤더) · 사진만 */
export type AlbumSectionKind = 'photosCalls' | 'callsOnly' | 'photosOnly';
/** call-list 변형 (Figma 변형 이름 — 'scrim' = v6 CallListCard 'list', tokens layout.callListV6.$roles) */
export type CallCardVariant = 'default' | 'scrim' | 'failed';
export type CapturedOrientation = 'portrait' | 'landscape';

/** 사진 시트의 실시간 카메라 칸 — 열 col, 행 row..row+rowSpan-1 을 덮는다 (1-based) */
export interface SheetLiveCellContent {
  readonly nodeId: string;
  /** 시뮬레이터용 placeholder (실기기는 카메라 프리뷰) */
  readonly image: LabImageFile;
  readonly row: number;
  readonly col: number;
  readonly rowSpan: number;
}

export interface SheetPhotoContent {
  readonly image: LabImageFile;
  /** Figma 선택 상태 (opacity 0.3 + 체크) */
  readonly selected: boolean;
}

export interface PhotoSheetContent {
  readonly screenNodeId: string;
  readonly nodeId: string;
  /** '사진' */
  readonly title: string;
  readonly liveCell: SheetLiveCellContent;
  readonly columns: number;
  /** Figma 셀 배치 row-major (실시간 칸이 덮은 칸 포함) */
  readonly rows: readonly (readonly LabImageFile[])[];
  /** 보이는 사진만 row-major (덮인 칸 제외) + 선택 상태 */
  readonly photos: readonly SheetPhotoContent[];
}

export interface CapturedCardContent {
  readonly nodeId: string;
  readonly image: LabImageFile;
  /** portrait = 3:4 (Figma 2170:8313) · landscape = 4:3 (cameo E10) */
  readonly orientation: CapturedOrientation;
}

/** 통화 v5 (2170:8678 · 9065 · 2176:9162 · 2170:8774 · 8313) */
export interface InCallV5Content {
  readonly screenNodeIds: readonly string[];
  readonly name: string;
  readonly timer: string;
  /** 바탕 사진 (opacity layout.callV5.backgroundPhotoOpacity) */
  readonly background: LabImageFile;
  readonly toasts: {
    /** moon — 파트너 취침 전환 (오타 원문 그대로) */
    readonly sleep: ToastContent;
    /** rewind-15 — 하이라이트 저장 */
    readonly highlight: ToastContent;
  };
  readonly photoSheet: PhotoSheetContent;
  readonly capturedCard: CapturedCardContent;
}

export interface CameraV5Content {
  readonly screenNodeId: string;
  readonly viewfinderNodeId: string;
  /** 뷰파인더 placeholder (실기기 = 프리뷰) — 시뮬레이터 촬영 결과 */
  readonly viewfinder: LabImageFile;
  readonly thumbnailNodeId: string;
  /** 마지막 사진 썸네일 (= 인스턴트 사진) */
  readonly thumbnail: LabImageFile;
  /** 파트너 인스턴트 토스트 (motion.instant.partnerDelayMs) */
  readonly toast: ToastContent;
}

export interface ViewerContent {
  readonly screenNodeId: string;
  readonly cardNodeId: string;
  readonly image: LabImageFile;
  /** 자리표시 원문 '오늘, 00시 00분' */
  readonly date: string;
  /** buttonOption 아이콘 키 순서 */
  readonly actions: readonly string[];
}

/** 사진 보기 (2170:7914) · 인스턴트 보기 (2170:6159) */
export interface ViewerV5Content {
  readonly photo: ViewerContent;
  readonly instant: ViewerContent;
}

export interface TabBarV5Content {
  readonly nodeId: string;
  /** 탭 0 아바타 이미지 22 r4 (커플 셀카) */
  readonly avatar: LabImageFile;
}

export interface CallCardV5Content {
  readonly nodeId: string;
  readonly variant: CallCardVariant;
  readonly direction: CallDirection;
  /** 방향 데이터로 정한 Tabler 아이콘 (E4) */
  readonly icon: 'arrow-up-right' | 'arrow-down-left';
  readonly title: string;
  /** v5: run 모두 Regular (bodySm) */
  readonly subtitle: readonly LabTextSpan[];
}

export interface AlbumV5SectionContent {
  readonly id: string;
  readonly figmaName: string;
  readonly nodeId: string;
  readonly kind: AlbumSectionKind;
  /** 섹션 배경 틴트 = 색 역할 (모드 무관) */
  readonly tint: ColorRole;
  /** 히어로 그라데이션 (callsOnly = null) */
  readonly heroGradient: GradientName | null;
  readonly cover: LabImageFile | null;
  readonly title: string;
  readonly subtitle: string;
  readonly stats: AlbumStatsContent;
  readonly callCards: readonly CallCardV5Content[];
  /** photos = 보이는 사진 + liked (featured 2x2) — layoutPhotoGrid 입력 */
  readonly grid: PhotoGridContent | null;
  readonly featured: readonly FeaturedTileContent[];
}

export interface AlbumV5NavContent {
  /** '선택' */
  readonly selectLabel: string;
  readonly actions: readonly string[];
}

export interface AlbumV5SelectNavContent {
  readonly actions: readonly string[];
}

/** 앨범 홈 타임라인 (2170:6590 = 2232:2109) — 섹션은 최신 → 과거 */
export interface AlbumV5Content {
  readonly screenNodeId: string;
  readonly contentNodeId: string;
  readonly nav: AlbumV5NavContent;
  readonly selectNav: AlbumV5SelectNavContent;
  readonly sections: readonly AlbumV5SectionContent[];
}

export interface SettingsActionContent {
  readonly nodeId: string;
  readonly label: string;
  readonly icon: string;
}

/** 설정 v5 (2176:11011) — Figma 원문. 앱은 이름 = 세션, 날짜 = days (app-content settingsV5 템플릿) */
export interface SettingsV5Content {
  readonly screenNodeId: string;
  readonly hero: LabImageFile;
  /** '이주영, 이유림' */
  readonly names: string;
  readonly days: number;
  /** '200일째' (bodyMdMedium) */
  readonly dayCount: string;
  /** ' 공유중' (bodyMd) */
  readonly daySuffix: string;
  readonly editProfile: SettingsActionContent;
  readonly disconnect: SettingsActionContent;
}

export interface TranscriptV5LineContent {
  readonly id: string;
  readonly nodeId: string;
  /** '\\n' = Figma 의 강제 줄바꿈 */
  readonly text: string;
  readonly side: LabAlign;
  readonly inHighlight: boolean;
  /** 현재 줄 — gradient.karaokeV5 */
  readonly current: boolean;
}

export interface InlinePhotoContent {
  readonly nodeId: string;
  readonly image: LabImageFile;
  /** 이 줄 바로 뒤 (같은 줄 블록 안, gap 8) */
  readonly afterLineId: string;
}

export interface PlayerV5MarkerContent {
  readonly nodeId: string;
  readonly leftPx: number;
  readonly widthPx: number;
  /** trackWidthPx 기준 분수 (0..1) */
  readonly start: number;
  readonly width: number;
}

export interface PlayerV5Content {
  readonly nodeId: string;
  readonly currentTime: string;
  readonly duration: string;
  readonly durationSeconds: number;
  readonly playing: boolean;
  readonly trackWidthPx: number;
  readonly progressWidthPx: number;
  readonly progress: number;
  readonly thumbLeftPx: number;
  readonly thumbSizePx: number;
  readonly thumbCenterPx: number;
  readonly thumbCenter: number;
  readonly markers: readonly PlayerV5MarkerContent[];
}

/** 통화 기록 v5 A (2176:9241, dark) */
export interface TranscriptV5Content {
  readonly screenNodeId: string;
  /** 탐색안 B · C · D (라우트 없음) */
  readonly variantNodeIds: readonly string[];
  readonly title: string;
  readonly date: string;
  readonly navActions: readonly string[];
  readonly lines: readonly TranscriptV5LineContent[];
  readonly inlinePhoto: InlinePhotoContent;
  readonly player: PlayerV5Content;
}

/** 통화 v5 */
export const labInCallV5: InCallV5Content = ${tsJson(content.inCallV5)};

/** 카메라 v5 (2170:5682) */
export const labCameraV5: CameraV5Content = ${tsJson(content.cameraV5)};

/** 사진 보기 · 인스턴트 보기 */
export const labViewerV5: ViewerV5Content = ${tsJson(content.viewerV5)};

/** 탭바 v5 (bottom-nav 2166:5444) */
export const labTabBarV5: TabBarV5Content = ${tsJson(content.tabBarV5)};

/** 앨범 홈 타임라인 v5 */
export const labAlbumV5: AlbumV5Content = ${tsJson(content.albumV5)};

/** 설정 v5 (Figma 원문) */
export const labSettingsV5: SettingsV5Content = ${tsJson(content.settingsV5)};

/** 통화 기록 v5 A */
export const labTranscriptV5: TranscriptV5Content = ${tsJson(content.transcriptV5)};
`;

// ---------------------------------------------------------------------------
// Dart
// ---------------------------------------------------------------------------
const dStr = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$').replace(/\n/g, '\\n')}'`;
const dNum = (n) => (Number.isInteger(n) ? `${n}.0` : `${n}`);
const dImg = (f) => `LabImages.${camelFile(f)}`;
const dImgN = (f) => (f === null ? 'null' : dImg(f));
const ind = (n) => '  '.repeat(n);
const dList = (items, n, type) =>
  items.length === 0 ? `<${type}>[]` : `<${type}>[\n${items.map((i) => `${ind(n + 1)}${i},`).join('\n')}\n${ind(n)}]`;
const dNodeIds = (o) => `LabNodeIds(light: ${dStr(o.light)}, dark: ${dStr(o.dark)})`;
const dGradient = (g) => (g === null ? 'null' : `GradientTextContent(solidUntil: ${dNum(g.solidUntil)})`);
const dGrid = (g, n) =>
  g === null
    ? 'null'
    : `PhotoGridContent(\n${ind(n + 1)}columns: ${g.columns},\n${ind(n + 1)}rows: ${dList(
        g.rows.map((r) => `<String>[${r.map(dImg).join(', ')}]`),
        n + 1,
        'List<String>',
      )},\n${ind(n + 1)}photos: ${dList(
        g.photos.map((p) => `GridPhotoContent(image: ${dImg(p.image)}, liked: ${p.liked})`),
        n + 1,
        'GridPhotoContent',
      )},\n${ind(n)})`;
const dCall = (c, n) =>
  `CallCardContent(\n${ind(n + 1)}nodeId: ${dStr(c.nodeId)},\n${ind(n + 1)}direction: CallDirection.${c.direction},\n${ind(n + 1)}icon: ${dStr(
    c.icon,
  )},\n${ind(n + 1)}title: ${dStr(c.title)},\n${ind(n + 1)}subtitle: ${dList(
    c.subtitle.map((s) => `LabTextSpan(${dStr(s.text)}, LabTextWeight.${s.weight})`),
    n + 1,
    'LabTextSpan',
  )},\n${ind(n)})`;
const dSection = (s, n) => `AlbumSectionContent(
${ind(n + 1)}id: ${dStr(s.id)},
${ind(n + 1)}figmaName: ${dStr(s.figmaName)},
${ind(n + 1)}nodeId: ${dStr(s.nodeId)},
${ind(n + 1)}tone: LabTone.${s.tone},
${ind(n + 1)}cover: ${dImgN(s.cover)},
${ind(n + 1)}title: ${dStr(s.title)},
${ind(n + 1)}subtitle: ${dStr(s.subtitle)},
${ind(n + 1)}stats: AlbumStatsContent(photos: ${dStr(s.stats.photos)}, calls: ${dStr(s.stats.calls)}),
${ind(n + 1)}callCards: ${dList(s.callCards.map((c) => dCall(c, n + 2)), n + 1, 'CallCardContent')},
${ind(n + 1)}grid: ${dGrid(s.grid, n + 1)},
${ind(n)})`;
const dToast = (t, n) => `ToastContent(
${ind(n + 1)}screenNodeId: ${dStr(t.screenNodeId)},
${ind(n + 1)}nodeId: ${dStr(t.nodeId)},
${ind(n + 1)}text: ${dStr(t.text)},
${ind(n + 1)}icon: ${dStr(t.icon)},
${ind(n + 1)}iconIsPlaceholder: ${t.iconIsPlaceholder},
${ind(n)})`;

const dStrList = (xs) => `<String>[${xs.map(dStr).join(', ')}]`;
const dSpans = (spans, n) => dList(spans.map((s) => `LabTextSpan(${dStr(s.text)}, LabTextWeight.${s.weight})`), n, 'LabTextSpan');
const dFeatured = (t) =>
  `FeaturedTileContent(nodeId: ${dStr(t.nodeId)}, image: ${dImg(t.image)}, row: ${t.row}, col: ${t.col}, rowSpan: ${t.rowSpan}, colSpan: ${t.colSpan}, liked: ${t.liked})`;
const dCallV5 = (c, n) =>
  `CallCardV5Content(\n${ind(n + 1)}nodeId: ${dStr(c.nodeId)},\n${ind(n + 1)}variant: ${dStr(c.variant)},\n${ind(n + 1)}direction: CallDirection.${c.direction},\n${ind(n + 1)}icon: ${dStr(
    c.icon,
  )},\n${ind(n + 1)}title: ${dStr(c.title)},\n${ind(n + 1)}subtitle: ${dSpans(c.subtitle, n + 1)},\n${ind(n)})`;
const dSectionV5 = (s, n) => `AlbumV5SectionContent(
${ind(n + 1)}id: ${dStr(s.id)},
${ind(n + 1)}figmaName: ${dStr(s.figmaName)},
${ind(n + 1)}nodeId: ${dStr(s.nodeId)},
${ind(n + 1)}kind: AlbumSectionKind.${s.kind},
${ind(n + 1)}tint: ${dStr(s.tint)},
${ind(n + 1)}heroGradient: ${s.heroGradient === null ? 'null' : dStr(s.heroGradient)},
${ind(n + 1)}cover: ${dImgN(s.cover)},
${ind(n + 1)}title: ${dStr(s.title)},
${ind(n + 1)}subtitle: ${dStr(s.subtitle)},
${ind(n + 1)}stats: AlbumStatsContent(photos: ${dStr(s.stats.photos)}, calls: ${dStr(s.stats.calls)}),
${ind(n + 1)}callCards: ${dList(s.callCards.map((c) => dCallV5(c, n + 2)), n + 1, 'CallCardV5Content')},
${ind(n + 1)}grid: ${dGrid(s.grid, n + 1)},
${ind(n + 1)}featured: ${dList(s.featured.map(dFeatured), n + 1, 'FeaturedTileContent')},
${ind(n)})`;
const dViewer = (v) =>
  `ViewerContent(screenNodeId: ${dStr(v.screenNodeId)}, cardNodeId: ${dStr(v.cardNodeId)}, image: ${dImg(v.image)}, date: ${dStr(v.date)}, actions: ${dStrList(v.actions)})`;
const dAction = (a) => `SettingsActionContent(nodeId: ${dStr(a.nodeId)}, label: ${dStr(a.label)}, icon: ${dStr(a.icon)})`;

const A = content.albumDay;
const G = content.albumGangneung;
const T = content.transcript;
const P = T.player;
const C = content.inCall;
const B = content.photoBoothSample;
const K = content.camera;

const dart = `// ${HEADER}
// dart format off
// ignore_for_file: lines_longer_than_80_chars, constant_identifier_names
// 콘텐츠는 Figma 원문 그대로 (오타 '자긴 전 대화', 시간 표기 불일치 포함 — 수정 금지).
// 색은 없다 (색은 tokens.json 색 역할 — Figma 값·모드). 이미지 필드는 에셋 경로 문자열 → Image.asset(path).
// 그리드 row/col 은 1-based (파일명 rRcC 와 동일). PhotoGridContent.photos = 그리드 순서 사진 목록 (배치는 layoutPhotoGrid).

/// 콘텐츠 이미지 에셋 경로 (pubspec: assets/content/).
abstract final class LabImages {
${files.map((f) => `  static const String ${camelFile(f)} = 'assets/content/${f}';`).join('\n')}

  static const List<String> all = <String>[
${files.map((f) => `    ${camelFile(f)},`).join('\n')}
  ];

  /// 처리 후 실제 픽셀 크기 (aspect ratio 계산용).
  static const Map<String, LabImageSize> sizes = <String, LabImageSize>{
${files.map((f) => `    ${camelFile(f)}: LabImageSize(${imageByFile.get(f).output.width}, ${imageByFile.get(f).output.height}),`).join('\n')}
  };
}

class LabImageSize {
  const LabImageSize(this.width, this.height);
  final int width;
  final int height;
}

enum LabTone { dark, light }

enum LabTextWeight { regular, medium }

enum LabAlign { left, right }

enum CallDirection { outgoing, incoming, missed }

/// 한 문단 안의 스타일 구간 (Figma span). weight 는 Interlude Medium/Regular.
class LabTextSpan {
  const LabTextSpan(this.text, this.weight);
  final String text;
  final LabTextWeight weight;
}

/// 텍스트 그라데이션: 텍스트 박스 폭 기준 0..solidUntil 은 강조 색, solidUntil..1 에서 기본 색으로 페이드 (색은 role).
class GradientTextContent {
  const GradientTextContent({required this.solidUntil});
  final double solidUntil;
}

class LabNodeIds {
  const LabNodeIds({required this.light, required this.dark});
  final String light;
  final String dark;
}

class CallCardContent {
  const CallCardContent({required this.nodeId, required this.direction, required this.icon, required this.title, required this.subtitle});
  final String nodeId;
  final CallDirection direction;
  /// Tabler 아이콘 키 ('arrow-up-right' | 'arrow-down-left')
  final String icon;
  final String title;
  final List<LabTextSpan> subtitle;
}

class AlbumStatsContent {
  const AlbumStatsContent({required this.photos, required this.calls});
  final String photos;
  final String calls;
}

/// 그리드 사진 한 장. liked = 2x2 로 크게 (좋아요 — docs/interaction-spec.md §1).
class GridPhotoContent {
  const GridPhotoContent({required this.image, required this.liked});
  /// 에셋 경로
  final String image;
  /// 초기 좋아요 상태 (16-3 추천 타일 2장 = true, 그 외 false)
  final bool liked;
}

class PhotoGridContent {
  const PhotoGridContent({required this.columns, required this.rows, required this.photos});
  final int columns;
  /// Figma 셀 배치 row-major (추천 타일이 덮은 칸 포함). 마지막 행은 columns 보다 짧을 수 있다 (왼쪽부터 채움). 값 = 에셋 경로.
  /// 레거시 — 현재 PhotoGrid 가 사용. 배치 엔진은 photos 를 쓴다.
  final List<List<String>> rows;
  /// 그리드 순서 사진 목록 + 초기 좋아요. 배치 = layoutPhotoGrid(photos.map((p) => p.liked).toList(), columns) (photo_grid_layout.dart).
  /// 추천 타일이 있으면 Figma 에 보이는 사진만 (덮인 칸 제외, 타일 사진은 앵커 자리에 liked) — 16-3 = 24장, #1·#14 liked.
  final List<GridPhotoContent> photos;
}

class AlbumSectionContent {
  const AlbumSectionContent({required this.id, required this.figmaName, required this.nodeId, required this.tone, required this.cover, required this.title, required this.subtitle, required this.stats, required this.callCards, required this.grid});
  final String id;
  final String figmaName;
  final String nodeId;
  /// 섹션 배경 명암 (dark = 사진 배경 섹션, light = 밝은 배경 섹션)
  final LabTone tone;
  /// 히어로 커버 에셋 경로 (null = 텍스트 헤더만)
  final String? cover;
  final String title;
  final String subtitle;
  final AlbumStatsContent stats;
  final List<CallCardContent> callCards;
  final PhotoGridContent? grid;
}

class AlbumDayContent {
  const AlbumDayContent({required this.screenNodeId, required this.sections});
  final String screenNodeId;
  final List<AlbumSectionContent> sections;
}

class FeaturedTileContent {
  const FeaturedTileContent({required this.nodeId, required this.image, required this.row, required this.col, required this.rowSpan, required this.colSpan, required this.liked});
  final String nodeId;
  final String image;
  /// 1-based 시작 셀
  final int row;
  final int col;
  final int rowSpan;
  final int colSpan;
  final bool liked;
}

class QuoteLineContent {
  const QuoteLineContent({required this.nodeId, required this.text, required this.align, required this.gradient});
  final String nodeId;
  final String text;
  final LabAlign align;
  final GradientTextContent? gradient;
}

class QuoteCardContent {
  const QuoteCardContent({required this.nodeId, required this.label, required this.labelAlign, required this.lines});
  final String nodeId;
  final String label;
  final LabAlign labelAlign;
  final List<QuoteLineContent> lines;
}

class TabBarContent {
  const TabBarContent({required this.nodeId, required this.selectedIndex, required this.avatar});
  final String nodeId;
  final int selectedIndex;
  final String avatar;
}

class AlbumGangneungContent {
  const AlbumGangneungContent({required this.screenNodeId, required this.title, required this.date, required this.cover, required this.grid, required this.featured, required this.quoteCard, required this.tabBar});
  final String screenNodeId;
  final String title;
  final String date;
  final String cover;
  final PhotoGridContent grid;
  /// 2x2 추천 타일 — 덮는 일반 셀은 그리지 않는다. 레거시 (현재 PhotoGrid 가 사용) — 같은 정보가 grid.photos 의 liked 로 들어 있다
  final List<FeaturedTileContent> featured;
  final QuoteCardContent quoteCard;
  final TabBarContent tabBar;
}

class TranscriptLineContent {
  const TranscriptLineContent({required this.id, required this.nodeIds, required this.text, required this.side, required this.inHighlight, required this.current, required this.gradient});
  final String id;
  final LabNodeIds nodeIds;
  /// '\\n' = Figma 의 강제 줄바꿈
  final String text;
  /// 화자: left / right 정렬
  final LabAlign side;
  /// 하이라이트 카드 안의 줄인지
  final bool inHighlight;
  /// 현재 재생 중인 줄 (카라오케 그라데이션)
  final bool current;
  final GradientTextContent? gradient;
}

class PlayerMarkerContent {
  const PlayerMarkerContent({required this.nodeIds, required this.leftPx, required this.widthPx, required this.start, required this.width});
  final LabNodeIds nodeIds;
  final double leftPx;
  final double widthPx;
  /// trackWidthPx 기준 분수 (0..1)
  final double start;
  final double width;
}

class PlayerContent {
  const PlayerContent({required this.nodeIds, required this.currentTime, required this.duration, required this.durationSeconds, required this.playing, required this.trackWidthPx, required this.trackWidthPxDark, required this.progressWidthPx, required this.progress, required this.thumbLeftPx, required this.thumbSizePx, required this.thumbCenterPx, required this.thumbCenter, required this.markers});
  final LabNodeIds nodeIds;
  final String currentTime;
  final String duration;
  final int durationSeconds;
  /// 일시정지 아이콘 표시 = 재생 중
  final bool playing;
  /// Figma 트랙 폭 (light 2042:3224 metadata). 분수는 이 값 기준.
  final double trackWidthPx;
  /// dark 2042:3105 는 렌더 실측 ≈154 (metadata 없음)
  final double trackWidthPxDark;
  final double progressWidthPx;
  final double progress;
  final double thumbLeftPx;
  final double thumbSizePx;
  final double thumbCenterPx;
  final double thumbCenter;
  final List<PlayerMarkerContent> markers;
}

class TranscriptContent {
  const TranscriptContent({required this.screenNodeIds, required this.title, required this.date, required this.darkBackground, required this.lines, required this.player});
  final LabNodeIds screenNodeIds;
  final String title;
  final String date;
  /// dark 테마 풀블리드 배경 (light 는 이미지 없음)
  final String darkBackground;
  /// 읽는 순서
  final List<TranscriptLineContent> lines;
  final PlayerContent player;
}

class ToastContent {
  const ToastContent({required this.screenNodeId, required this.nodeId, required this.text, required this.icon, required this.iconIsPlaceholder});
  final String screenNodeId;
  final String nodeId;
  final String text;
  /// Tabler 아이콘 키 ('-filled' 접미사 = filled 변형)
  final String icon;
  /// Figma 'placeholder' 인스턴스 (border-none) — 실제 아이콘 미정
  final bool iconIsPlaceholder;
}

class InCallToastsContent {
  const InCallToastsContent({required this.systemMessage, required this.sleepModeRequest});
  /// 16-8: 진입 직후 1회
  final ToastContent systemMessage;
  /// 16-4: 달 버튼
  final ToastContent sleepModeRequest;
}

class InCallContent {
  const InCallContent({required this.screenNodeIds, required this.name, required this.timer, required this.background, required this.toasts});
  final List<String> screenNodeIds;
  final String name;
  final String timer;
  final String background;
  final InCallToastsContent toasts;
}

class PhotoBoothSampleContent {
  const PhotoBoothSampleContent({required this.nodeId, required this.image});
  final String nodeId;
  final String image;
}

/// 카메라 촬영 모드 (세그먼트 컨트롤 순서 = modes 순서)
enum CameraModeId { photo, video }

class CameraModeContent {
  const CameraModeContent({required this.id, required this.nodeId, required this.labelNodeId, required this.label});
  final CameraModeId id;
  /// 세그먼트 노드 (2056:3394 사진 · 2056:3412 동영상)
  final String nodeId;
  final String labelNodeId;
  /// Figma 원문 라벨 ('사진' · '동영상')
  final String label;
}

class CameraContent {
  const CameraContent({required this.screenNodeId, required this.placeholderNodeId, required this.placeholder, required this.initialMode, required this.modes});
  final String screenNodeId;
  /// 뷰파인더 노드 (2058:3415)
  final String placeholderNodeId;
  /// 뷰파인더 placeholder 에셋 경로 (768x1024, 3:4) — 카메라가 없으면(시뮬레이터) 촬영 결과로도 쓴다
  final String placeholder;
  /// Figma 에서 선택된 모드 (사진)
  final CameraModeId initialMode;
  final List<CameraModeContent> modes;
}

// ---------------------------------------------------------------------------
// v5 (reference/figma-v5 — 원본 rg1ff6r7hw74V5Cw2Sqazr, 페이지 design 2131:1284)
// ---------------------------------------------------------------------------

/// 앨범 날짜 섹션 종류 (E12): 사진 + 통화 · 통화만 (텍스트 헤더) · 사진만
enum AlbumSectionKind { photosCalls, callsOnly, photosOnly }

/// portrait = 3:4 (Figma 2170:8313) · landscape = 4:3 (cameo E10)
enum CapturedOrientation { portrait, landscape }

/// 사진 시트의 실시간 카메라 칸 — 열 col, 행 row..row+rowSpan-1 을 덮는다 (1-based)
class SheetLiveCellContent {
  const SheetLiveCellContent({required this.nodeId, required this.image, required this.row, required this.col, required this.rowSpan});
  final String nodeId;
  /// 시뮬레이터용 placeholder 에셋 경로 (실기기는 카메라 프리뷰)
  final String image;
  final int row;
  final int col;
  final int rowSpan;
}

class SheetPhotoContent {
  const SheetPhotoContent({required this.image, required this.selected});
  final String image;
  /// Figma 선택 상태 (opacity 0.3 + 체크)
  final bool selected;
}

class PhotoSheetContent {
  const PhotoSheetContent({required this.screenNodeId, required this.nodeId, required this.title, required this.liveCell, required this.columns, required this.rows, required this.photos});
  final String screenNodeId;
  final String nodeId;
  /// '사진'
  final String title;
  final SheetLiveCellContent liveCell;
  final int columns;
  /// Figma 셀 배치 row-major (실시간 칸이 덮은 칸 포함)
  final List<List<String>> rows;
  /// 보이는 사진만 row-major (덮인 칸 제외) + 선택 상태
  final List<SheetPhotoContent> photos;
}

class CapturedCardContent {
  const CapturedCardContent({required this.nodeId, required this.image, required this.orientation});
  final String nodeId;
  final String image;
  final CapturedOrientation orientation;
}

class InCallV5ToastsContent {
  const InCallV5ToastsContent({required this.sleep, required this.highlight});
  /// moon — 파트너 취침 전환 (오타 원문 그대로)
  final ToastContent sleep;
  /// rewind-15 — 하이라이트 저장
  final ToastContent highlight;
}

/// 통화 v5 (2170:8678 · 9065 · 2176:9162 · 2170:8774 · 8313)
class InCallV5Content {
  const InCallV5Content({required this.screenNodeIds, required this.name, required this.timer, required this.background, required this.toasts, required this.photoSheet, required this.capturedCard});
  final List<String> screenNodeIds;
  final String name;
  final String timer;
  /// 바탕 사진 (opacity CameoLayout.callV5BackgroundPhotoOpacity)
  final String background;
  final InCallV5ToastsContent toasts;
  final PhotoSheetContent photoSheet;
  final CapturedCardContent capturedCard;
}

class CameraV5Content {
  const CameraV5Content({required this.screenNodeId, required this.viewfinderNodeId, required this.viewfinder, required this.thumbnailNodeId, required this.thumbnail, required this.toast});
  final String screenNodeId;
  final String viewfinderNodeId;
  /// 뷰파인더 placeholder (실기기 = 프리뷰) — 시뮬레이터 촬영 결과
  final String viewfinder;
  final String thumbnailNodeId;
  /// 마지막 사진 썸네일 (= 인스턴트 사진)
  final String thumbnail;
  /// 파트너 인스턴트 토스트 (CameoMotion.instantPartnerDelay)
  final ToastContent toast;
}

class ViewerContent {
  const ViewerContent({required this.screenNodeId, required this.cardNodeId, required this.image, required this.date, required this.actions});
  final String screenNodeId;
  final String cardNodeId;
  final String image;
  /// 자리표시 원문 '오늘, 00시 00분'
  final String date;
  /// buttonOption 아이콘 키 순서
  final List<String> actions;
}

/// 사진 보기 (2170:7914) · 인스턴트 보기 (2170:6159)
class ViewerV5Content {
  const ViewerV5Content({required this.photo, required this.instant});
  final ViewerContent photo;
  final ViewerContent instant;
}

class TabBarV5Content {
  const TabBarV5Content({required this.nodeId, required this.avatar});
  final String nodeId;
  /// 탭 0 아바타 이미지 22 r4 (커플 셀카)
  final String avatar;
}

class CallCardV5Content {
  const CallCardV5Content({required this.nodeId, required this.variant, required this.direction, required this.icon, required this.title, required this.subtitle});
  final String nodeId;
  /// call-list 변형 'default' | 'scrim' | 'failed' (Figma 변형 이름 — 'scrim' = v6 CallListVariant.list, tokens layout.callListV6.\$roles)
  final String variant;
  final CallDirection direction;
  /// 방향 데이터로 정한 Tabler 아이콘 (E4) — 'arrow-up-right' | 'arrow-down-left'
  final String icon;
  final String title;
  /// v5: run 모두 Regular (bodySm)
  final List<LabTextSpan> subtitle;
}

class AlbumV5SectionContent {
  const AlbumV5SectionContent({required this.id, required this.figmaName, required this.nodeId, required this.kind, required this.tint, required this.heroGradient, required this.cover, required this.title, required this.subtitle, required this.stats, required this.callCards, required this.grid, required this.featured});
  final String id;
  final String figmaName;
  final String nodeId;
  final AlbumSectionKind kind;
  /// 섹션 배경 틴트 = 색 역할 키 (모드 무관) → CameoColors.byRole[tint]
  final String tint;
  /// 히어로 그라데이션 이름 (callsOnly = null)
  final String? heroGradient;
  final String? cover;
  final String title;
  final String subtitle;
  final AlbumStatsContent stats;
  final List<CallCardV5Content> callCards;
  /// photos = 보이는 사진 + liked (featured 2x2) — layoutPhotoGrid 입력
  final PhotoGridContent? grid;
  final List<FeaturedTileContent> featured;
}

class AlbumV5NavContent {
  const AlbumV5NavContent({required this.selectLabel, required this.actions});
  /// '선택'
  final String selectLabel;
  final List<String> actions;
}

class AlbumV5SelectNavContent {
  const AlbumV5SelectNavContent({required this.actions});
  final List<String> actions;
}

/// 앨범 홈 타임라인 (2170:6590 = 2232:2109) — 섹션은 최신 → 과거
class AlbumV5Content {
  const AlbumV5Content({required this.screenNodeId, required this.contentNodeId, required this.nav, required this.selectNav, required this.sections});
  final String screenNodeId;
  final String contentNodeId;
  final AlbumV5NavContent nav;
  final AlbumV5SelectNavContent selectNav;
  final List<AlbumV5SectionContent> sections;
}

class SettingsActionContent {
  const SettingsActionContent({required this.nodeId, required this.label, required this.icon});
  final String nodeId;
  final String label;
  final String icon;
}

/// 설정 v5 (2176:11011) — Figma 원문. 앱은 이름 = 세션, 날짜 = days (app-content settingsV5 템플릿)
class SettingsV5Content {
  const SettingsV5Content({required this.screenNodeId, required this.hero, required this.names, required this.days, required this.dayCount, required this.daySuffix, required this.editProfile, required this.disconnect});
  final String screenNodeId;
  final String hero;
  /// '이주영, 이유림'
  final String names;
  final int days;
  /// '200일째' (bodyMdMedium)
  final String dayCount;
  /// ' 공유중' (bodyMd)
  final String daySuffix;
  final SettingsActionContent editProfile;
  final SettingsActionContent disconnect;
}

class TranscriptV5LineContent {
  const TranscriptV5LineContent({required this.id, required this.nodeId, required this.text, required this.side, required this.inHighlight, required this.current});
  final String id;
  final String nodeId;
  /// '\\n' = Figma 의 강제 줄바꿈
  final String text;
  final LabAlign side;
  final bool inHighlight;
  /// 현재 줄 — CameoGradients.karaokeV5
  final bool current;
}

class InlinePhotoContent {
  const InlinePhotoContent({required this.nodeId, required this.image, required this.afterLineId});
  final String nodeId;
  final String image;
  /// 이 줄 바로 뒤 (같은 줄 블록 안, gap 8)
  final String afterLineId;
}

class PlayerV5MarkerContent {
  const PlayerV5MarkerContent({required this.nodeId, required this.leftPx, required this.widthPx, required this.start, required this.width});
  final String nodeId;
  final double leftPx;
  final double widthPx;
  /// trackWidthPx 기준 분수 (0..1)
  final double start;
  final double width;
}

class PlayerV5Content {
  const PlayerV5Content({required this.nodeId, required this.currentTime, required this.duration, required this.durationSeconds, required this.playing, required this.trackWidthPx, required this.progressWidthPx, required this.progress, required this.thumbLeftPx, required this.thumbSizePx, required this.thumbCenterPx, required this.thumbCenter, required this.markers});
  final String nodeId;
  final String currentTime;
  final String duration;
  final int durationSeconds;
  final bool playing;
  final double trackWidthPx;
  final double progressWidthPx;
  final double progress;
  final double thumbLeftPx;
  final double thumbSizePx;
  final double thumbCenterPx;
  final double thumbCenter;
  final List<PlayerV5MarkerContent> markers;
}

/// 통화 기록 v5 A (2176:9241, dark)
class TranscriptV5Content {
  const TranscriptV5Content({required this.screenNodeId, required this.variantNodeIds, required this.title, required this.date, required this.navActions, required this.lines, required this.inlinePhoto, required this.player});
  final String screenNodeId;
  /// 탐색안 B · C · D (라우트 없음)
  final List<String> variantNodeIds;
  final String title;
  final String date;
  final List<String> navActions;
  final List<TranscriptV5LineContent> lines;
  final InlinePhotoContent inlinePhoto;
  final PlayerV5Content player;
}

/// iPhone 16 - 6 (album)
const AlbumDayContent labAlbumDay = AlbumDayContent(
  screenNodeId: ${dStr(A.screenNodeId)},
  sections: ${dList(A.sections.map((s) => dSection(s, 2)), 1, 'AlbumSectionContent')},
);

/// iPhone 16 - 3 (album 강릉)
const AlbumGangneungContent labAlbumGangneung = AlbumGangneungContent(
  screenNodeId: ${dStr(G.screenNodeId)},
  title: ${dStr(G.title)},
  date: ${dStr(G.date)},
  cover: ${dImg(G.cover)},
  grid: ${dGrid(G.grid, 1)},
  featured: ${dList(
    G.featured.map(
      (t) =>
        `FeaturedTileContent(nodeId: ${dStr(t.nodeId)}, image: ${dImg(t.image)}, row: ${t.row}, col: ${t.col}, rowSpan: ${t.rowSpan}, colSpan: ${t.colSpan}, liked: ${t.liked})`,
    ),
    1,
    'FeaturedTileContent',
  )},
  quoteCard: QuoteCardContent(
    nodeId: ${dStr(G.quoteCard.nodeId)},
    label: ${dStr(G.quoteCard.label)},
    labelAlign: LabAlign.${G.quoteCard.labelAlign},
    lines: ${dList(
      G.quoteCard.lines.map(
        (l) => `QuoteLineContent(nodeId: ${dStr(l.nodeId)}, text: ${dStr(l.text)}, align: LabAlign.${l.align}, gradient: ${dGradient(l.gradient)})`,
      ),
      2,
      'QuoteLineContent',
    )},
  ),
  tabBar: TabBarContent(nodeId: ${dStr(G.tabBar.nodeId)}, selectedIndex: ${G.tabBar.selectedIndex}, avatar: ${dImg(G.tabBar.avatar)}),
);

/// iPhone 16 - 13 (dark 모드, nodeIds.light) / 16 - 12 (사진 배경, nodeIds.dark) 통화 기록 상세
const TranscriptContent labTranscript = TranscriptContent(
  screenNodeIds: ${dNodeIds(T.screenNodeIds)},
  title: ${dStr(T.title)},
  date: ${dStr(T.date)},
  darkBackground: ${dImg(T.darkBackground)},
  lines: ${dList(
    T.lines.map(
      (l) =>
        `TranscriptLineContent(id: ${dStr(l.id)}, nodeIds: ${dNodeIds(l.nodeIds)}, text: ${dStr(l.text)}, side: LabAlign.${l.side}, inHighlight: ${l.inHighlight}, current: ${l.current}, gradient: ${dGradient(l.gradient)})`,
    ),
    1,
    'TranscriptLineContent',
  )},
  player: PlayerContent(
    nodeIds: ${dNodeIds(P.nodeIds)},
    currentTime: ${dStr(P.currentTime)},
    duration: ${dStr(P.duration)},
    durationSeconds: ${P.durationSeconds},
    playing: ${P.playing},
    trackWidthPx: ${dNum(P.trackWidthPx)},
    trackWidthPxDark: ${dNum(P.trackWidthPxDark)},
    progressWidthPx: ${dNum(P.progressWidthPx)},
    progress: ${dNum(P.progress)},
    thumbLeftPx: ${dNum(P.thumbLeftPx)},
    thumbSizePx: ${dNum(P.thumbSizePx)},
    thumbCenterPx: ${dNum(P.thumbCenterPx)},
    thumbCenter: ${dNum(P.thumbCenter)},
    markers: ${dList(
      P.markers.map(
        (m) =>
          `PlayerMarkerContent(nodeIds: ${dNodeIds(m.nodeIds)}, leftPx: ${dNum(m.leftPx)}, widthPx: ${dNum(m.widthPx)}, start: ${dNum(m.start)}, width: ${dNum(m.width)})`,
      ),
      2,
      'PlayerMarkerContent',
    )},
  ),
);

/// iPhone 16 - 8…11 / 16 - 4 통화 중
const InCallContent labInCall = InCallContent(
  screenNodeIds: <String>[${C.screenNodeIds.map(dStr).join(', ')}],
  name: ${dStr(C.name)},
  timer: ${dStr(C.timer)},
  background: ${dImg(C.background)},
  toasts: InCallToastsContent(
    systemMessage: ${dToast(C.toasts.systemMessage, 2)},
    sleepModeRequest: ${dToast(C.toasts.sleepModeRequest, 2)},
  ),
);

/// Frame 2042:3117 — 화면 아님 (에셋만)
const PhotoBoothSampleContent labPhotoBoothSample = PhotoBoothSampleContent(nodeId: ${dStr(B.nodeId)}, image: ${dImg(B.image)});

/// iPhone 16 - 14 카메라 촬영 (v3 신규)
const CameraContent labCamera = CameraContent(
  screenNodeId: ${dStr(K.screenNodeId)},
  placeholderNodeId: ${dStr(K.placeholderNodeId)},
  placeholder: ${dImg(K.placeholder)},
  initialMode: CameraModeId.${K.initialMode},
  modes: ${dList(
    K.modes.map(
      (m) => `CameraModeContent(id: CameraModeId.${m.id}, nodeId: ${dStr(m.nodeId)}, labelNodeId: ${dStr(m.labelNodeId)}, label: ${dStr(m.label)})`,
    ),
    1,
    'CameraModeContent',
  )},
);

/// 통화 v5
const InCallV5Content labInCallV5 = InCallV5Content(
  screenNodeIds: ${dStrList(content.inCallV5.screenNodeIds)},
  name: ${dStr(content.inCallV5.name)},
  timer: ${dStr(content.inCallV5.timer)},
  background: ${dImg(content.inCallV5.background)},
  toasts: InCallV5ToastsContent(
    sleep: ${dToast(content.inCallV5.toasts.sleep, 2)},
    highlight: ${dToast(content.inCallV5.toasts.highlight, 2)},
  ),
  photoSheet: PhotoSheetContent(
    screenNodeId: ${dStr(content.inCallV5.photoSheet.screenNodeId)},
    nodeId: ${dStr(content.inCallV5.photoSheet.nodeId)},
    title: ${dStr(content.inCallV5.photoSheet.title)},
    liveCell: SheetLiveCellContent(nodeId: ${dStr(content.inCallV5.photoSheet.liveCell.nodeId)}, image: ${dImg(content.inCallV5.photoSheet.liveCell.image)}, row: ${content.inCallV5.photoSheet.liveCell.row}, col: ${content.inCallV5.photoSheet.liveCell.col}, rowSpan: ${content.inCallV5.photoSheet.liveCell.rowSpan}),
    columns: ${content.inCallV5.photoSheet.columns},
    rows: ${dList(content.inCallV5.photoSheet.rows.map((r) => `<String>[${r.map(dImg).join(', ')}]`), 2, 'List<String>')},
    photos: ${dList(content.inCallV5.photoSheet.photos.map((p) => `SheetPhotoContent(image: ${dImg(p.image)}, selected: ${p.selected})`), 2, 'SheetPhotoContent')},
  ),
  capturedCard: CapturedCardContent(nodeId: ${dStr(content.inCallV5.capturedCard.nodeId)}, image: ${dImg(content.inCallV5.capturedCard.image)}, orientation: CapturedOrientation.${content.inCallV5.capturedCard.orientation}),
);

/// 카메라 v5 (2170:5682)
const CameraV5Content labCameraV5 = CameraV5Content(
  screenNodeId: ${dStr(content.cameraV5.screenNodeId)},
  viewfinderNodeId: ${dStr(content.cameraV5.viewfinderNodeId)},
  viewfinder: ${dImg(content.cameraV5.viewfinder)},
  thumbnailNodeId: ${dStr(content.cameraV5.thumbnailNodeId)},
  thumbnail: ${dImg(content.cameraV5.thumbnail)},
  toast: ${dToast(content.cameraV5.toast, 1)},
);

/// 사진 보기 · 인스턴트 보기
const ViewerV5Content labViewerV5 = ViewerV5Content(
  photo: ${dViewer(content.viewerV5.photo)},
  instant: ${dViewer(content.viewerV5.instant)},
);

/// 탭바 v5 (bottom-nav 2166:5444)
const TabBarV5Content labTabBarV5 = TabBarV5Content(nodeId: ${dStr(content.tabBarV5.nodeId)}, avatar: ${dImg(content.tabBarV5.avatar)});

/// 앨범 홈 타임라인 v5
const AlbumV5Content labAlbumV5 = AlbumV5Content(
  screenNodeId: ${dStr(content.albumV5.screenNodeId)},
  contentNodeId: ${dStr(content.albumV5.contentNodeId)},
  nav: AlbumV5NavContent(selectLabel: ${dStr(content.albumV5.nav.selectLabel)}, actions: ${dStrList(content.albumV5.nav.actions)}),
  selectNav: AlbumV5SelectNavContent(actions: ${dStrList(content.albumV5.selectNav.actions)}),
  sections: ${dList(content.albumV5.sections.map((s) => dSectionV5(s, 2)), 1, 'AlbumV5SectionContent')},
);

/// 설정 v5 (Figma 원문)
const SettingsV5Content labSettingsV5 = SettingsV5Content(
  screenNodeId: ${dStr(content.settingsV5.screenNodeId)},
  hero: ${dImg(content.settingsV5.hero)},
  names: ${dStr(content.settingsV5.names)},
  days: ${content.settingsV5.days},
  dayCount: ${dStr(content.settingsV5.dayCount)},
  daySuffix: ${dStr(content.settingsV5.daySuffix)},
  editProfile: ${dAction(content.settingsV5.editProfile)},
  disconnect: ${dAction(content.settingsV5.disconnect)},
);

/// 통화 기록 v5 A
const TranscriptV5Content labTranscriptV5 = TranscriptV5Content(
  screenNodeId: ${dStr(content.transcriptV5.screenNodeId)},
  variantNodeIds: ${dStrList(content.transcriptV5.variantNodeIds)},
  title: ${dStr(content.transcriptV5.title)},
  date: ${dStr(content.transcriptV5.date)},
  navActions: ${dStrList(content.transcriptV5.navActions)},
  lines: ${dList(
    content.transcriptV5.lines.map(
      (l) =>
        `TranscriptV5LineContent(id: ${dStr(l.id)}, nodeId: ${dStr(l.nodeId)}, text: ${dStr(l.text)}, side: LabAlign.${l.side}, inHighlight: ${l.inHighlight}, current: ${l.current})`,
    ),
    1,
    'TranscriptV5LineContent',
  )},
  inlinePhoto: InlinePhotoContent(nodeId: ${dStr(content.transcriptV5.inlinePhoto.nodeId)}, image: ${dImg(content.transcriptV5.inlinePhoto.image)}, afterLineId: ${dStr(content.transcriptV5.inlinePhoto.afterLineId)}),
  player: PlayerV5Content(
    nodeId: ${dStr(content.transcriptV5.player.nodeId)},
    currentTime: ${dStr(content.transcriptV5.player.currentTime)},
    duration: ${dStr(content.transcriptV5.player.duration)},
    durationSeconds: ${content.transcriptV5.player.durationSeconds},
    playing: ${content.transcriptV5.player.playing},
    trackWidthPx: ${dNum(content.transcriptV5.player.trackWidthPx)},
    progressWidthPx: ${dNum(content.transcriptV5.player.progressWidthPx)},
    progress: ${dNum(content.transcriptV5.player.progress)},
    thumbLeftPx: ${dNum(content.transcriptV5.player.thumbLeftPx)},
    thumbSizePx: ${dNum(content.transcriptV5.player.thumbSizePx)},
    thumbCenterPx: ${dNum(content.transcriptV5.player.thumbCenterPx)},
    thumbCenter: ${dNum(content.transcriptV5.player.thumbCenter)},
    markers: ${dList(
      content.transcriptV5.player.markers.map(
        (m) =>
          `PlayerV5MarkerContent(nodeId: ${dStr(m.nodeId)}, leftPx: ${dNum(m.leftPx)}, widthPx: ${dNum(m.widthPx)}, start: ${dNum(m.start)}, width: ${dNum(m.width)})`,
      ),
      2,
      'PlayerV5MarkerContent',
    )},
  ),
);
`;

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
const APP_CONTENT = resolve(CONTENT_DIR, 'app-content.json');
const OUT_APP_TS = resolve(root, 'apps/rn/src/content/app.generated.ts');
const OUT_APP_DART = resolve(root, 'apps/flutter/lib/content/app.g.dart');
const APP_HEADER =
  'GENERATED by design-system/scripts/build-content.mjs from design-system/content/app-content.json — DO NOT EDIT';
const IMAGE_NAME = /\.(jpg|png)$/;
const stripMeta = (v) =>
  Array.isArray(v)
    ? v.map(stripMeta)
    : v !== null && typeof v === 'object'
      ? Object.fromEntries(
          Object.entries(v)
            .filter(([k]) => !k.startsWith('$'))
            .map(([k, x]) => [k, stripMeta(x)]),
        )
      : v;
const app = stripMeta(readJson(APP_CONTENT));
const kindOf = (v) =>
  Array.isArray(v) ? 'array' : v === null ? 'null' : typeof v === 'number' ? (Number.isInteger(v) ? 'int' : 'double') : typeof v;
const shapeOf = (v) => (kindOf(v) === 'object' ? `{${Object.keys(v).join(',')}}` : kindOf(v));
function validateApp(v, path) {
  const k = kindOf(v);
  if (k === 'null') fail(`app-content.json: ${path}: null 은 쓰지 않는다`);
  if (!/^[a-z][A-Za-z0-9]*$/.test(path.split('.').pop()) && !/^\d+$/.test(path.split('.').pop()) && path !== 'app')
    fail(`app-content.json: ${path}: 키는 camelCase`);
  if (k === 'string' && IMAGE_NAME.test(v) && !imageByFile.has(v)) fail(`app-content.json: ${path}: manifest 에 없는 이미지 '${v}'`);
  if (k === 'array') {
    if (v.length === 0) fail(`app-content.json: ${path}: 빈 배열`);
    const s = shapeOf(v[0]);
    v.forEach((x, i) => {
      if (shapeOf(x) !== s && !(['int', 'double'].includes(kindOf(x)) && ['int', 'double'].includes(kindOf(v[0]))))
        fail(`app-content.json: ${path}.${i}: 배열 항목의 모양이 다르다 (${shapeOf(x)} ≠ ${s})`);
      validateApp(x, `${path}.${i}`);
    });
  }
  if (k === 'object') for (const [key, x] of Object.entries(v)) validateApp(x, `${path}.${key}`);
}
validateApp(app, 'app');
if (app.partner?.partner?.name !== content.inCall.name)
  fail(`app-content.json: partner.partner.name '${app.partner?.partner?.name}' 은 lab inCall.name '${content.inCall.name}' 과 같아야 한다`);

const appTs = `// ${APP_HEADER}
// v4 cameo 문구 (Figma 에 없는 화면 — docs/v4-plan.md). 이미지 값은 LabImageFile 파일명 (labImages[file] 로 source).
// '{name}' 자리표시는 fillTemplate 으로 채운다 (Flutter fillTemplate 과 같은 규칙).

export const appContent = ${tsJson(app)} as const;
export type AppContent = typeof appContent;

/** '{key}' 를 vars[key] 로 바꾼다. 모르는 키는 그대로 둔다. Flutter \`fillTemplate\` 과 같다. */
export function fillTemplate(template: string, vars: Readonly<Record<string, string | number>>): string {
  return template.replace(/\\{(\\w+)\\}/g, (whole, key: string) => (key in vars ? String(vars[key]) : whole));
}
`;

const pascalKey = (k) => k.charAt(0).toUpperCase() + k.slice(1);
const singular = (k) => (k.endsWith('ies') ? `${k.slice(0, -3)}y` : k.endsWith('s') ? k.slice(0, -1) : `${k}Item`);
const dartClasses = [];

function dartOf(v, className, n, classes = dartClasses) {
  const k = kindOf(v);
  if (k === 'string') return ['String', IMAGE_NAME.test(v) ? dImg(v) : dStr(v)];
  if (k === 'int') return ['int', String(v)];
  if (k === 'double') return ['double', dNum(v)];
  if (k === 'boolean') return ['bool', String(v)];
  if (k === 'array') {
    const itemClass = className;
    const items = v.map((x) => dartOf(x, itemClass, n + 1, classes));
    const type = items.some(([t]) => t === 'double') ? 'double' : items[0][0];
    return [`List<${type}>`, dList(items.map(([, e]) => e), n, type)];
  }
  const fields = Object.entries(v).map(([key, x]) => {
    const child = kindOf(x) === 'array' ? `${className}${pascalKey(singular(key))}` : `${className}${pascalKey(key)}`;
    const [type, expr] = dartOf(x, child, n + 1, classes);
    return { key, type, expr };
  });
  if (!classes.some((c) => c.name === className)) classes.push({ name: className, fields });
  return [className, `${className}(\n${fields.map((f) => `${ind(n + 1)}${f.key}: ${f.expr},`).join('\n')}\n${ind(n)})`];
}
const [, appExpr] = dartOf(app, 'AppContent', 0);
const appDart = `// ${APP_HEADER}
// v4 cameo 문구 (Figma 에 없는 화면 — docs/v4-plan.md). 이미지 = LabImages 에셋 경로.
// '{name}' 자리표시는 fillTemplate 으로 채운다 (RN fillTemplate 과 같은 규칙).
// dart format off
// ignore_for_file: lines_longer_than_80_chars

import 'lab.g.dart';

/// '{key}' 를 vars[key] 로 바꾼다. 모르는 키는 그대로 둔다. RN \`fillTemplate\` 과 같다.
String fillTemplate(String template, Map<String, Object> vars) =>
    template.replaceAllMapped(RegExp(r'\\{(\\w+)\\}'), (m) => vars.containsKey(m[1]) ? '\${vars[m[1]]}' : m[0]!);

${dartClasses
  .reverse()
  .map(
    (c) => `class ${c.name} {
  const ${c.name}({${c.fields.map((f) => `required this.${f.key}`).join(', ')}});
${c.fields.map((f) => `  final ${f.type} ${f.key};`).join('\n')}
}`,
  )
  .join('\n\n')}

/// v4 앱 문구 (app-content.json)
const AppContent appContent = ${appExpr};
`;

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
if (!raw.v6 || typeof raw.v6 !== 'object') fail('lab-content.json: v6 없음 (Figma v6 원문)');
const labV6 = stripMeta(raw.v6);
const isIconKey = (key) => key === 'icon' || key === 'icons' || /Icons?$/.test(key) || /(^a|A)ctions$/.test(key);
function validateLabV6(v, path, key) {
  const k = kindOf(v);
  const last = path.split('.').pop();
  if (k === 'null') fail(`lab-content.json: ${path}: null 은 쓰지 않는다`);
  if (!/^[a-z][A-Za-z0-9]*$/.test(last) && !/^\d+$/.test(last)) fail(`lab-content.json: ${path}: 키는 camelCase`);
  if (k === 'string') {
    if (IMAGE_NAME.test(v) && !imageByFile.has(v)) fail(`lab-content.json: ${path}: manifest 에 없는 이미지 '${v}'`);
    if (isIconKey(key) && !ICON_KEYS.has(v)) fail(`lab-content.json: ${path}: tokens.json icon.used 에 없는 아이콘 '${v}'`);
  }
  if (k === 'array') {
    if (v.length === 0) fail(`lab-content.json: ${path}: 빈 배열`);
    const s0 = shapeOf(v[0]);
    v.forEach((x, i) => {
      if (shapeOf(x) !== s0) fail(`lab-content.json: ${path}.${i}: 배열 항목의 모양이 다르다 (${shapeOf(x)} ≠ ${s0})`);
      validateLabV6(x, `${path}.${i}`, key);
    });
  }
  if (k === 'object') for (const [ck, x] of Object.entries(v)) validateLabV6(x, `${path}.${ck}`, ck);
}
validateLabV6(labV6, 'v6', 'v6');
if (!labV6.connected?.message?.includes('{partner}')) fail("lab-content.json: v6.connected.message 는 '{partner}' 자리표시를 쓴다 (원문 'Yurim' = inCall.name)");
if (!labV6.camera?.partnerToast?.text?.startsWith(content.inCall.name))
  fail(`lab-content.json: v6.camera.partnerToast.text 는 상대 이름 '${content.inCall.name}' 으로 시작한다 (Figma 원문)`);
const labV6Ts = `
/** v6 원문 (Figma 원본 페이지 product 2256:4477 — reference/figma-v6). 범용 트리: lab-content.json v6 그대로 ('$' 메모 제외). */
export const labV6 = ${tsJson(labV6)} as const;
export type LabV6Content = typeof labV6;
`;
const labV6Classes = [];
const [, labV6Expr] = dartOf(labV6, 'LabV6', 0, labV6Classes);
const labV6Dart = `
// ---------------------------------------------------------------------------
// v6 (reference/figma-v6 — 원본 페이지 product 2256:4477). 범용 트리: lab-content.json v6 그대로 ('$' 메모 제외).
// ---------------------------------------------------------------------------

${labV6Classes
  .reverse()
  .map(
    (c) => `class ${c.name} {
  const ${c.name}({${c.fields.map((f) => `required this.${f.key}`).join(', ')}});
${c.fields.map((f) => `  final ${f.type} ${f.key};`).join('\n')}
}`,
  )
  .join('\n\n')}

/// v6 원문 (lab-content.json v6)
const LabV6 labV6 = ${labV6Expr};
`;

// ---------------------------------------------------------------------------
// write / check
// ---------------------------------------------------------------------------
let stale = false;
function sync(file, content) {
  const current = existsSync(file) ? readFileSync(file) : null;
  const same = current !== null && Buffer.compare(current, Buffer.isBuffer(content) ? content : Buffer.from(content)) === 0;
  if (CHECK) {
    if (!same) {
      console.error(`✗ stale: ${file}`);
      stale = true;
    }
    return;
  }
  if (!same) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}

for (const dir of [FL_ASSETS, ...(process.argv.includes('--rn') ? [RN_ASSETS] : [])]) {
  for (const f of files) sync(join(dir, f), imageBytes.get(f));
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir)) {
    if (imageByFile.has(f)) continue;

    if (CHECK) {
      if (!isAppleDouble(f)) {
        console.error(`✗ stray: ${join(dir, f)}`);
        stale = true;
      }
    } else rmSync(join(dir, f), { force: true });
  }
}
if (process.argv.includes('--rn')) sync(OUT_TS, ts + labV6Ts);
sync(OUT_DART, generatedComments(dart + labV6Dart));
if (process.argv.includes('--rn')) sync(OUT_APP_TS, appTs);
sync(OUT_APP_DART, generatedComments(appDart));

if (CHECK) {
  if (stale) {
    console.error('콘텐츠 생성물이 design-system/content 와 다릅니다. `node design-system/scripts/build-content.mjs` 를 실행하세요.');
    process.exit(1);
  }
  console.log(`✓ content up to date (${files.length} images, TS + Dart)`);
} else {
  console.log(`synced ${files.length} images → RN/Flutter assets/content, generated lab.generated.ts + lab.g.dart`);
}
