#!/usr/bin/env node
// Generate and validate design tokens from the canonical JSON and recorded variable values. Flutter is the default target; --rn explicitly enables the retained reference output.

//

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generatedComments } from './generated-comments.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const tokens = JSON.parse(readFileSync(resolve(root, 'design-system/tokens.json'), 'utf8'));
const CHECK = process.argv.includes('--check');

const OUT_TS = resolve(root, 'apps/rn/src/design-system/tokens.generated.ts');
const OUT_DART = resolve(root, 'apps/flutter/lib/design_system/tokens.g.dart');
const HEADER = 'GENERATED by design-system/scripts/build-tokens.mjs from design-system/tokens.json — DO NOT EDIT';

// ---------- helpers ----------
const errors = [];
const check = (cond, msg) => {
  if (!cond) errors.push(msg);
};
const round = (n) => Math.round(n * 1e6) / 1e6;
const isObj = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const RATIO = /^(\d+(?:\.\d+)?):(\d+(?:\.\d+)?)$/;

function strip(node) {
  if (Array.isArray(node)) return node.map(strip);
  if (!isObj(node)) return node;
  if ('$value' in node) return node.$value;
  const out = {};
  for (const [k, v] of Object.entries(node)) if (!k.startsWith('$')) out[k] = strip(v);
  return out;
}

function resolveRatios(node) {
  if (Array.isArray(node)) return node.map(resolveRatios);
  if (isObj(node)) return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, resolveRatios(v)]));
  if (typeof node === 'string' && RATIO.test(node)) {
    const [, a, b] = node.match(RATIO);
    return Number(a) / Number(b);
  }
  return node;
}

const camel = (parts) =>
  parts
    .flatMap((p) => String(p).split(/[^A-Za-z0-9]+/))
    .filter(Boolean)
    .map((p, i) => (i === 0 ? p.charAt(0).toLowerCase() + p.slice(1) : p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

function flatten(obj, prefix = [], out = []) {
  for (const [k, v] of Object.entries(obj)) {
    if (isObj(v)) flatten(v, [...prefix, k], out);
    else out.push([[...prefix, k], v]);
  }
  return out;
}

const DART_RESERVED = new Set([
  'abstract', 'as', 'assert', 'async', 'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'covariant',
  'default', 'deferred', 'do', 'dynamic', 'else', 'enum', 'export', 'extends', 'extension', 'external', 'factory',
  'false', 'final', 'finally', 'for', 'Function', 'get', 'hide', 'if', 'implements', 'import', 'in', 'interface', 'is',
  'late', 'library', 'mixin', 'new', 'null', 'on', 'operator', 'part', 'required', 'rethrow', 'return', 'set', 'show',
  'static', 'super', 'switch', 'sync', 'this', 'throw', 'true', 'try', 'typedef', 'var', 'void', 'while', 'with', 'yield',
  'values', 'index', 'name', 'hashCode', 'runtimeType',
]);
const dartId = (name, suffix) => (DART_RESERVED.has(name) ? `${name}${suffix}` : name);

function dartIds(className, ids) {
  const seen = new Set();
  for (const id of ids) {
    check(/^[a-z][A-Za-z0-9]*$/.test(id), `${className}: 잘못된 Dart 식별자 '${id}'`);
    check(!DART_RESERVED.has(id), `${className}: Dart 예약어 '${id}'`);
    check(!seen.has(id), `${className}: 중복 식별자 '${id}'`);
    seen.add(id);
  }
}

const dartNum = (n) => (Number.isInteger(n) ? `${n}.0` : `${n}`);
const dartStr = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const dartRatio = (s) => {
  const [, a, b] = s.match(RATIO);
  return `${dartNum(Number(a))} / ${dartNum(Number(b))}`;
};
const dartColor = (hex) => {
  const h = hex.replace('#', '').toUpperCase();
  const rgb = h.slice(0, 6);
  const a = h.length === 8 ? h.slice(6, 8) : 'FF';
  return `Color(0x${a}${rgb})`;
};

// ---------- colors ----------
const PROVENANCE = new Set(['figma', 'figma-geometry', 'figma-inferred', 'cameo']);

const MODES = ['light', 'dark'];
const HEX = /^#[0-9a-f]{6}([0-9a-f]{2})?$/;
const roleTokens = tokens.color.roles;
const roleNames = Object.keys(roleTokens);
const isRole = (r) => typeof r === 'string' && r in roleTokens;
check(
  isObj(tokens.color.$modes) && Object.keys(tokens.color.$modes).join() === MODES.join(),
  `color.$modes 의 키는 ${MODES.join(', ')} 순서여야 한다`,
);

function cssToHex(css) {
  const h2 = (n) => Math.round(n).toString(16).padStart(2, '0');
  const s = String(css).trim().toLowerCase();
  if (HEX.test(s)) return s.length === 9 && s.endsWith('ff') ? s.slice(0, 7) : s;
  const m = /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/.exec(s);
  if (!m) return null;
  const [r, g, b] = [m[1], m[2], m[3]].map(Number);
  const a = m[4] === undefined ? 1 : Number(m[4]);
  if ([r, g, b].some((c) => c > 255) || a > 1) return null;

  const alpha = Math.round(a * 255 + 1e-6);
  return `#${h2(r)}${h2(g)}${h2(b)}${alpha === 255 ? '' : h2(alpha)}`;
}

// Recorded color values keep token validation independent of local design exports.
const snapshot = JSON.parse(readFileSync(resolve(root, 'design-system/variable-defs.json'), 'utf8'));
const decodeMap = (map) => new Map(Object.entries(map).map(([key, values]) => [key, new Set(values)]));
const decodeModes = (modes) => Object.fromEntries(Object.entries(modes).map(([mode, map]) => [mode, decodeMap(map)]));
const figmaDefs = decodeModes(snapshot.observed);
const byVersion = Object.fromEntries(Object.entries(snapshot.versions).map(([version, modes]) => [version, decodeModes(modes)]));
const v6Union = new Map(Object.entries(snapshot.v6).map(([key, modes]) => [key, Object.fromEntries(Object.entries(modes).map(([mode, values]) => [mode, new Set(values)]))]));

const colorByMode = { light: {}, dark: {} };

const modeIndependent = new Set();
for (const [role, t] of Object.entries(roleTokens)) {
  const where = `color ${role}`;
  check(!('$placeholder' in t), `${where}: $placeholder 는 폐지됨 — Figma 값을 $value 에 쓴다`);
  check(PROVENANCE.has(t.$provenance), `${where}: $provenance 누락/오류`);
  const v = t.$value;
  const fallback = t.$modeFallback ?? {};
  if (typeof v === 'string') {
    check(HEX.test(v), `${where}: $value 는 소문자 #rrggbb 또는 #rrggbbaa (${v})`);
    check(!('$modeFallback' in t), `${where}: 모드 무관 값에는 $modeFallback 을 쓰지 않는다`);
    for (const m of MODES) colorByMode[m][role] = v;
    modeIndependent.add(role);
  } else if (isObj(v)) {
    check(Object.keys(v).sort().join() === [...MODES].sort().join(), `${where}: 모드 값 키는 ${MODES.join('/')} 여야 한다`);
    for (const m of MODES) {
      check(typeof v[m] === 'string' && HEX.test(v[m]), `${where}: $value.${m} 는 소문자 #rrggbb 또는 #rrggbbaa (${v[m]})`);
      colorByMode[m][role] = v[m];
    }
    check(isObj(fallback) && Object.keys(fallback).length < MODES.length, `${where}: $modeFallback 은 { 복사된 모드: 원본 모드 } 하나`);
    for (const [to, from] of Object.entries(fallback)) {
      check(MODES.includes(to) && MODES.includes(from) && to !== from, `${where}: $modeFallback ${to} ← ${from} 가 잘못됨`);
      check(v[to] === v[from], `${where}: $modeFallback ${to} ← ${from} 인데 두 값이 다르다`);
    }
    if (v.light === v.dark) check(Object.keys(fallback).length === 1, `${where}: 두 모드 값이 같으면 $modeFallback 으로 출처를 밝히거나 단일 $value 로 쓴다`);
  } else {
    check(false, `${where}: $value 가 없다 — 모든 색 역할은 Figma 값이 필요하다 (placeholder 규칙 폐지, 2026-09-28)`);
    continue;
  }

  if (t.$provenance === 'figma') {
    const fv = t.$figmaVariable;
    const legacy = typeof t.$legacyOf === 'string';
    const nameOk = legacy
      ? t.$legacyOf === fv && role === `${fv}-legacy`
      : fv === role || (typeof fv === 'string' && fv.toLowerCase() === role && typeof t.$codeKeyNote === 'string');
    check(
      nameOk,
      `${where}: figma 역할 이름은 $figmaVariable 과 같아야 한다 (대소문자만 다르면 $codeKeyNote 로 코드 키를 설명 · 같은 이름 옛 값은 <변수>-legacy + $legacyOf)`,
    );

    const fvers = t.$figmaVersion;
    const versionOf = (m) => (typeof fvers === 'string' ? fvers : isObj(fvers) ? fvers[m] : undefined);
    const VERSIONS = ['v6', 'v6-legacy', 'v5', 'v3'];
    for (const m of MODES) {
      const ver = versionOf(m);
      check(ver === undefined || VERSIONS.includes(ver), `${where}: $figmaVersion ${m} 는 ${VERSIONS.join(' | ')} 중 하나 (${ver})`);
    }
    check(!legacy || MODES.every((m) => m in fallback || versionOf(m) !== undefined), `${where}: legacy 역할은 모든 관측 모드에 $figmaVersion 이 필요`);

    for (const m of MODES) {
      if (m in fallback) continue;
      const ver = versionOf(m);
      const modes = typeof v === 'string' ? MODES : [m];
      const source = (mm) =>
        ver === undefined ? figmaDefs[mm] : ver === 'v6-legacy' ? byVersion.v6.legacy : byVersion[ver][mm];
      const seen = [...new Set(modes.flatMap((mm) => [...(source(mm).get(fv) ?? [])]))];
      check(
        seen.includes(colorByMode[m][role]),
        `${where}: ${m} 값 ${colorByMode[m][role]} 이 get_variable_defs(${ver ?? '전 버전'} ${ver === 'v6-legacy' ? 'legacy' : modes.join('/')}) 에 없다 (관측: ${seen.join(', ') || '없음'})`,
      );
    }
    for (const [alt, frames] of Object.entries(t.$variants ?? {})) {
      check(HEX.test(alt) && Array.isArray(frames) && frames.length > 0, `${where}: $variants 는 { hex: [프레임] }`);
      check([...(figmaDefs.light.get(fv) ?? []), ...(figmaDefs.dark.get(fv) ?? [])].includes(alt), `${where}: $variants ${alt} 가 get_variable_defs 에 없다`);
    }
  } else if (t.$provenance === 'cameo') {
    check(typeof v === 'string', `${where}: raw(cameo) 역할은 모드 무관 단일 $value`);
    if ('$figmaRaw' in t) {
      const hex = cssToHex(t.$figmaRaw);
      check(hex !== null, `${where}: $figmaRaw 를 해석할 수 없다 (${t.$figmaRaw})`);
      check(hex === v, `${where}: $figmaRaw ${t.$figmaRaw} (= ${hex}) 와 $value ${v} 가 다르다`);
    } else {
      check(typeof t.$cameoValue === 'string', `${where}: cameo 역할은 $figmaRaw(Figma raw 값) 또는 $cameoValue(값이 Figma 에 없는 이유) 가 필요`);
    }
  }
}

for (const [k, u] of v6Union) {
  const where = `figma-v6 변수 ${k}`;
  if (u.light.size || u.dark.size) {
    const r = roleTokens[k];
    check(r?.$provenance === 'figma' && r.$figmaVariable === k, `${where}: 같은 이름 figma 역할이 없다 (tokens.json color.roles — 모든 v6 변수를 가져온다)`);
    if (r)
      for (const m of MODES)
        for (const val of u[m]) check(colorByMode[m][k] === val, `${where}: ${m} 역할 값 ${colorByMode[m][k]} ≠ v6 관측 ${val}`);
  }
  for (const val of u.legacy) {
    const name = `${k}-legacy`;
    const r = roleTokens[name];
    check(r?.$legacyOf === k, `${where}: 옛 값 ${val} 의 역할 ${name} ($legacyOf) 이 없다`);
    if (!r) continue;
    const modesFromLegacy = MODES.filter((m) => (typeof r.$figmaVersion === 'string' ? r.$figmaVersion : r.$figmaVersion?.[m]) === 'v6-legacy');
    check(modesFromLegacy.length > 0, `${where}: ${name} 의 $figmaVersion 에 v6-legacy 모드가 없다`);
    for (const m of modesFromLegacy) check(colorByMode[m][name] === val, `${where}: ${name} ${m} 값 ${colorByMode[m][name]} ≠ v6 옛 값 ${val}`);
  }
}
const colorRoles = colorByMode.light;
const colorRolesDark = colorByMode.dark;

const colorConfirmed = true;
const colorId = (role) => camel(role.split('/'));
dartIds('CameoColors', roleNames.map(colorId));

const PALETTE_FIELDS = ['mode', 'byRole', 'gradients', 'shadows', 'light', 'dark', 'of'];
dartIds('CameoPalette', [...roleNames.map(colorId), ...PALETTE_FIELDS]);

(function checkLayoutRoles(node, path) {
  if (!isObj(node)) return;
  for (const [k, v] of Object.entries(node)) {
    if (k === '$roles') {
      (function leaves(x, p) {
        if (typeof x === 'string') check(isRole(x.split(' ')[0]), `${p}: 없는 색 역할 '${x}'`);
        else if (isObj(x)) for (const [kk, vv] of Object.entries(x)) leaves(vv, `${p}.${kk}`);
        else check(false, `${p}: $roles 값은 역할 문자열 또는 객체`);
      })(v, `${path}.$roles`);
    } else if (isObj(v)) checkLayoutRoles(v, `${path}.${k}`);
  }
})(tokens.layout, 'layout');

// ---------- typography ----------
const typo = tokens.typography;
const fontFamily = strip(typo.fontFamily);
const fontWeight = strip(typo.fontWeight);
const typeScale = { size: strip(typo.fontSize), lineHeight: strip(typo.lineHeight) };

const flutterFontFallback = {};
const fallbackOfWeight = {};
{
  const group = typo.fontFallback?.flutter;
  check(isObj(group), 'typography.fontFallback.flutter: 항목 그룹이어야 한다');
  for (const [name, raw] of Object.entries(isObj(group) ? group : {})) {
    if (name.startsWith('$')) continue;
    const where = `typography.fontFallback.flutter.${name}`;
    check(isObj(raw) && '$value' in raw, `${where}: $value 필요`);
    if (!isObj(raw)) continue;
    const families = raw.$value;
    check(PROVENANCE.has(raw.$provenance), `${where}: $provenance 누락`);
    check(
      Array.isArray(families) && families.length > 0 && families.every((f) => typeof f === 'string' && f.length > 0),
      `${where}: 비어 있지 않은 패밀리 이름 배열이어야 한다`,
    );
    check(
      !(Array.isArray(families) ? families : []).some((f) => Object.values(fontFamily).includes(f)),
      `${where}: 폰트 역할 패밀리(default·system)와 겹치면 안 된다 — Interlude 가 항상 먼저다`,
    );
    const weights = raw.$weights;
    check(Array.isArray(weights) && weights.length > 0, `${where}: $weights 는 비어 있지 않은 weight 키 배열`);
    for (const w of Array.isArray(weights) ? weights : []) {
      check(w in fontWeight, `${where}: 없는 weight '${w}'`);
      check(!(w in fallbackOfWeight), `${where}: weight '${w}' 가 '${fallbackOfWeight[w]}' 항목과 겹친다`);
      fallbackOfWeight[w] = name;
    }
    const below = raw.$fontSizeBelow;
    check(below === undefined || (typeof below === 'number' && below > 0), `${where}: $fontSizeBelow 는 양수`);
    flutterFontFallback[name] = { families, weights, fontSizeBelow: below };
  }
  for (const w of Object.keys(fontWeight)) {
    check(w in fallbackOfWeight, `typography.fontFallback.flutter: weight '${w}' 를 받는 항목이 없다`);
  }
}
const fallbackId = (name) => camel(['fallback', name]);

const systemTrackingTable = (() => {
  const raw = typo.fontFallback?.systemTracking;
  if (raw === undefined) return null;
  const where = 'typography.fontFallback.systemTracking';
  check(isObj(raw) && isObj(raw.$value), `${where}: $value 는 { 크기(pt): font units } 객체`);
  if (!isObj(raw) || !isObj(raw.$value)) return null;
  check(PROVENANCE.has(raw.$provenance), `${where}: $provenance 누락`);
  check(typeof raw.$source === 'string' && raw.$source.length > 0, `${where}: $source (읽은 폰트 파일) 필요`);
  const upm = raw.$unitsPerEm;
  check(typeof upm === 'number' && upm > 0, `${where}: $unitsPerEm 은 양수`);
  const points = Object.entries(raw.$value).map(([k, v]) => [Number(k), v]);
  check(points.length >= 2, `${where}: 크기 2개 이상`);
  for (const [size, units] of points) {
    check(Number.isFinite(size) && size > 0, `${where}: 크기 키 '${size}' 는 양수`);
    check(Number.isInteger(units), `${where}.${size}: font units 는 정수`);
  }
  check(points.every(([s], i) => i === 0 || s > points[i - 1][0]), `${where}: 크기 키는 오름차순`);
  const status = String(typo.fontFamily?.default?.$assetStatus ?? '');
  check(
    status.startsWith('MISSING'),
    `${where}: Interlude(fontFamily.default)가 번들되면 라틴 글리프가 SF 로 그려지지 않는다 — 이 항목을 지우거나 ` +
      `Interlude 의 'trak' 표로 바꾼다 (README §4 폰트 · §7 '폰트 폴백')`,
  );
  return { points, upm };
})();

function systemTrackingAt(size) {
  const { points, upm } = systemTrackingTable;
  let units = points[points.length - 1][1];
  if (size <= points[0][0]) units = points[0][1];
  else {
    for (let i = 1; i < points.length; i++) {
      const [s1, u1] = points[i];
      if (size > s1) continue;
      const [s0, u0] = points[i - 1];
      units = u0 + ((u1 - u0) * (size - s0)) / (s1 - s0);
      break;
    }
  }
  return round((units * size) / upm);
}

const textStyles = Object.fromEntries(
  Object.entries(typo.styles).map(([name, raw]) => {
    const s = strip(raw);
    check(PROVENANCE.has(raw.$provenance), `typography.styles.${name}: $provenance 누락`);
    check('$figmaStyle' in raw, `typography.styles.${name}: $figmaStyle 필요 (없으면 null)`);
    check(typeof raw.$sourceNode === 'string', `typography.styles.${name}: $sourceNode 필요`);
    check(s.fontFamily in fontFamily, `typography.styles.${name}: 없는 fontFamily '${s.fontFamily}'`);
    check(s.fontWeight in fontWeight, `typography.styles.${name}: 없는 fontWeight '${s.fontWeight}'`);
    check(['px', 'multiplier'].includes(s.lineHeightUnit), `typography.styles.${name}: lineHeightUnit 은 px|multiplier`);
    const fb = flutterFontFallback[fallbackOfWeight[s.fontWeight]];
    check(
      !fb?.fontSizeBelow || s.fontSize < fb.fontSizeBelow,
      `typography.styles.${name}: ${s.fontWeight} ${s.fontSize}pt — fontFallback.flutter.${fallbackOfWeight[s.fontWeight]} 는 ` +
        `${fb?.fontSizeBelow}pt 미만 전용 (광학 크기 17 고정). iOS 에서 opsz 를 받는 폴백이 이 weight 에 없다 — README §7 '폰트 폴백'`,
    );
    const lineHeightPx = s.lineHeightUnit === 'multiplier' ? s.fontSize * s.lineHeight : s.lineHeight;
    return [
      name,
      {
        family: s.fontFamily,
        weight: s.fontWeight,
        fontSize: s.fontSize,
        lineHeight: round(lineHeightPx),
        lineHeightMultiplier: round(lineHeightPx / s.fontSize),
        letterSpacing: round((s.fontSize * s.letterSpacingPercent) / 100),
      },
    ];
  }),
);
dartIds('CameoTextStyles', [...Object.keys(textStyles), 'byName', 'systemTracking']);

const systemTracking = systemTrackingTable
  ? Object.fromEntries(
      [...new Set(Object.values(textStyles).map((s) => s.fontSize))]
        .sort((a, b) => a - b)
        .map((size) => [size, systemTrackingAt(size)]),
    )
  : {};
dartIds('CameoFontFamily', [
  ...Object.keys(fontFamily).map((k) => dartId(camel([k]), 'Family')),
  ...Object.keys(flutterFontFallback).map(fallbackId),
]);

// ---------- icon / space / radius / border ----------
const icon = {
  grid: tokens.icon.grid.$value,
  strokeWidth: tokens.icon.strokeWidth.$value,
  size: strip(tokens.icon.size),
};
const space = strip(tokens.space);
const radius = strip(tokens.radius);
const borderWidth = strip(tokens.borderWidth);

// ---------- effects ----------
const effectTokens = tokens.effect;
const effect = strip(effectTokens);
const blurSigma = {};

const blurMaterial = {};
const BLUR_MATERIALS = ['glass', 'blur'];
const shadows = {};
for (const [name, e] of Object.entries(effect)) {
  const meta = effectTokens[name];
  if (name !== 'liquidGlass') check(PROVENANCE.has(meta.$provenance), `effect.${name}: $provenance 누락`);
  if ('blurRadius' in e && 'blurSigma' in e) {
    check(e.blurSigma === e.blurRadius / 2, `effect.${name}: blurSigma 는 blurRadius / 2 여야 한다`);
    blurSigma[name] = e.blurSigma;
    check(BLUR_MATERIALS.includes(e.material), `effect.${name}: material 은 ${BLUR_MATERIALS.join(' | ')} 중 하나여야 한다`);

    const figmaGlass = /\bGLASS\b/.test(String(meta.$figmaEffects ?? ''));
    const g1 = /\bG1\b/.test(String(meta.$materialDecision ?? ''));
    check(
      e.material === 'glass' ? figmaGlass || g1 : !figmaGlass,
      `effect.${name}: material '${e.material}' 가 $figmaEffects/$materialDecision 과 맞지 않는다 (Figma GLASS → 'glass', GLASS 없이 'glass' 는 $materialDecision 에 G1)`,
    );
    blurMaterial[name] = e.material;
  }
  const sh = 'offsetY' in e ? e : isObj(e.shadow) ? e.shadow : null;
  if (sh) {
    check(isRole(sh.colorRole), `effect.${name}: 없는 색 역할 '${sh.colorRole}'`);
    shadows[name] = sh;
  }
}

const GLASS_BACKDROPS = ['default', 'dark', 'light'];
const GLASS_SCHEMES = ['light', 'dark'];
{
  const lg = effect.liquidGlass ?? {};
  for (const [k, v] of Object.entries(lg.native ?? {})) {
    if (k.endsWith('Role')) check(isRole(v) && modeIndependent.has(v), `effect.liquidGlass.native.${k}: 모드 무관 색 역할이어야 한다 ('${v}')`);

    if (k.startsWith('colorScheme')) check(GLASS_SCHEMES.includes(v), `effect.liquidGlass.native.${k}: ${GLASS_SCHEMES.join(' | ')} 중 하나 ('${v}')`);
  }
  for (const [k, v] of Object.entries(lg.backdrop ?? {})) {
    check(GLASS_BACKDROPS.includes(v), `effect.liquidGlass.backdrop.${k}: ${GLASS_BACKDROPS.join(' | ')} 중 하나 ('${v}')`);
  }
}

const flutterBlurRadius = (figmaRadius) => round((figmaRadius / 2 - 0.5) / 0.57735);
dartIds('CameoBlur', Object.keys(blurSigma));
dartIds('CameoShadows', Object.keys(shadows));

// ---------- gradients ----------
const gradient = strip(tokens.gradient);
for (const [name, g] of Object.entries(gradient)) {
  check(['toBottom', 'toRight'].includes(g.direction), `gradient.${name}: direction 은 toBottom|toRight`);
  if (g.stops) {
    let prev = -1;
    for (const s of g.stops) {
      check(isRole(s.color), `gradient.${name}: 없는 색 역할 '${s.color}'`);
      check(s.position >= 0 && s.position <= 1 && s.position >= prev, `gradient.${name}: stop 위치는 0–1 오름차순`);
      prev = s.position;
    }
  } else {
    check(isRole(g.ink) && isRole(g.base), `gradient.${name}: ink/base 는 색 역할이어야 한다`);
    check(g.fadeStart >= 0 && g.fadeStart <= g.fadeEnd && g.fadeEnd <= 1, `gradient.${name}: 0 ≤ fadeStart ≤ fadeEnd ≤ 1`);
  }
}
dartIds('CameoGradients', Object.keys(gradient));

// ---------- layout ----------
const layoutRaw = strip(tokens.layout);
const layout = resolveRatios(layoutRaw);
for (const [name, c] of Object.entries(tokens.layout)) {
  if (name.startsWith('$')) continue;
  check(PROVENANCE.has(c.$provenance), `layout.${name}: $provenance 누락`);
}
const layoutEntries = flatten(layoutRaw);
for (const [path, v] of layoutEntries) {
  const ok =
    typeof v === 'number' ||
    (Array.isArray(v) && v.every((x) => typeof x === 'number' || (typeof x === 'string' && RATIO.test(x))));
  check(ok, `layout.${path.join('.')}: 생성되는 layout 값은 숫자/숫자·비율 배열만 (참조는 $-메타로)`);
}
dartIds('CameoLayout', layoutEntries.map(([p]) => camel(p)));

// ---------- motion ----------
const motionAll = strip(tokens.motion);
const springNames = Object.keys(motionAll.spring);
for (const [k, s] of Object.entries(motionAll.spring)) {
  check(Math.abs(s.damping / (2 * Math.sqrt(s.stiffness * s.mass)) - s.dampingRatio) < 1e-3, `motion.spring.${k}: dampingRatio 불일치`);
}

const springs = Object.fromEntries(
  Object.entries(motionAll.spring).map(([k, s]) => [k, { mass: s.mass, stiffness: s.stiffness, damping: s.damping }]),
);
const { spring: _spring, easing, ...motionRest } = motionAll;
const motion = { ...motionRest, easing };

const motionFields = flatten(motionRest).map(([path, v]) => {
  const key = path[path.length - 1];
  const where = `motion.${path.join('.')}`;
  if (key.endsWith('Ms')) {
    check(typeof v === 'number', `${where}: *Ms 는 숫자`);
    const id = camel([...path.slice(0, -1), key.slice(0, -2)]);
    return [id, `static const Duration ${id} = Duration(milliseconds: ${v});`];
  }
  if (key.endsWith('Role')) {
    check(isRole(v), `${where}: 없는 색 역할 '${v}'`);

    check(modeIndependent.has(v), `${where}: 모드별 역할 '${v}' 는 CameoMotion 정적 상수로 낼 수 없다 (모드 무관 역할만)`);
    const id = camel([...path.slice(0, -1), key.slice(0, -4)]);
    return [id, `static const Color ${id} = CameoColors.${colorId(v)}; // ${v}`];
  }
  if (typeof v === 'string') {
    check((key === 'spring' || key.endsWith('Spring')) && springNames.includes(v), `${where}: 없는 spring '${v}'`);
    const id = camel(path);
    return [id, `static const SpringDescription ${id} = CameoSprings.${v};`];
  }
  check(typeof v === 'number', `${where}: 숫자/문자열 참조만 허용`);
  const id = camel(path);
  return [id, `static const double ${id} = ${dartNum(v)};`];
});
const easingFields = Object.entries(easing).map(([k, [a, b, c, d]]) => {
  const id = `easing${cap(k)}`;
  return [id, `static const Cubic ${id} = Cubic(${[a, b, c, d].map(dartNum).join(', ')});`];
});
dartIds('CameoMotion', [...motionFields, ...easingFields].map(([id]) => id));
dartIds('CameoSprings', springNames);

if (errors.length) {
  console.error('tokens.json 규칙 위반:\n' + errors.map((e) => `  ✗ ${e}`).join('\n'));
  process.exit(1);
}

// ---------- TypeScript ----------
const J = (v) => JSON.stringify(v, null, 2);
const ts = `// ${HEADER}

/** 팔레트 확정 — 모든 색 역할이 Figma 값(알파·모드 포함)을 가진다 (2026-09-28). */
export const colorConfirmed = ${colorConfirmed} as const;
/**
 * 색 역할 → light 모드 값 (기존 API — 모드를 모르는 코드는 light).
 * 역할 이름 = Figma 변수 이름 또는 cameo 이름 (예외: 'background/neutral/interactive' = Figma 'background/neutral/Interactive').
 */
export const color = ${J(colorRoles)} as const;
export type ColorRole = keyof typeof color;
/** 색 역할 → dark 모드 값 (16-13). 한 모드에서만 관측된 역할·모드 무관 역할은 light 와 같은 값 (tokens.json $modeFallback). */
export const colorDark = ${J(colorRolesDark)} as const satisfies Record<ColorRole, string>;
/** 모드 → 역할 → 값. 16-13 = dark, 나머지 화면 = light. */
export const colorModes = { light: color, dark: colorDark } as const;
export type ColorMode = keyof typeof colorModes;
/** 모드와 무관하게 같은 값인 역할 (레거시 Surface/Background/Normal · Material/Shadow, raw cameo 역할) */
export const modeIndependentColorRoles: readonly ColorRole[] = ${J(roleNames.filter((r) => modeIndependent.has(r)))};

export const fontFamily = ${J(fontFamily)} as const;
export const fontWeight = ${J(fontWeight)} as const;
export type FontFamilyRole = keyof typeof fontFamily;
export type FontWeightRole = keyof typeof fontWeight;
/** Figma size/* · line-height/* 변수 (px) */
export const typeScale = ${J(typeScale)} as const;

/** lineHeight/letterSpacing 은 px 로 계산된 값 (Figma % → px). */
export const textStyles = ${J(textStyles)} as const;
export type TextStyleName = keyof typeof textStyles;

export const icon = ${J(icon)} as const;
export type IconSizeName = keyof typeof icon.size;
export const space = ${J(space)} as const;
export const radius = ${J(radius)} as const;
export type RadiusName = keyof typeof radius;
export const borderWidth = ${J(borderWidth)} as const;

export const effect = ${J(effect)} as const;
/** 블러 이펙트별 Gaussian σ (= Figma radius / 2) */
export const blurSigma = ${J(blurSigma)} as const;
export type BlurName = keyof typeof blurSigma;
/**
 * 블러 이펙트별 렌더 재질 (tokens.json effect.$material, v3-plan G1): 'glass' → Liquid Glass (떠 있는 컨트롤 —
 * Figma GLASS 표면 + Figma 가 blur + 채움으로 그린 내비·바·플레이어·카메라 컨트롤), 'blur' → Frosted (카드·안쪽 요소).
 * GlassSurface effect='glass' 가 이 값으로 렌더러를 고른다.
 * Flutter \`CameoBlur.<name>.material\` 과 같은 값.
 */
export type BlurMaterial = ${BLUR_MATERIALS.map((m) => `'${m}'`).join(' | ')};
export const blurMaterial = ${J(blurMaterial)} as const satisfies Record<BlurName, BlurMaterial>;
/** 그림자 (CSS box-shadow 의미론: blurRadius = Figma radius) */
export const shadows = ${J(shadows)} as const;
export type ShadowName = keyof typeof shadows;

/** 그라데이션 — stop 위치는 Figma, 색은 역할. stops 가 없으면 카라오케 텍스트 마스크. */
export const gradient = ${J(gradient)} as const;
export type GradientName = keyof typeof gradient;

export const layout = ${J(layout)} as const;

/** 물리 스프링(mass/stiffness/damping). Flutter SpringDescription 과 동일한 방정식. */
export const springs = ${J(springs)} as const;
export type SpringName = keyof typeof springs;
export const motion = ${J(motion)} as const;
`;

// ---------- Dart ----------
const dartLiteral = (v) => {
  if (typeof v === 'number') return ['double', dartNum(v)];
  if (typeof v === 'string' && RATIO.test(v)) return ['double', dartRatio(v)];
  if (typeof v === 'string') return ['String', dartStr(v)];
  if (typeof v === 'boolean') return ['bool', String(v)];
  if (Array.isArray(v)) return ['List<double>', `[${v.map((x) => dartLiteral(x)[1]).join(', ')}]`];
  throw new Error(`Dart 로 표현할 수 없는 값: ${JSON.stringify(v)}`);
};

const INT_KEYS = new Set(['columns', 'flex', 'featuredSpan']);
const dartFields = (entries) =>
  entries
    .map(([path, v]) => {
      if (INT_KEYS.has(path[path.length - 1]) && Number.isInteger(v)) return `  static const int ${camel(path)} = ${v};`;
      const [type, lit] = dartLiteral(v);
      return `  static const ${type} ${camel(path)} = ${lit};`;
    })
    .join('\n');
const alignment = { toBottom: ['Alignment.topCenter', 'Alignment.bottomCenter'], toRight: ['Alignment.centerLeft', 'Alignment.centerRight'] };
const familyId = (k) => dartId(camel([k]), 'Family');

const dartColorMembers = (mode) => `${roleNames
  .map((r) => {
    const t = roleTokens[r];
    const tag = modeIndependent.has(r) ? ' (모드 무관)' : t.$modeFallback?.[mode] ? ` (${t.$modeFallback[mode]} 값 복사)` : '';
    return `  static const Color ${colorId(r)} = ${dartColor(colorByMode[mode][r])}; // ${r}${tag}`;
  })
  .join('\n')}

  /// 역할 이름(RN ColorRole 과 같은 문자열) → 색
  static const Map<String, Color> byRole = {
${roleNames.map((r) => `    ${dartStr(r)}: ${colorId(r)},`).join('\n')}
  };`;

const dartPaletteArgs = (mode, cls) =>
  [
    `    mode: CameoColorMode.${mode},`,
    `    byRole: ${cls}.byRole,`,
    `    gradients: CameoGradientSet.${mode},`,
    `    shadows: CameoShadowSet.${mode},`,
    ...roleNames.map((r) => `    ${colorId(r)}: ${cls}.${colorId(r)},`),
  ].join('\n');

const dartShadowMembers = (cls) =>
  Object.entries(shadows)
    .map(
      ([k, s]) =>
        `  /// Figma radius ${s.blurRadius} (σ ${s.blurRadius / 2}), 색 역할 ${s.colorRole}
  static const BoxShadow ${k} = BoxShadow(color: ${cls}.${colorId(s.colorRole)}, offset: Offset(${dartNum(s.offsetX)}, ${dartNum(s.offsetY)}), blurRadius: ${dartNum(flutterBlurRadius(s.blurRadius))}, spreadRadius: ${dartNum(s.spread)});`,
    )
    .join('\n');

const dartGradientMembers = (cls) =>
  Object.entries(gradient)
    .map(([k, g]) => {
      if (g.stops) {
        const [begin, end] = alignment[g.direction];
        return `  static const LinearGradient ${k} = LinearGradient(begin: ${begin}, end: ${end}, colors: [${g.stops
          .map((s) => `${cls}.${colorId(s.color)}`)
          .join(', ')}], stops: [${g.stops.map((s) => dartNum(s.position)).join(', ')}]);`;
      }
      return `  static const CameoKaraokeSpec ${k} = (ink: ${cls}.${colorId(g.ink)}, base: ${cls}.${colorId(g.base)}, fadeStart: ${dartNum(g.fadeStart)}, fadeEnd: ${dartNum(g.fadeEnd)});`;
    })
    .join('\n');

const dart = `// ${HEADER}
// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars
// dart format off
import 'package:flutter/animation.dart';
import 'package:flutter/painting.dart';

/// 팔레트 확정 — 모든 색 역할이 Figma 값(알파·모드 포함)을 가진다 (2026-09-28).
const bool kCameoColorConfirmed = ${colorConfirmed};

/// 색 모드 (RN ColorMode 와 같은 이름). 16-13 = dark, 나머지 화면 = light.
enum CameoColorMode { ${MODES.join(', ')} }

/// 색 역할 — **light** 모드 값 (기존 API: 모드를 모르는 코드는 light). dark 는 [CameoColorsDark], 모드 선택은 [CameoPalette.of].
/// 이름 = tokens.json color.roles 키의 camelCase (주석이 원래 역할 이름).
abstract final class CameoColors {
${dartColorMembers('light')}
}

/// 색 역할 — **dark** 모드 값 (16-13). 한 모드에서만 관측된 역할·모드 무관 역할은 [CameoColors] 와 같은 값.
abstract final class CameoColorsDark {
${dartColorMembers('dark')}
}

/// 모드별 팔레트 — 역할별 필드 + byRole + 그 모드로 해석한 그라데이션·그림자. RN colorModes[mode] 와 같은 값.
final class CameoPalette {
  const CameoPalette._({
    required this.mode,
    required this.byRole,
    required this.gradients,
    required this.shadows,
${roleNames.map((r) => `    required this.${colorId(r)},`).join('\n')}
  });

  static const CameoPalette light = CameoPalette._(
${dartPaletteArgs('light', 'CameoColors')}
  );

  static const CameoPalette dark = CameoPalette._(
${dartPaletteArgs('dark', 'CameoColorsDark')}
  );

  static CameoPalette of(CameoColorMode mode) => switch (mode) {
${MODES.map((m) => `        CameoColorMode.${m} => ${m},`).join('\n')}
      };

  final CameoColorMode mode;

  /// 역할 이름(RN ColorRole 과 같은 문자열) → 색
  final Map<String, Color> byRole;

  /// 이 모드로 해석한 그라데이션 ([CameoGradients] / [CameoGradientsDark])
  final CameoGradientSet gradients;

  /// 이 모드로 해석한 그림자 ([CameoShadows] / [CameoShadowsDark])
  final CameoShadowSet shadows;

${roleNames.map((r) => `  /// ${r}\n  final Color ${colorId(r)};`).join('\n')}
}

abstract final class CameoFontFamily {
${Object.entries(fontFamily)
  .map(([k, v]) => `  static const String ${familyId(k)} = ${dartStr(v)};`)
  .join('\n')}

  // 시스템 폴백 (tokens.json typography.fontFallback.flutter) — [defaultFamily] 에 없는 글리프
  // (Interlude 미번들이면 모든 글리프)만 여기서 찾는다. [CameoTextStyles] 는 weight 로 하나를 고른다.
  // 한글은 이 폰트들에도 없어 시스템 문자 폴백(Apple SD Gothic Neo). README §7 '폰트 폴백'.
${Object.entries(flutterFontFallback)
  .map(
    ([name, f]) =>
      `  /// ${f.weights.join(' · ')}${f.fontSizeBelow ? ` (${f.fontSizeBelow}pt 미만)` : ''}\n` +
      `  static const List<String> ${fallbackId(name)} = [${f.families.map(dartStr).join(', ')}];`,
  )
  .join('\n')}
}

abstract final class CameoFontWeight {
${Object.entries(fontWeight)
  .map(([k, v]) => `  static const FontWeight ${camel([k])} = FontWeight.w${v};`)
  .join('\n')}
}

/// Figma size/* · line-height/* 변수 (px)
abstract final class CameoTypeScale {
${Object.entries(typeScale.size).map(([k, v]) => `  static const double size${k} = ${dartNum(v)};`).join('\n')}
${Object.entries(typeScale.lineHeight).map(([k, v]) => `  static const double lineHeight${k} = ${dartNum(v)};`).join('\n')}
}

/// Figma 텍스트 스타일. leadingDistribution.even = CSS/RN 과 같은 half-leading.
///
/// 폰트: [CameoFontFamily.defaultFamily](Interlude Variable)가 항상 먼저이고, 없는 글리프만
/// weight 별 폴백 ([CameoFontFamily] fallback*) → 시스템 폴백(한글) 순으로 찾는다.
/// fontVariations — wght: 가변 폰트는 fontWeight 만으로 wght 축이 바뀌지 않으므로 명시.
/// opsz = fontSize: CoreText(RN) 의 자동 광학 크기와 같게 (축 범위 밖은 폰트가 자르고, 축이 없는 폰트는 무시).
/// regular 폴백(CupertinoSystemText = 시스템 기본 폰트)은 fontVariations 를 받지 않고 광학 크기 17 로 고정 —
/// ${flutterFontFallback.text?.fontSizeBelow ?? '?'}pt 미만 regular 스타일만 쓴다: 20pt 미만은 RN(opsz = 크기, 최소 17)과 거의 같고,
/// 20pt(headingMd — v6 키패드 숫자)는 RN opsz 20 과 3 차이 (쓸 수 있는 폴백 중 가장 가깝다 — README §7 · §12).
/// 시스템 폰트(SF)의 크기별 트래킹(trak)은 SkParagraph 가 적용하지 않는다 → [systemTracking] 을
/// CameoText·KeepAllText(cameoTextSpan)가 SF 로 그려지는 글자 run 에만 letterSpacing 으로 더한다 (README §7 '폰트 폴백').
/// opsz·트래킹은 TextScaler 배율과 무관하게 토큰 크기로 고정.
abstract final class CameoTextStyles {
${Object.entries(textStyles)
  .map(
    ([name, s]) => `  static const TextStyle ${name} = TextStyle(
    fontFamily: CameoFontFamily.${familyId(s.family)},
    fontFamilyFallback: CameoFontFamily.${fallbackId(fallbackOfWeight[s.weight])},
    fontWeight: CameoFontWeight.${camel([s.weight])},
    fontVariations: [FontVariation('wght', ${dartNum(fontWeight[s.weight])}), FontVariation('opsz', ${dartNum(s.fontSize)})],
    fontSize: ${dartNum(s.fontSize)},
    height: ${s.lineHeightMultiplier},
    letterSpacing: ${dartNum(s.letterSpacing)},
    leadingDistribution: TextLeadingDistribution.even,
  );`,
  )
  .join('\n')}

  /// 스타일 키(RN TextStyleName 과 같은 문자열) → 스타일
  static const Map<String, TextStyle> byName = {
${Object.keys(textStyles).map((n) => `    ${dartStr(n)}: ${n},`).join('\n')}
  };

  /// 스타일 크기(fontSize) → 시스템 폰트(SF) 트래킹 pt (tokens.json typography.fontFallback.systemTracking —
  /// SF 'trak' 표를 크기로 선형 보간, units × 크기 / unitsPerEm). CoreText(RN)는 SF 글리프에 이 값을 더하고
  /// SkParagraph 는 더하지 않으므로 cameoTextSpan 이 SF run(한글 제외)의 letterSpacing 에 더한다.
  /// 비어 있으면 보정 없음 (Interlude 번들 후). (double 키는 const 맵에 못 쓴다 → 수정 불가 final 맵)
  static final Map<double, double> systemTracking = Map.unmodifiable(<double, double>{${Object.entries(systemTracking)
    .map(([size, pt]) => `${dartNum(Number(size))}: ${dartNum(pt)}`)
    .join(', ')}});
}

abstract final class CameoIconTokens {
  static const double grid = ${dartNum(icon.grid)};
  static const double strokeWidth = ${dartNum(icon.strokeWidth)};
${Object.entries(icon.size)
  .map(([k, v]) => `  static const double size${cap(k)} = ${dartNum(v)};`)
  .join('\n')}
}

abstract final class CameoSpace {
${Object.entries(space)
  .map(([k, v]) => `  static const double s${k} = ${dartNum(v)};`)
  .join('\n')}
}

abstract final class CameoRadius {
${dartFields(flatten(radius))}
}

abstract final class CameoBorderWidth {
${dartFields(flatten(borderWidth))}
}

/// 블러 렌더 재질 (tokens.json effect.$material) — RN \`BlurMaterial\` 과 같은 이름.
/// [glass] → Liquid Glass (떠 있는 컨트롤 — v3-plan G1) · [blur] → Frosted (카드·안쪽 요소).
enum CameoBlurMaterial { ${BLUR_MATERIALS.join(', ')} }

/// 블러 이펙트 — Gaussian σ (= Figma radius / 2) + 렌더 재질. RN BlurName · blurSigma · blurMaterial 과 같은 이름·값.
enum CameoBlur {
${Object.entries(blurSigma)
  .map(([k, v]) => `  ${k}(${dartNum(v)}, CameoBlurMaterial.${blurMaterial[k]}),`)
  .join('\n')}
  ;

  const CameoBlur(this.sigma, this.material);

  final double sigma;

  /// GlassSurface(effect: GlassEffect.glass) 가 이 값으로 렌더러를 고른다.
  final CameoBlurMaterial material;
}

/// 그림자 (light 모드 색). blurRadius 는 Figma radius(σ = radius/2)를 Flutter BoxShadow 변환식(σ = r·0.57735 + 0.5)으로 역산한 값.
abstract final class CameoShadows {
${dartShadowMembers('CameoColors')}
}

/// 그림자 (dark 모드 색) — [CameoShadows] 와 같은 기하.
abstract final class CameoShadowsDark {
${dartShadowMembers('CameoColorsDark')}
}

/// 모드별 그림자 묶음 ([CameoPalette.shadows]).
final class CameoShadowSet {
  const CameoShadowSet._({${Object.keys(shadows)
    .map((k) => `required this.${k}`)
    .join(', ')}});

  static const CameoShadowSet light = CameoShadowSet._(${Object.keys(shadows)
    .map((k) => `${k}: CameoShadows.${k}`)
    .join(', ')});
  static const CameoShadowSet dark = CameoShadowSet._(${Object.keys(shadows)
    .map((k) => `${k}: CameoShadowsDark.${k}`)
    .join(', ')});

${Object.keys(shadows)
  .map((k) => `  final BoxShadow ${k};`)
  .join('\n')}
}

/// Liquid Glass 렌더 파라미터 (cameo, v3-plan G1) — renderer* = liquid_glass_renderer (길이 dp), native* = RN iOS GlassView 용 (Flutter 미사용),
/// backdrop* = 글래스 배경 톤을 색 모드와 다르게 정하는 화면.
abstract final class CameoEffects {
${dartFields(flatten({ liquidGlass: effect.liquidGlass }))}
}

/// 카라오케 텍스트 마스크: base 색 텍스트 위에 ink 색 텍스트를 [0, fadeStart] 불투명 → fadeEnd 투명 마스크로 겹친다.
typedef CameoKaraokeSpec = ({Color ink, Color base, double fadeStart, double fadeEnd});

/// 그라데이션 (light 모드 색) — stop 위치는 Figma, 색은 역할 (Figma raw 값 그대로, 투명 stop 포함).
/// Figma 는 straight(비 premultiplied) 알파로 보간한다 — Flutter LinearGradient 와 같다 (tokens.json color.$interpolation).
abstract final class CameoGradients {
${dartGradientMembers('CameoColors')}
}

/// 그라데이션 (dark 모드 색) — [CameoGradients] 와 같은 stop.
abstract final class CameoGradientsDark {
${dartGradientMembers('CameoColorsDark')}
}

/// 모드별 그라데이션 묶음 ([CameoPalette.gradients]).
final class CameoGradientSet {
  const CameoGradientSet._({
${Object.keys(gradient)
  .map((k) => `    required this.${k},`)
  .join('\n')}
  });

  static const CameoGradientSet light = CameoGradientSet._(
${Object.keys(gradient)
  .map((k) => `    ${k}: CameoGradients.${k},`)
  .join('\n')}
  );

  static const CameoGradientSet dark = CameoGradientSet._(
${Object.keys(gradient)
  .map((k) => `    ${k}: CameoGradientsDark.${k},`)
  .join('\n')}
  );

${Object.entries(gradient)
  .map(([k, g]) => `  final ${g.stops ? 'LinearGradient' : 'CameoKaraokeSpec'} ${k};`)
  .join('\n')}
}

abstract final class CameoLayout {
${dartFields(layoutEntries)}
}

/// 물리 스프링. RN Reanimated withSpring({mass, stiffness, damping}) 과 동일.
abstract final class CameoSprings {
${Object.entries(springs)
  .map(
    ([k, s]) =>
      `  static const SpringDescription ${k} = SpringDescription(mass: ${dartNum(s.mass)}, stiffness: ${dartNum(s.stiffness)}, damping: ${dartNum(s.damping)});`,
  )
  .join('\n')}

  /// 스프링 이름(RN SpringName 과 같은 문자열) → 스프링
  static const Map<String, SpringDescription> byName = {
${springNames.map((n) => `    ${dartStr(n)}: ${n},`).join('\n')}
  };
}

/// 모션 토큰 (cameo). *Ms → Duration, *Role → Color, 스프링 참조 → SpringDescription.
abstract final class CameoMotion {
${[...motionFields, ...easingFields].map(([, line]) => `  ${line}`).join('\n')}
}
`;

// ---------- write / check ----------
let stale = false;
for (const [file, source] of [
  ...(process.argv.includes('--rn') ? [[OUT_TS, ts]] : []),
  [OUT_DART, dart],
]) {
  const content = generatedComments(source);
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (CHECK) {
    if (current !== content) {
      console.error(`✗ stale: ${file}`);
      stale = true;
    } else console.log(`✓ up to date: ${file}`);
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`wrote ${file}`);
}
if (stale) {
  console.error('토큰 생성물이 tokens.json 과 다릅니다. `npm run tokens` 를 실행하세요.');
  process.exit(1);
}
