#!/usr/bin/env node
// Normalize bundled Tabler icons and generate their typed Flutter names. The token manifest defines the icon set and stroke width; --rn enables reference output.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generatedComments } from './generated-comments.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const tokens = JSON.parse(readFileSync(resolve(root, 'design-system/tokens.json'), 'utf8'));
const CHECK = process.argv.includes('--check');
const HEADER = 'GENERATED by design-system/scripts/sync-icons.mjs from design-system/tokens.json — DO NOT EDIT';

const SRC = resolve(root, 'node_modules/@tabler/icons/icons');
const DS_SVG = resolve(root, 'design-system/icons/svg');
const OUT_TS = resolve(root, 'apps/rn/src/design-system/icons.generated.ts');
const FLUTTER_ASSETS = resolve(root, 'apps/flutter/assets/icons');
const OUT_DART = resolve(root, 'apps/flutter/lib/design_system/icons.g.dart');

const expectedPkg = tokens.icon.sourcePackage.$value; // "@tabler/icons@x.y.z"
const strokeWidth = tokens.icon.strokeWidth.$value;
const used = tokens.icon.used;
const cameoAdditions = new Set(used.$cameoAdditions ?? []);

if (!existsSync(SRC)) {
  console.error('node_modules/@tabler/icons 가 없습니다. 루트에서 `npm install` 을 먼저 실행하세요.');
  process.exit(1);
}
const installed = JSON.parse(readFileSync(resolve(root, 'node_modules/@tabler/icons/package.json'), 'utf8')).version;
if (`@tabler/icons@${installed}` !== expectedPkg) {
  console.error(`@tabler/icons 버전 불일치: 설치됨 ${installed}, tokens.json 은 ${expectedPkg}`);
  process.exit(1);
}

function normalize(svg, variant) {
  let s = svg
    .replace(/\s+class="[^"]*"/g, '')
    .replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*\/>/g, '')
    .replace(/\s*\n\s*/g, ' ')
    .replace(/>\s+</g, '><')
    .replace(/\s+\/>/g, '/>')
    .trim();
  if (variant === 'outline') s = s.replace(/stroke-width="[^"]*"/, `stroke-width="${strokeWidth}"`);
  return s + '\n';
}

const pascal = (slug) => slug.split('-').map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
const camel = (slug) => {
  const p = pascal(slug);
  return p.charAt(0).toLowerCase() + p.slice(1);
};

const entries = [];
for (const add of cameoAdditions) {
  const [variant, slug] = add.split('/');
  if (!(used[variant] ?? []).includes(slug)) {
    console.error(`icon.used.$cameoAdditions '${add}' 가 icon.used.${variant} 목록에 없습니다.`);
    process.exit(1);
  }
}
for (const variant of ['outline', 'filled']) {
  const list = used[variant] ?? [];
  const dup = list.find((slug, i) => list.indexOf(slug) !== i);
  if (dup) {
    console.error(`icon.used.${variant} 에 중복: ${dup}`);
    process.exit(1);
  }
  for (const slug of list) {
    const file = join(SRC, variant, `${slug}.svg`);
    if (!existsSync(file)) {
      console.error(`아이콘 없음: ${variant}/${slug} (@tabler/icons ${installed})`);
      process.exit(1);
    }
    const key = variant === 'filled' ? `${slug}-filled` : slug;
    const provenance = cameoAdditions.has(`${variant}/${slug}`) ? 'cameo' : 'figma';
    entries.push({ slug, variant, key, provenance, svg: normalize(readFileSync(file, 'utf8'), variant) });
  }
}
entries.sort((a, b) => a.key.localeCompare(b.key));

// ---------- outputs ----------
const outputs = new Map();
for (const e of entries) {
  outputs.set(join(DS_SVG, e.variant, `${e.slug}.svg`), e.svg);
  outputs.set(join(FLUTTER_ASSETS, e.variant, `${e.slug}.svg`), e.svg);
}
outputs.set(
  resolve(root, 'design-system/icons/manifest.json'),
  JSON.stringify(
    {
      $generated: HEADER,
      source: `@tabler/icons@${installed}`,
      license: 'MIT',
      strokeWidth,
      icons: entries.map(({ key, slug, variant, provenance }) => ({
        key,
        slug,
        variant,
        provenance,
        file: `svg/${variant}/${slug}.svg`,
      })),
    },
    null,
    2,
  ) + '\n',
);

if (process.argv.includes('--rn')) outputs.set(
  OUT_TS,
  `// ${HEADER}
// Tabler Icons (MIT) — stroke-width ${strokeWidth}, viewBox 24. currentColor 로 색 지정.
export const iconXml = {
${entries.map((e) => `  '${e.key}': ${JSON.stringify(e.svg.trim())},`).join('\n')}
} as const;
export type IconName = keyof typeof iconXml;
/** Figma 에 없는 cameo 추가 아이콘 (tokens.json icon.used.$cameoAdditions) */
export const cameoIcons: readonly IconName[] = [${entries
    .filter((e) => e.provenance === 'cameo')
    .map((e) => `'${e.key}'`)
    .join(', ')}];
`,
);

outputs.set(
  OUT_DART,
  `// ${HEADER}
// dart format off
// Tabler Icons (MIT) — stroke-width ${strokeWidth}, viewBox 24. currentColor 로 색 지정.
enum CameoIconName {
${entries
  .map((e) => `  ${camel(e.key)}('${e.key}', 'assets/icons/${e.variant}/${e.slug}.svg', cameo: ${e.provenance === 'cameo'}),`)
  .join('\n')}
  ;

  const CameoIconName(this.key, this.asset, {required this.cameo});

  /// RN IconName 과 동일한 키 (filled 변형은 '-filled' 접미사)
  final String key;
  final String asset;

  /// Figma 에 없는 cameo 추가 아이콘 (tokens.json icon.used.$cameoAdditions)
  final bool cameo;
}
`,
);

const stray = [];
for (const dir of [DS_SVG, FLUTTER_ASSETS]) {
  for (const variant of ['outline', 'filled']) {
    const d = join(dir, variant);
    if (!existsSync(d)) continue;
    for (const f of readdirSync(d)) {
      if (f.startsWith('._')) continue;
      const p = join(d, f);
      if (!outputs.has(p)) stray.push(p);
    }
  }
}

let stale = false;
for (const [file, source] of outputs) {
  const content = file.endsWith('.dart') ? generatedComments(source) : source;
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (CHECK) {
    if (current !== content) {
      console.error(`✗ stale: ${file}`);
      stale = true;
    }
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  if (current !== content) writeFileSync(file, content);
}
for (const p of stray) {
  if (CHECK) {
    console.error(`✗ stray: ${p}`);
    stale = true;
  } else rmSync(p);
}
if (CHECK) {
  if (stale) {
    console.error('아이콘 생성물이 tokens.json 과 다릅니다. `npm run icons` 를 실행하세요.');
    process.exit(1);
  }
  console.log(`✓ icons up to date (${entries.length})`);
} else {
  console.log(`synced ${entries.length} icons → design-system/icons, RN, Flutter`);
}
