// GENERATED by design-system/scripts/build-content.mjs from design-system/content/lab-content.json + manifest.json — DO NOT EDIT
// dart format off
// ignore_for_file: lines_longer_than_80_chars, constant_identifier_names

import 'package:flutter/widgets.dart';
import 'content_locale.dart';

abstract final class LabImages {
  static const String album3Cover = 'assets/content/album-3-cover.jpg';
  static const String album3GridR1c2 = 'assets/content/album-3-grid-r1c2.jpg';
  static const String albumSungsuCover = 'assets/content/album-sungsu-cover.jpg';
  static const String albumSungsuGridR1c1Hires = 'assets/content/album-sungsu-grid-r1c1-hires.jpg';
  static const String albumSungsuGridR1c1 = 'assets/content/album-sungsu-grid-r1c1.jpg';
  static const String albumSungsuGridR1c2 = 'assets/content/album-sungsu-grid-r1c2.jpg';
  static const String albumSungsuGridR1c3 = 'assets/content/album-sungsu-grid-r1c3.jpg';
  static const String albumSungsuGridR1c4 = 'assets/content/album-sungsu-grid-r1c4.jpg';
  static const String albumSungsuGridR1c5 = 'assets/content/album-sungsu-grid-r1c5.jpg';
  static const String albumSungsuGridR2c1 = 'assets/content/album-sungsu-grid-r2c1.jpg';
  static const String albumSungsuGridR2c2 = 'assets/content/album-sungsu-grid-r2c2.jpg';
  static const String albumSungsuGridR2c3 = 'assets/content/album-sungsu-grid-r2c3.jpg';
  static const String albumSungsuGridR2c4 = 'assets/content/album-sungsu-grid-r2c4.jpg';
  static const String albumSungsuGridR2c5 = 'assets/content/album-sungsu-grid-r2c5.jpg';
  static const String albumSungsuGridR3c1 = 'assets/content/album-sungsu-grid-r3c1.jpg';
  static const String albumSungsuGridR3c2Hires = 'assets/content/album-sungsu-grid-r3c2-hires.jpg';
  static const String albumSungsuGridR3c2 = 'assets/content/album-sungsu-grid-r3c2.jpg';
  static const String albumSungsuGridR3c3 = 'assets/content/album-sungsu-grid-r3c3.jpg';
  static const String albumSungsuGridR3c4 = 'assets/content/album-sungsu-grid-r3c4.jpg';
  static const String albumSungsuGridR3c5 = 'assets/content/album-sungsu-grid-r3c5.jpg';
  static const String albumSungsuGridR4c1 = 'assets/content/album-sungsu-grid-r4c1.jpg';
  static const String albumSungsuGridR4c2 = 'assets/content/album-sungsu-grid-r4c2.jpg';
  static const String albumSungsuGridR4c3 = 'assets/content/album-sungsu-grid-r4c3.jpg';
  static const String albumSungsuGridR4c4 = 'assets/content/album-sungsu-grid-r4c4.jpg';
  static const String albumSungsuGridR4c5 = 'assets/content/album-sungsu-grid-r4c5.jpg';
  static const String albumSungsuGridR5c1 = 'assets/content/album-sungsu-grid-r5c1.jpg';
  static const String albumSungsuGridR5c2 = 'assets/content/album-sungsu-grid-r5c2.jpg';
  static const String albumSungsuGridR5c3 = 'assets/content/album-sungsu-grid-r5c3.jpg';
  static const String albumSungsuGridR5c4Hires = 'assets/content/album-sungsu-grid-r5c4-hires.jpg';
  static const String albumSungsuGridR5c4 = 'assets/content/album-sungsu-grid-r5c4.jpg';
  static const String albumSungsuGridR5c5 = 'assets/content/album-sungsu-grid-r5c5.jpg';
  static const String albumSungsuGridR6c1 = 'assets/content/album-sungsu-grid-r6c1.jpg';
  static const String albumSungsuGridR6c2 = 'assets/content/album-sungsu-grid-r6c2.jpg';
  static const String albumSungsuGridR6c3 = 'assets/content/album-sungsu-grid-r6c3.jpg';
  static const String albumSungsuGridR6c4 = 'assets/content/album-sungsu-grid-r6c4.jpg';
  static const String albumSungsuGridR6c5 = 'assets/content/album-sungsu-grid-r6c5.jpg';
  static const String callBackground = 'assets/content/call-background.jpg';
  static const String cameraPlaceholder = 'assets/content/camera-placeholder.jpg';
  static const String cameraViewfinderV5 = 'assets/content/camera-viewfinder-v5.jpg';
  static const String photoSheetLiveCamera = 'assets/content/photo-sheet-live-camera.png';
  static const String tabbarAvatar = 'assets/content/tabbar-avatar.png';
  static const String transcriptDarkBackground = 'assets/content/transcript-dark-background.jpg';
  static const String transcriptInlinePhoto = 'assets/content/transcript-inline-photo.jpg';
  static const String welcomeCouple01Cafe = 'assets/content/welcome-couple-01-cafe.jpg';
  static const String welcomeCouple02Coast = 'assets/content/welcome-couple-02-coast.jpg';
  static const String welcomeCouple03Spring = 'assets/content/welcome-couple-03-spring.jpg';
  static const String welcomeCouple04Kitchen = 'assets/content/welcome-couple-04-kitchen.jpg';
  static const String welcomeCouple05Picnic = 'assets/content/welcome-couple-05-picnic.jpg';
  static const String welcomeCouple06Rain = 'assets/content/welcome-couple-06-rain.jpg';
  static const String welcomeCouple07Autumn = 'assets/content/welcome-couple-07-autumn.jpg';
  static const String welcomeCouple08Snow = 'assets/content/welcome-couple-08-snow.jpg';
  static const String welcomeCouple09PlayfulPortrait = 'assets/content/welcome-couple-09-playful-portrait.jpg';
  static const String welcomeCouple10Train = 'assets/content/welcome-couple-10-train.jpg';
  static const String welcomeCouple11Rooftop = 'assets/content/welcome-couple-11-rooftop.jpg';
  static const String welcomeCouple12Bookstore = 'assets/content/welcome-couple-12-bookstore.jpg';
  static const String welcomeCouple13Riverside = 'assets/content/welcome-couple-13-riverside.jpg';
  static const String welcomeCouple14FlowerMarket = 'assets/content/welcome-couple-14-flower-market.jpg';
  static const String welcomeCouple15SummerBeach = 'assets/content/welcome-couple-15-summer-beach.jpg';
  static const String welcomeCouple16Hike = 'assets/content/welcome-couple-16-hike.jpg';
  static const String welcomeCouple17HomeSofa = 'assets/content/welcome-couple-17-home-sofa.jpg';
  static const String welcomeCouple18EveningDate = 'assets/content/welcome-couple-18-evening-date.jpg';

  static const List<String> all = <String>[
    album3Cover,
    album3GridR1c2,
    albumSungsuCover,
    albumSungsuGridR1c1Hires,
    albumSungsuGridR1c1,
    albumSungsuGridR1c2,
    albumSungsuGridR1c3,
    albumSungsuGridR1c4,
    albumSungsuGridR1c5,
    albumSungsuGridR2c1,
    albumSungsuGridR2c2,
    albumSungsuGridR2c3,
    albumSungsuGridR2c4,
    albumSungsuGridR2c5,
    albumSungsuGridR3c1,
    albumSungsuGridR3c2Hires,
    albumSungsuGridR3c2,
    albumSungsuGridR3c3,
    albumSungsuGridR3c4,
    albumSungsuGridR3c5,
    albumSungsuGridR4c1,
    albumSungsuGridR4c2,
    albumSungsuGridR4c3,
    albumSungsuGridR4c4,
    albumSungsuGridR4c5,
    albumSungsuGridR5c1,
    albumSungsuGridR5c2,
    albumSungsuGridR5c3,
    albumSungsuGridR5c4Hires,
    albumSungsuGridR5c4,
    albumSungsuGridR5c5,
    albumSungsuGridR6c1,
    albumSungsuGridR6c2,
    albumSungsuGridR6c3,
    albumSungsuGridR6c4,
    albumSungsuGridR6c5,
    callBackground,
    cameraPlaceholder,
    cameraViewfinderV5,
    photoSheetLiveCamera,
    tabbarAvatar,
    transcriptDarkBackground,
    transcriptInlinePhoto,
    welcomeCouple01Cafe,
    welcomeCouple02Coast,
    welcomeCouple03Spring,
    welcomeCouple04Kitchen,
    welcomeCouple05Picnic,
    welcomeCouple06Rain,
    welcomeCouple07Autumn,
    welcomeCouple08Snow,
    welcomeCouple09PlayfulPortrait,
    welcomeCouple10Train,
    welcomeCouple11Rooftop,
    welcomeCouple12Bookstore,
    welcomeCouple13Riverside,
    welcomeCouple14FlowerMarket,
    welcomeCouple15SummerBeach,
    welcomeCouple16Hike,
    welcomeCouple17HomeSofa,
    welcomeCouple18EveningDate,
  ];

  static const Map<String, LabImageSize> sizes = <String, LabImageSize>{
    album3Cover: LabImageSize(1024, 768),
    album3GridR1c2: LabImageSize(768, 1024),
    albumSungsuCover: LabImageSize(1179, 1572),
    albumSungsuGridR1c1Hires: LabImageSize(1179, 1570),
    albumSungsuGridR1c1: LabImageSize(481, 640),
    albumSungsuGridR1c2: LabImageSize(480, 640),
    albumSungsuGridR1c3: LabImageSize(481, 640),
    albumSungsuGridR1c4: LabImageSize(640, 481),
    albumSungsuGridR1c5: LabImageSize(480, 640),
    albumSungsuGridR2c1: LabImageSize(480, 640),
    albumSungsuGridR2c2: LabImageSize(640, 480),
    albumSungsuGridR2c3: LabImageSize(480, 640),
    albumSungsuGridR2c4: LabImageSize(480, 640),
    albumSungsuGridR2c5: LabImageSize(640, 480),
    albumSungsuGridR3c1: LabImageSize(480, 640),
    albumSungsuGridR3c2Hires: LabImageSize(1179, 1572),
    albumSungsuGridR3c2: LabImageSize(480, 640),
    albumSungsuGridR3c3: LabImageSize(480, 640),
    albumSungsuGridR3c4: LabImageSize(480, 640),
    albumSungsuGridR3c5: LabImageSize(480, 640),
    albumSungsuGridR4c1: LabImageSize(480, 640),
    albumSungsuGridR4c2: LabImageSize(480, 640),
    albumSungsuGridR4c3: LabImageSize(215, 640),
    albumSungsuGridR4c4: LabImageSize(640, 480),
    albumSungsuGridR4c5: LabImageSize(640, 480),
    albumSungsuGridR5c1: LabImageSize(480, 640),
    albumSungsuGridR5c2: LabImageSize(480, 640),
    albumSungsuGridR5c3: LabImageSize(480, 640),
    albumSungsuGridR5c4Hires: LabImageSize(1536, 2048),
    albumSungsuGridR5c4: LabImageSize(480, 640),
    albumSungsuGridR5c5: LabImageSize(480, 640),
    albumSungsuGridR6c1: LabImageSize(480, 640),
    albumSungsuGridR6c2: LabImageSize(480, 640),
    albumSungsuGridR6c3: LabImageSize(480, 640),
    albumSungsuGridR6c4: LabImageSize(1179, 1572),
    albumSungsuGridR6c5: LabImageSize(1179, 884),
    callBackground: LabImageSize(1917, 2556),
    cameraPlaceholder: LabImageSize(768, 1024),
    cameraViewfinderV5: LabImageSize(1536, 2048),
    photoSheetLiveCamera: LabImageSize(770, 1369),
    tabbarAvatar: LabImageSize(304, 302),
    transcriptDarkBackground: LabImageSize(786, 1704),
    transcriptInlinePhoto: LabImageSize(1179, 780),
    welcomeCouple01Cafe: LabImageSize(512, 512),
    welcomeCouple02Coast: LabImageSize(512, 512),
    welcomeCouple03Spring: LabImageSize(512, 512),
    welcomeCouple04Kitchen: LabImageSize(512, 512),
    welcomeCouple05Picnic: LabImageSize(512, 512),
    welcomeCouple06Rain: LabImageSize(512, 512),
    welcomeCouple07Autumn: LabImageSize(512, 512),
    welcomeCouple08Snow: LabImageSize(512, 512),
    welcomeCouple09PlayfulPortrait: LabImageSize(512, 512),
    welcomeCouple10Train: LabImageSize(512, 512),
    welcomeCouple11Rooftop: LabImageSize(512, 512),
    welcomeCouple12Bookstore: LabImageSize(512, 512),
    welcomeCouple13Riverside: LabImageSize(512, 512),
    welcomeCouple14FlowerMarket: LabImageSize(512, 512),
    welcomeCouple15SummerBeach: LabImageSize(512, 512),
    welcomeCouple16Hike: LabImageSize(512, 512),
    welcomeCouple17HomeSofa: LabImageSize(512, 512),
    welcomeCouple18EveningDate: LabImageSize(512, 512),
  };
}

class LabImageSize {
  const LabImageSize(this.width, this.height);
  final int width;
  final int height;
}

enum LabTone { dark, light }

enum LabTextWeight { regular, medium }

enum LabAlign { left, right }

enum CallDirection { outgoing, incoming, missed }

class LabTextSpan {
  const LabTextSpan(this.text, this.weight);
  final String text;
  final LabTextWeight weight;
}

class GradientTextContent {
  const GradientTextContent({required this.solidUntil});
  final double solidUntil;
}

class LabNodeIds {
  const LabNodeIds({required this.light, required this.dark});
  final String light;
  final String dark;
}

class CallCardContent {
  const CallCardContent({required this.nodeId, required this.direction, required this.icon, required this.title, required this.subtitle});
  final String nodeId;
  final CallDirection direction;
  final String icon;
  final String title;
  final List<LabTextSpan> subtitle;
}

class AlbumStatsContent {
  const AlbumStatsContent({required this.photos, required this.calls});
  final String photos;
  final String calls;
}

class GridPhotoContent {
  const GridPhotoContent({required this.image, required this.liked});
  final String image;
  final bool liked;
}

class PhotoGridContent {
  const PhotoGridContent({required this.columns, required this.rows, required this.photos});
  final int columns;
  final List<List<String>> rows;
  final List<GridPhotoContent> photos;
}

class AlbumSectionContent {
  const AlbumSectionContent({required this.id, required this.figmaName, required this.nodeId, required this.tone, required this.cover, required this.title, required this.subtitle, required this.stats, required this.callCards, required this.grid});
  final String id;
  final String figmaName;
  final String nodeId;
  final LabTone tone;
  final String? cover;
  final String title;
  final String subtitle;
  final AlbumStatsContent stats;
  final List<CallCardContent> callCards;
  final PhotoGridContent? grid;
}

class AlbumDayContent {
  const AlbumDayContent({required this.screenNodeId, required this.sections});
  final String screenNodeId;
  final List<AlbumSectionContent> sections;
}

class FeaturedTileContent {
  const FeaturedTileContent({required this.nodeId, required this.image, required this.row, required this.col, required this.rowSpan, required this.colSpan, required this.liked});
  final String nodeId;
  final String image;
  final int row;
  final int col;
  final int rowSpan;
  final int colSpan;
  final bool liked;
}

class QuoteLineContent {
  const QuoteLineContent({required this.nodeId, required this.text, required this.align, required this.gradient});
  final String nodeId;
  final String text;
  final LabAlign align;
  final GradientTextContent? gradient;
}

class QuoteCardContent {
  const QuoteCardContent({required this.nodeId, required this.label, required this.labelAlign, required this.lines});
  final String nodeId;
  final String label;
  final LabAlign labelAlign;
  final List<QuoteLineContent> lines;
}

class TabBarContent {
  const TabBarContent({required this.nodeId, required this.selectedIndex, required this.avatar});
  final String nodeId;
  final int selectedIndex;
  final String avatar;
}

class AlbumGangneungContent {
  const AlbumGangneungContent({required this.screenNodeId, required this.title, required this.date, required this.cover, required this.grid, required this.featured, required this.quoteCard, required this.tabBar});
  final String screenNodeId;
  final String title;
  final String date;
  final String cover;
  final PhotoGridContent grid;
  final List<FeaturedTileContent> featured;
  final QuoteCardContent quoteCard;
  final TabBarContent tabBar;
}

class TranscriptLineContent {
  const TranscriptLineContent({required this.id, required this.nodeIds, required this.text, required this.side, required this.inHighlight, required this.current, required this.gradient});
  final String id;
  final LabNodeIds nodeIds;
  final String text;
  final LabAlign side;
  final bool inHighlight;
  final bool current;
  final GradientTextContent? gradient;
}

class PlayerMarkerContent {
  const PlayerMarkerContent({required this.nodeIds, required this.leftPx, required this.widthPx, required this.start, required this.width});
  final LabNodeIds nodeIds;
  final double leftPx;
  final double widthPx;
  final double start;
  final double width;
}

class PlayerContent {
  const PlayerContent({required this.nodeIds, required this.currentTime, required this.duration, required this.durationSeconds, required this.playing, required this.trackWidthPx, required this.trackWidthPxDark, required this.progressWidthPx, required this.progress, required this.thumbLeftPx, required this.thumbSizePx, required this.thumbCenterPx, required this.thumbCenter, required this.markers});
  final LabNodeIds nodeIds;
  final String currentTime;
  final String duration;
  final int durationSeconds;
  final bool playing;
  final double trackWidthPx;
  final double trackWidthPxDark;
  final double progressWidthPx;
  final double progress;
  final double thumbLeftPx;
  final double thumbSizePx;
  final double thumbCenterPx;
  final double thumbCenter;
  final List<PlayerMarkerContent> markers;
}

class TranscriptContent {
  const TranscriptContent({required this.screenNodeIds, required this.title, required this.date, required this.darkBackground, required this.lines, required this.player});
  final LabNodeIds screenNodeIds;
  final String title;
  final String date;
  final String darkBackground;
  final List<TranscriptLineContent> lines;
  final PlayerContent player;
}

class ToastContent {
  const ToastContent({required this.screenNodeId, required this.nodeId, required this.text, required this.icon, required this.iconIsPlaceholder});
  final String screenNodeId;
  final String nodeId;
  final String text;
  final String icon;
  final bool iconIsPlaceholder;
}

class InCallToastsContent {
  const InCallToastsContent({required this.systemMessage, required this.sleepModeRequest});
  final ToastContent systemMessage;
  final ToastContent sleepModeRequest;
}

class InCallContent {
  const InCallContent({required this.screenNodeIds, required this.name, required this.timer, required this.background, required this.toasts});
  final List<String> screenNodeIds;
  final String name;
  final String timer;
  final String background;
  final InCallToastsContent toasts;
}

class PhotoBoothSampleContent {
  const PhotoBoothSampleContent({required this.nodeId, required this.image});
  final String nodeId;
  final String image;
}

enum CameraModeId { photo, video }

class CameraModeContent {
  const CameraModeContent({required this.id, required this.nodeId, required this.labelNodeId, required this.label});
  final CameraModeId id;
  final String nodeId;
  final String labelNodeId;
  final String label;
}

class CameraContent {
  const CameraContent({required this.screenNodeId, required this.placeholderNodeId, required this.placeholder, required this.initialMode, required this.modes});
  final String screenNodeId;
  final String placeholderNodeId;
  final String placeholder;
  final CameraModeId initialMode;
  final List<CameraModeContent> modes;
}

// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------

enum AlbumSectionKind { photosCalls, callsOnly, photosOnly }

/// portrait = 3:4 (Figma 2170:8313) · landscape = 4:3 (cameo E10)
enum CapturedOrientation { portrait, landscape }

class SheetLiveCellContent {
  const SheetLiveCellContent({required this.nodeId, required this.image, required this.row, required this.col, required this.rowSpan});
  final String nodeId;
  final String image;
  final int row;
  final int col;
  final int rowSpan;
}

class SheetPhotoContent {
  const SheetPhotoContent({required this.image, required this.selected});
  final String image;
  final bool selected;
}

class PhotoSheetContent {
  const PhotoSheetContent({required this.screenNodeId, required this.nodeId, required this.title, required this.liveCell, required this.columns, required this.rows, required this.photos});
  final String screenNodeId;
  final String nodeId;
  final String title;
  final SheetLiveCellContent liveCell;
  final int columns;
  final List<List<String>> rows;
  final List<SheetPhotoContent> photos;
}

class CapturedCardContent {
  const CapturedCardContent({required this.nodeId, required this.image, required this.orientation});
  final String nodeId;
  final String image;
  final CapturedOrientation orientation;
}

class InCallV5ToastsContent {
  const InCallV5ToastsContent({required this.sleep, required this.highlight});
  final ToastContent sleep;
  final ToastContent highlight;
}

class InCallV5Content {
  const InCallV5Content({required this.screenNodeIds, required this.name, required this.timer, required this.background, required this.toasts, required this.photoSheet, required this.capturedCard});
  final List<String> screenNodeIds;
  final String name;
  final String timer;
  final String background;
  final InCallV5ToastsContent toasts;
  final PhotoSheetContent photoSheet;
  final CapturedCardContent capturedCard;
}

class CameraV5Content {
  const CameraV5Content({required this.screenNodeId, required this.viewfinderNodeId, required this.viewfinder, required this.thumbnailNodeId, required this.thumbnail, required this.toast});
  final String screenNodeId;
  final String viewfinderNodeId;
  final String viewfinder;
  final String thumbnailNodeId;
  final String thumbnail;
  final ToastContent toast;
}

class ViewerContent {
  const ViewerContent({required this.screenNodeId, required this.cardNodeId, required this.image, required this.date, required this.actions});
  final String screenNodeId;
  final String cardNodeId;
  final String image;
  final String date;
  final List<String> actions;
}

class ViewerV5Content {
  const ViewerV5Content({required this.photo, required this.instant});
  final ViewerContent photo;
  final ViewerContent instant;
}

class TabBarV5Content {
  const TabBarV5Content({required this.nodeId, required this.avatar});
  final String nodeId;
  final String avatar;
}

class CallCardV5Content {
  const CallCardV5Content({required this.nodeId, required this.variant, required this.direction, required this.icon, required this.title, required this.subtitle});
  final String nodeId;
  final String variant;
  final CallDirection direction;
  final String icon;
  final String title;
  final List<LabTextSpan> subtitle;
}

class AlbumV5SectionContent {
  const AlbumV5SectionContent({required this.id, required this.figmaName, required this.nodeId, required this.kind, required this.tint, required this.heroGradient, required this.cover, required this.title, required this.subtitle, required this.stats, required this.callCards, required this.grid, required this.featured});
  final String id;
  final String figmaName;
  final String nodeId;
  final AlbumSectionKind kind;
  final String tint;
  final String? heroGradient;
  final String? cover;
  final String title;
  final String subtitle;
  final AlbumStatsContent stats;
  final List<CallCardV5Content> callCards;
  final PhotoGridContent? grid;
  final List<FeaturedTileContent> featured;
}

class AlbumV5NavContent {
  const AlbumV5NavContent({required this.selectLabel, required this.actions});
  final String selectLabel;
  final List<String> actions;
}

class AlbumV5SelectNavContent {
  const AlbumV5SelectNavContent({required this.actions});
  final List<String> actions;
}

class AlbumV5Content {
  const AlbumV5Content({required this.screenNodeId, required this.contentNodeId, required this.nav, required this.selectNav, required this.sections});
  final String screenNodeId;
  final String contentNodeId;
  final AlbumV5NavContent nav;
  final AlbumV5SelectNavContent selectNav;
  final List<AlbumV5SectionContent> sections;
}

class SettingsActionContent {
  const SettingsActionContent({required this.nodeId, required this.label, required this.icon});
  final String nodeId;
  final String label;
  final String icon;
}

class SettingsV5Content {
  const SettingsV5Content({required this.screenNodeId, required this.hero, required this.names, required this.days, required this.dayCount, required this.daySuffix, required this.editProfile, required this.disconnect});
  final String screenNodeId;
  final String hero;
  final String names;
  final int days;
  final String dayCount;
  final String daySuffix;
  final SettingsActionContent editProfile;
  final SettingsActionContent disconnect;
}

class TranscriptV5LineContent {
  const TranscriptV5LineContent({required this.id, required this.nodeId, required this.text, required this.side, required this.inHighlight, required this.current});
  final String id;
  final String nodeId;
  final String text;
  final LabAlign side;
  final bool inHighlight;
  final bool current;
}

class InlinePhotoContent {
  const InlinePhotoContent({required this.nodeId, required this.image, required this.afterLineId});
  final String nodeId;
  final String image;
  final String afterLineId;
}

class PlayerV5MarkerContent {
  const PlayerV5MarkerContent({required this.nodeId, required this.leftPx, required this.widthPx, required this.start, required this.width});
  final String nodeId;
  final double leftPx;
  final double widthPx;
  final double start;
  final double width;
}

class PlayerV5Content {
  const PlayerV5Content({required this.nodeId, required this.currentTime, required this.duration, required this.durationSeconds, required this.playing, required this.trackWidthPx, required this.progressWidthPx, required this.progress, required this.thumbLeftPx, required this.thumbSizePx, required this.thumbCenterPx, required this.thumbCenter, required this.markers});
  final String nodeId;
  final String currentTime;
  final String duration;
  final int durationSeconds;
  final bool playing;
  final double trackWidthPx;
  final double progressWidthPx;
  final double progress;
  final double thumbLeftPx;
  final double thumbSizePx;
  final double thumbCenterPx;
  final double thumbCenter;
  final List<PlayerV5MarkerContent> markers;
}

class TranscriptV5Content {
  const TranscriptV5Content({required this.screenNodeId, required this.variantNodeIds, required this.title, required this.date, required this.navActions, required this.lines, required this.inlinePhoto, required this.player});
  final String screenNodeId;
  final List<String> variantNodeIds;
  final String title;
  final String date;
  final List<String> navActions;
  final List<TranscriptV5LineContent> lines;
  final InlinePhotoContent inlinePhoto;
  final PlayerV5Content player;
}

/// iPhone 16 - 6 (album)
const AlbumDayContent labAlbumDay = AlbumDayContent(
  screenNodeId: '2028:435',
  sections: <AlbumSectionContent>[
    AlbumSectionContent(
      id: 'sungsu',
      figmaName: '1',
      nodeId: '2042:2791',
      tone: LabTone.dark,
      cover: LabImages.albumSungsuCover,
      title: '성수 → 한남',
      subtitle: '2026년 8월 20일, 6시간',
      stats: AlbumStatsContent(photos: '30', calls: '3'),
      callCards: <CallCardContent>[
        CallCardContent(
          nodeId: '2042:2804',
          direction: CallDirection.outgoing,
          icon: 'arrow-up-right',
          title: '성수 데이트 코스에 대한 대화',
          subtitle: <LabTextSpan>[
            LabTextSpan('12시 20분', LabTextWeight.medium),
            LabTextSpan(' ∙ 발신 통화 21분 17초', LabTextWeight.regular),
          ],
        ),
        CallCardContent(
          nodeId: '2042:2809',
          direction: CallDirection.incoming,
          icon: 'arrow-down-left',
          title: '아침 인사',
          subtitle: <LabTextSpan>[
            LabTextSpan('8시 12분', LabTextWeight.medium),
            LabTextSpan(' ∙ 수신 통화 5분 10초', LabTextWeight.regular),
          ],
        ),
        CallCardContent(
          nodeId: '2042:2814',
          direction: CallDirection.missed,
          icon: 'arrow-down-left',
          title: '이주영 빨리 일어나..!!',
          subtitle: <LabTextSpan>[
            LabTextSpan('8시 10분', LabTextWeight.medium),
            LabTextSpan(' ∙ 부재중', LabTextWeight.regular),
          ],
        ),
      ],
      grid: PhotoGridContent(
        columns: 5,
        rows: <List<String>>[
          <String>[LabImages.albumSungsuGridR1c1, LabImages.albumSungsuGridR1c2, LabImages.albumSungsuGridR1c3, LabImages.albumSungsuGridR1c4, LabImages.albumSungsuGridR1c5],
          <String>[LabImages.albumSungsuGridR2c1, LabImages.albumSungsuGridR2c2, LabImages.albumSungsuGridR2c3, LabImages.albumSungsuGridR2c4, LabImages.albumSungsuGridR2c5],
          <String>[LabImages.albumSungsuGridR3c1, LabImages.albumSungsuGridR3c2, LabImages.albumSungsuGridR3c3, LabImages.albumSungsuGridR3c4, LabImages.albumSungsuGridR3c5],
          <String>[LabImages.albumSungsuGridR4c1, LabImages.albumSungsuGridR4c2, LabImages.albumSungsuGridR4c3, LabImages.albumSungsuGridR4c4, LabImages.albumSungsuGridR4c5],
          <String>[LabImages.albumSungsuGridR5c1, LabImages.albumSungsuGridR5c2, LabImages.albumSungsuGridR5c3, LabImages.albumSungsuGridR5c4, LabImages.albumSungsuGridR5c5],
          <String>[LabImages.albumSungsuGridR6c1, LabImages.albumSungsuGridR6c2, LabImages.albumSungsuGridR6c3, LabImages.albumSungsuGridR6c4, LabImages.albumSungsuGridR6c5],
        ],
        photos: <GridPhotoContent>[
          GridPhotoContent(image: LabImages.albumSungsuGridR1c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c5, liked: false),
        ],
      ),
    ),
    AlbumSectionContent(
      id: 'empty-photo',
      figmaName: 'empty photo',
      nodeId: '2042:2856',
      tone: LabTone.light,
      cover: null,
      title: '2026년 8월 20일',
      subtitle: '전체 통화 요약',
      stats: AlbumStatsContent(photos: '0', calls: '2'),
      callCards: <CallCardContent>[
        CallCardContent(
          nodeId: '2042:2869',
          direction: CallDirection.outgoing,
          icon: 'arrow-up-right',
          title: '자긴 전 대화',
          subtitle: <LabTextSpan>[
            LabTextSpan('23시 10분', LabTextWeight.medium),
            LabTextSpan(' ∙ 발신 통화 21분 17초', LabTextWeight.regular),
          ],
        ),
        CallCardContent(
          nodeId: '2042:2874',
          direction: CallDirection.incoming,
          icon: 'arrow-down-left',
          title: '아침 인사',
          subtitle: <LabTextSpan>[
            LabTextSpan('08시 00분', LabTextWeight.medium),
            LabTextSpan(' ∙ 수신 통화 5분 10초', LabTextWeight.regular),
          ],
        ),
      ],
      grid: null,
    ),
    AlbumSectionContent(
      id: 'section-3',
      figmaName: '2',
      nodeId: '2042:2879',
      tone: LabTone.dark,
      cover: LabImages.album3Cover,
      title: '2026년 8월 20일',
      subtitle: '전체 사진 요약',
      stats: AlbumStatsContent(photos: '2', calls: '0'),
      callCards: <CallCardContent>[],
      grid: PhotoGridContent(
        columns: 5,
        rows: <List<String>>[
          <String>[LabImages.album3Cover, LabImages.album3GridR1c2],
        ],
        photos: <GridPhotoContent>[
          GridPhotoContent(image: LabImages.album3Cover, liked: false),
          GridPhotoContent(image: LabImages.album3GridR1c2, liked: false),
        ],
      ),
    ),
  ],
);

const AlbumGangneungContent labAlbumGangneung = AlbumGangneungContent(
  screenNodeId: '2001:1126',
  title: '강릉',
  date: '2026년 8월 20일',
  cover: LabImages.albumSungsuCover,
  grid: PhotoGridContent(
    columns: 5,
    rows: <List<String>>[
      <String>[LabImages.albumSungsuGridR1c1, LabImages.albumSungsuGridR1c2, LabImages.albumSungsuGridR1c3, LabImages.albumSungsuGridR1c4, LabImages.albumSungsuGridR1c5],
      <String>[LabImages.albumSungsuGridR2c1, LabImages.albumSungsuGridR2c2, LabImages.albumSungsuGridR2c3, LabImages.albumSungsuGridR2c4, LabImages.albumSungsuGridR2c5],
      <String>[LabImages.albumSungsuGridR3c1, LabImages.albumSungsuGridR3c2, LabImages.albumSungsuGridR3c3, LabImages.albumSungsuGridR3c4, LabImages.albumSungsuGridR3c5],
      <String>[LabImages.albumSungsuGridR4c1, LabImages.albumSungsuGridR4c2, LabImages.albumSungsuGridR4c3, LabImages.albumSungsuGridR4c4, LabImages.albumSungsuGridR4c5],
      <String>[LabImages.albumSungsuGridR5c1, LabImages.albumSungsuGridR5c2, LabImages.albumSungsuGridR5c3, LabImages.albumSungsuGridR5c4, LabImages.albumSungsuGridR5c5],
      <String>[LabImages.albumSungsuGridR6c1, LabImages.albumSungsuGridR6c2, LabImages.albumSungsuGridR6c3, LabImages.albumSungsuGridR6c4, LabImages.albumSungsuGridR6c5],
    ],
    photos: <GridPhotoContent>[
      GridPhotoContent(image: LabImages.albumSungsuGridR1c1, liked: true),
      GridPhotoContent(image: LabImages.albumSungsuGridR1c3, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR1c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR1c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR2c3, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR2c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR2c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c1, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c2, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c3, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR4c1, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR4c2, liked: true),
      GridPhotoContent(image: LabImages.albumSungsuGridR4c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR4c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR5c1, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR5c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR5c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c1, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c2, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c3, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c5, liked: false),
    ],
  ),
  featured: <FeaturedTileContent>[
    FeaturedTileContent(nodeId: '2001:1168', image: LabImages.albumSungsuGridR1c1, row: 1, col: 1, rowSpan: 2, colSpan: 2, liked: true),
    FeaturedTileContent(nodeId: '2001:1171', image: LabImages.albumSungsuGridR4c2, row: 4, col: 2, rowSpan: 2, colSpan: 2, liked: true),
  ],
  quoteCard: QuoteCardContent(
    nodeId: '2015:1954',
    label: '중요 내용 #1',
    labelAlign: LabAlign.left,
    lines: <QuoteLineContent>[
      QuoteLineContent(nodeId: '2015:1956', text: '나 내일 수능이라 컴싸 꼭 필요해!', align: LabAlign.left, gradient: GradientTextContent(solidUntil: 0.46635)),
      QuoteLineContent(nodeId: '2015:1957', text: '아 알겠어 꼭 챙겨갈게!', align: LabAlign.right, gradient: null),
    ],
  ),
  tabBar: TabBarContent(nodeId: '2001:1375', selectedIndex: 0, avatar: LabImages.tabbarAvatar),
);

const TranscriptContent labTranscript = TranscriptContent(
  screenNodeIds: LabNodeIds(light: '2042:3219', dark: '2042:2933'),
  title: '성수 데이트 코스에 대한 대화',
  date: '8월 20일, 12시 20분',
  darkBackground: LabImages.transcriptDarkBackground,
  lines: <TranscriptLineContent>[
    TranscriptLineContent(id: 'l1', nodeIds: LabNodeIds(light: '2042:3246', dark: '2042:3132'), text: '주영아 토요일에 성수 갈까?', side: LabAlign.left, inHighlight: false, current: false, gradient: null),
    TranscriptLineContent(id: 'l2', nodeIds: LabNodeIds(light: '2042:3257', dark: '2042:3135'), text: '좋아 나 거기 가보고 싶은 데 있었어', side: LabAlign.right, inHighlight: false, current: false, gradient: null),
    TranscriptLineContent(id: 'l3', nodeIds: LabNodeIds(light: '2042:3248', dark: '2042:3137'), text: '저번에 말한 대림창고 쪽 말고 연무장길 안쪽에\n새로 생긴 카페?', side: LabAlign.left, inHighlight: false, current: false, gradient: null),
    TranscriptLineContent(id: 'l4', nodeIds: LabNodeIds(light: '2042:3251', dark: '2042:3139'), text: '거기 3시 전에 가야 웨이팅 없대! 토요일에 1시쯤 서울숲에서 만나서 걸어가면 딱 맞을 것 같은데', side: LabAlign.left, inHighlight: true, current: false, gradient: null),
    TranscriptLineContent(id: 'l5', nodeIds: LabNodeIds(light: '2042:3252', dark: '2042:3141'), text: '오 그럼 1시에 서울숲역 4번 출구에서 봐!', side: LabAlign.right, inHighlight: true, current: true, gradient: GradientTextContent(solidUntil: 0.60577)),
    TranscriptLineContent(id: 'l6', nodeIds: LabNodeIds(light: '2042:3253', dark: '2042:3213'), text: '저녁은 어디서 먹지', side: LabAlign.left, inHighlight: true, current: false, gradient: null),
    TranscriptLineContent(id: 'l7', nodeIds: LabNodeIds(light: '2042:3254', dark: '2042:3215'), text: '일단 카페 갔다가 정하자', side: LabAlign.right, inHighlight: true, current: false, gradient: null),
    TranscriptLineContent(id: 'l8', nodeIds: LabNodeIds(light: '2042:3255', dark: '2042:3217'), text: '좋아 기대된다!!', side: LabAlign.left, inHighlight: true, current: false, gradient: null),
  ],
  player: PlayerContent(
    nodeIds: LabNodeIds(light: '2042:3224', dark: '2042:3105'),
    currentTime: '00:00',
    duration: '07:23',
    durationSeconds: 443,
    playing: true,
    trackWidthPx: 155.0,
    trackWidthPxDark: 154.0,
    progressWidthPx: 36.0,
    progress: 0.232258,
    thumbLeftPx: 24.0,
    thumbSizePx: 24.0,
    thumbCenterPx: 36.0,
    thumbCenter: 0.232258,
    markers: <PlayerMarkerContent>[
      PlayerMarkerContent(nodeIds: LabNodeIds(light: '2042:3226', dark: '2042:3107'), leftPx: 80.0, widthPx: 19.0, start: 0.516129, width: 0.122581),
      PlayerMarkerContent(nodeIds: LabNodeIds(light: '2042:3227', dark: '2042:3108'), leftPx: 122.0, widthPx: 12.0, start: 0.787097, width: 0.077419),
    ],
  ),
);

const InCallContent labInCall = InCallContent(
  screenNodeIds: <String>['2042:2361', '2042:2504', '2042:2581', '2042:2650', '2004:1796'],
  name: 'Yurim',
  timer: '00:04',
  background: LabImages.callBackground,
  toasts: InCallToastsContent(
    systemMessage: ToastContent(
      screenNodeId: '2042:2361',
      nodeId: '2042:2498',
      text: '시스템 메시지입니다.',
      icon: 'border-none',
      iconIsPlaceholder: true,
    ),
    sleepModeRequest: ToastContent(
      screenNodeId: '2004:1796',
      nodeId: '2004:1818',
      text: 'Yurim님께 취침 모드 전환 요청이 전송되었습니다!',
      icon: 'moon-filled',
      iconIsPlaceholder: false,
    ),
  ),
);

const PhotoBoothSampleContent labPhotoBoothSample = PhotoBoothSampleContent(nodeId: '2042:3117', image: LabImages.albumSungsuGridR4c2);

const CameraContent labCamera = CameraContent(
  screenNodeId: '2056:3280',
  placeholderNodeId: '2058:3415',
  placeholder: LabImages.cameraPlaceholder,
  initialMode: CameraModeId.photo,
  modes: <CameraModeContent>[
    CameraModeContent(id: CameraModeId.photo, nodeId: '2056:3394', labelNodeId: '2056:3410', label: '사진'),
    CameraModeContent(id: CameraModeId.video, nodeId: '2056:3412', labelNodeId: '2056:3414', label: '동영상'),
  ],
);

const InCallV5Content labInCallV5 = InCallV5Content(
  screenNodeIds: <String>['2170:8678', '2170:9065', '2176:9162', '2170:8774', '2170:8313'],
  name: 'Yurim',
  timer: '00:04',
  background: LabImages.albumSungsuCover,
  toasts: InCallV5ToastsContent(
    sleep: ToastContent(
      screenNodeId: '2170:8678',
      nodeId: '2170:8743',
      text: 'Yurim님이 취침모드 전환로 전환했어요!',
      icon: 'moon-filled',
      iconIsPlaceholder: false,
    ),
    highlight: ToastContent(
      screenNodeId: '2176:9162',
      nodeId: '2176:9229',
      text: '전후 15초 하이라이트가 저장됐어요!',
      icon: 'info-circle',
      iconIsPlaceholder: false,
    ),
  ),
  photoSheet: PhotoSheetContent(
    screenNodeId: '2170:8774',
    nodeId: '2170:9008',
    title: '사진',
    liveCell: SheetLiveCellContent(nodeId: '2170:9039', image: LabImages.photoSheetLiveCamera, row: 1, col: 1, rowSpan: 2),
    columns: 3,
    rows: <List<String>>[
      <String>[LabImages.albumSungsuGridR1c1, LabImages.albumSungsuGridR1c2, LabImages.albumSungsuGridR1c3],
      <String>[LabImages.albumSungsuGridR2c1, LabImages.albumSungsuGridR2c2, LabImages.albumSungsuGridR2c3],
      <String>[LabImages.albumSungsuGridR3c1, LabImages.albumSungsuGridR3c2, LabImages.albumSungsuGridR3c3],
      <String>[LabImages.albumSungsuGridR4c1, LabImages.albumSungsuGridR4c2, LabImages.albumSungsuGridR4c3],
    ],
    photos: <SheetPhotoContent>[
      SheetPhotoContent(image: LabImages.albumSungsuGridR1c2, selected: true),
      SheetPhotoContent(image: LabImages.albumSungsuGridR1c3, selected: true),
      SheetPhotoContent(image: LabImages.albumSungsuGridR2c2, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR2c3, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR3c1, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR3c2, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR3c3, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR4c1, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR4c2, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR4c3, selected: false),
    ],
  ),
  capturedCard: CapturedCardContent(nodeId: '2170:8607', image: LabImages.albumSungsuGridR3c2Hires, orientation: CapturedOrientation.portrait),
);

const CameraV5Content labCameraV5 = CameraV5Content(
  screenNodeId: '2170:5682',
  viewfinderNodeId: '2170:5760',
  viewfinder: LabImages.cameraViewfinderV5,
  thumbnailNodeId: '2170:5904',
  thumbnail: LabImages.albumSungsuGridR5c4Hires,
  toast: ToastContent(
    screenNodeId: '2170:5682',
    nodeId: '2170:9152',
    text: 'Yurim님이 인스턴트를 공유했어요!',
    icon: 'info-circle',
    iconIsPlaceholder: false,
  ),
);

const ViewerV5Content labViewerV5 = ViewerV5Content(
  photo: ViewerContent(screenNodeId: '2170:7914', cardNodeId: '2170:8068', image: LabImages.albumSungsuGridR5c4Hires, date: '오늘, 00시 00분', actions: <String>['share-2', 'heart', 'trash']),
  instant: ViewerContent(screenNodeId: '2170:6159', cardNodeId: '2170:6162', image: LabImages.albumSungsuGridR5c4Hires, date: '오늘, 00시 00분', actions: <String>['share-2', 'heart']),
);

const TabBarV5Content labTabBarV5 = TabBarV5Content(nodeId: '2166:5444', avatar: LabImages.albumSungsuGridR1c1Hires);

const AlbumV5Content labAlbumV5 = AlbumV5Content(
  screenNodeId: '2170:6590',
  contentNodeId: '2232:2109',
  nav: AlbumV5NavContent(selectLabel: '선택', actions: <String>['phone-call', 'heart', 'history']),
  selectNav: AlbumV5SelectNavContent(actions: <String>['share-2', 'trash']),
  sections: <AlbumV5SectionContent>[
    AlbumV5SectionContent(
      id: 'sungsu',
      figmaName: '1',
      nodeId: '2170:7307',
      kind: AlbumSectionKind.photosCalls,
      tint: 'album/section-1',
      heroGradient: 'albumHeroV5',
      cover: LabImages.albumSungsuCover,
      title: '성수 → 한남',
      subtitle: '2026년 8월 20일, 6시간',
      stats: AlbumStatsContent(photos: '30', calls: '3'),
      callCards: <CallCardV5Content>[
        CallCardV5Content(
          nodeId: '2170:7320',
          variant: 'scrim',
          direction: CallDirection.outgoing,
          icon: 'arrow-up-right',
          title: '성수 데이트 코스에 대한 대화',
          subtitle: <LabTextSpan>[
            LabTextSpan('12시 20분', LabTextWeight.regular),
            LabTextSpan(' ∙ 발신 통화 21분 17초', LabTextWeight.regular),
          ],
        ),
        CallCardV5Content(
          nodeId: '2170:7321',
          variant: 'scrim',
          direction: CallDirection.incoming,
          icon: 'arrow-down-left',
          title: '아침 인사',
          subtitle: <LabTextSpan>[
            LabTextSpan('8시 12분', LabTextWeight.regular),
            LabTextSpan(' ∙ 수신 통화 5분 10초', LabTextWeight.regular),
          ],
        ),
        CallCardV5Content(
          nodeId: '2170:7322',
          variant: 'failed',
          direction: CallDirection.missed,
          icon: 'arrow-down-left',
          title: '부재중',
          subtitle: <LabTextSpan>[
            LabTextSpan('8시 10분', LabTextWeight.regular),
          ],
        ),
      ],
      grid: PhotoGridContent(
        columns: 5,
        rows: <List<String>>[
          <String>[LabImages.albumSungsuGridR1c1, LabImages.albumSungsuGridR1c2, LabImages.albumSungsuGridR1c3, LabImages.albumSungsuGridR1c4, LabImages.albumSungsuGridR1c5],
          <String>[LabImages.albumSungsuGridR2c1, LabImages.albumSungsuGridR2c2, LabImages.albumSungsuGridR2c3, LabImages.albumSungsuGridR2c4, LabImages.albumSungsuGridR2c5],
          <String>[LabImages.albumSungsuGridR3c1, LabImages.albumSungsuGridR3c2, LabImages.albumSungsuGridR3c3, LabImages.albumSungsuGridR3c4, LabImages.albumSungsuGridR3c5],
          <String>[LabImages.albumSungsuGridR4c1, LabImages.albumSungsuGridR4c2, LabImages.albumSungsuGridR4c3, LabImages.albumSungsuGridR4c4, LabImages.albumSungsuGridR4c5],
          <String>[LabImages.albumSungsuGridR5c1, LabImages.albumSungsuGridR5c2, LabImages.albumSungsuGridR5c3, LabImages.albumSungsuGridR5c4, LabImages.albumSungsuGridR5c5],
          <String>[LabImages.albumSungsuGridR6c1, LabImages.albumSungsuGridR6c2, LabImages.albumSungsuGridR6c3, LabImages.albumSungsuGridR6c4, LabImages.albumSungsuGridR6c5],
        ],
        photos: <GridPhotoContent>[
          GridPhotoContent(image: LabImages.albumSungsuGridR1c1, liked: true),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c5, liked: false),
        ],
      ),
      featured: <FeaturedTileContent>[
        FeaturedTileContent(nodeId: '2170:8302', image: LabImages.albumSungsuGridR1c1, row: 1, col: 1, rowSpan: 2, colSpan: 2, liked: true),
      ],
    ),
    AlbumV5SectionContent(
      id: 'calls-only',
      figmaName: 'empty photo',
      nodeId: '2170:7360',
      kind: AlbumSectionKind.callsOnly,
      tint: 'album/section-calls',
      heroGradient: null,
      cover: null,
      title: '2026년 8월 20일',
      subtitle: '전체 통화 요약',
      stats: AlbumStatsContent(photos: '0', calls: '2'),
      callCards: <CallCardV5Content>[
        CallCardV5Content(
          nodeId: '2170:7373',
          variant: 'default',
          direction: CallDirection.outgoing,
          icon: 'arrow-up-right',
          title: '자긴 전 대화',
          subtitle: <LabTextSpan>[
            LabTextSpan('23시 10분 ∙ 발신 통화 21분 17초', LabTextWeight.regular),
          ],
        ),
        CallCardV5Content(
          nodeId: '2170:7374',
          variant: 'default',
          direction: CallDirection.incoming,
          icon: 'arrow-down-left',
          title: '아침 인사',
          subtitle: <LabTextSpan>[
            LabTextSpan('08시 00분 ∙ 수신 통화 5분 10초', LabTextWeight.regular),
          ],
        ),
      ],
      grid: null,
      featured: <FeaturedTileContent>[],
    ),
    AlbumV5SectionContent(
      id: 'section-2',
      figmaName: '2',
      nodeId: '2170:7375',
      kind: AlbumSectionKind.photosOnly,
      tint: 'album/section-3',
      heroGradient: 'albumHeroV5Section2',
      cover: LabImages.album3Cover,
      title: '2026년 8월 20일',
      subtitle: '전체 사진 요약',
      stats: AlbumStatsContent(photos: '2', calls: '0'),
      callCards: <CallCardV5Content>[],
      grid: PhotoGridContent(
        columns: 5,
        rows: <List<String>>[
          <String>[LabImages.album3Cover, LabImages.album3GridR1c2],
        ],
        photos: <GridPhotoContent>[
          GridPhotoContent(image: LabImages.album3Cover, liked: false),
          GridPhotoContent(image: LabImages.album3GridR1c2, liked: false),
        ],
      ),
      featured: <FeaturedTileContent>[],
    ),
  ],
);

const SettingsV5Content labSettingsV5 = SettingsV5Content(
  screenNodeId: '2176:11011',
  hero: LabImages.albumSungsuCover,
  names: '이주영, 이유림',
  days: 200,
  dayCount: '200일째',
  daySuffix: ' 공유중',
  editProfile: SettingsActionContent(nodeId: '2176:11374', label: '프로필 수정', icon: 'pencil'),
  disconnect: SettingsActionContent(nodeId: '2176:11483', label: '연결 해제', icon: 'link-off'),
);

const TranscriptV5Content labTranscriptV5 = TranscriptV5Content(
  screenNodeId: '2176:9241',
  variantNodeIds: <String>['2232:2862', '2232:2932', '2194:13374'],
  title: '성수 데이트 코스에 대한 대화',
  date: '8월 20일, 12시 20분',
  navActions: <String>['phone-call', 'heart'],
  lines: <TranscriptV5LineContent>[
    TranscriptV5LineContent(id: 'l1', nodeId: '2176:10929', text: '주영아 토요일에 성수 갈까?', side: LabAlign.left, inHighlight: false, current: false),
    TranscriptV5LineContent(id: 'l2', nodeId: '2176:10931', text: '좋아 나 거기 가보고 싶은 데 있었어', side: LabAlign.right, inHighlight: false, current: false),
    TranscriptV5LineContent(id: 'l3', nodeId: '2176:10933', text: '저번에 말한 대림창고 쪽 말고 연무장길 안쪽에\n새로 생긴 카페?', side: LabAlign.left, inHighlight: false, current: false),
    TranscriptV5LineContent(id: 'l4', nodeId: '2176:10937', text: '거기 3시 전에 가야 웨이팅 없대! 토요일에 1시쯤 서울숲에서 만나서 걸어가면 딱 맞을 것 같은데', side: LabAlign.left, inHighlight: true, current: false),
    TranscriptV5LineContent(id: 'l5', nodeId: '2176:10938', text: '오 그럼 1시에 서울숲역 4번 출구에서 봐!', side: LabAlign.right, inHighlight: true, current: true),
    TranscriptV5LineContent(id: 'l6', nodeId: '2176:10939', text: '저녁은 어디서 먹지', side: LabAlign.left, inHighlight: true, current: false),
    TranscriptV5LineContent(id: 'l7', nodeId: '2176:10940', text: '일단 카페 갔다가 정하자', side: LabAlign.right, inHighlight: true, current: false),
    TranscriptV5LineContent(id: 'l8', nodeId: '2176:10941', text: '좋아 기대된다!!', side: LabAlign.left, inHighlight: true, current: false),
  ],
  inlinePhoto: InlinePhotoContent(nodeId: '2176:10934', image: LabImages.transcriptInlinePhoto, afterLineId: 'l3'),
  player: PlayerV5Content(
    nodeId: '2176:10994',
    currentTime: '00:00',
    duration: '07:23',
    durationSeconds: 443,
    playing: true,
    trackWidthPx: 157.0,
    progressWidthPx: 47.0,
    progress: 0.299363,
    thumbLeftPx: 32.5,
    thumbSizePx: 28.0,
    thumbCenterPx: 46.5,
    thumbCenter: 0.296178,
    markers: <PlayerV5MarkerContent>[
      PlayerV5MarkerContent(nodeId: '2176:11006', leftPx: 75.0, widthPx: 16.0, start: 0.477707, width: 0.101911),
      PlayerV5MarkerContent(nodeId: '2176:11007', leftPx: 112.0, widthPx: 16.0, start: 0.713376, width: 0.101911),
    ],
  ),
);

// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------

class LabV6 {
  static LabV6 of(BuildContext context) => Localizations.of<LabV6>(context, LabV6) ?? labV6;
  static const delegate = ContentLocaleDelegate<LabV6>(ko: labV6, en: labV6En);

  const LabV6({required this.welcome, required this.phone, required this.verify, required this.profile, required this.partner, required this.connected, required this.permissions, required this.settings, required this.tabBar, required this.album, required this.emptyAlbum, required this.viewer, required this.transcript, required this.call, required this.camera, required this.review});
  final LabV6Welcome welcome;
  final LabV6Phone phone;
  final LabV6Verify verify;
  final LabV6Profile profile;
  final LabV6Partner partner;
  final LabV6Connected connected;
  final LabV6Permissions permissions;
  final LabV6Settings settings;
  final LabV6TabBar tabBar;
  final LabV6Album album;
  final LabV6EmptyAlbum emptyAlbum;
  final LabV6Viewer viewer;
  final LabV6Transcript transcript;
  final LabV6Call call;
  final LabV6Camera camera;
  final LabV6Review review;
}

class LabV6Review {
  const LabV6Review({required this.discardIcon, required this.sendIcon});
  final String discardIcon;
  final String sendIcon;
}

class LabV6Camera {
  const LabV6Camera({required this.partnerToast, required this.viewfinder, required this.thumbnail, required this.flipIcon});
  final LabV6CameraPartnerToast partnerToast;
  final String viewfinder;
  final String thumbnail;
  final String flipIcon;
}

class LabV6CameraPartnerToast {
  const LabV6CameraPartnerToast({required this.text, required this.icon});
  final String text;
  final String icon;
}

class LabV6Call {
  const LabV6Call({required this.navIcons, required this.barIcons, required this.highlightToast, required this.sleepEnd});
  final List<String> navIcons;
  final List<String> barIcons;
  final LabV6CallHighlightToast highlightToast;
  final LabV6CallSleepEnd sleepEnd;
}

class LabV6CallSleepEnd {
  const LabV6CallSleepEnd({required this.label, required this.icon});
  final String label;
  final String icon;
}

class LabV6CallHighlightToast {
  const LabV6CallHighlightToast({required this.text, required this.icon});
  final String text;
  final String icon;
}

class LabV6Transcript {
  const LabV6Transcript({required this.navActions, required this.closeIcon});
  final List<String> navActions;
  final String closeIcon;
}

class LabV6Viewer {
  const LabV6Viewer({required this.date, required this.actions, required this.image, required this.closeIcon});
  final String date;
  final List<String> actions;
  final String image;
  final String closeIcon;
}

class LabV6EmptyAlbum {
  const LabV6EmptyAlbum({required this.title, required this.cta, required this.ctaIcon, required this.meInitialSample, required this.partnerPhoto});
  final String title;
  final String cta;
  final String ctaIcon;
  final String meInitialSample;
  final String partnerPhoto;
}

class LabV6Album {
  const LabV6Album({required this.selectLabel, required this.navActions, required this.selectActions, required this.likedActions, required this.deletedActions, required this.closeIcon});
  final String selectLabel;
  final List<String> navActions;
  final List<String> selectActions;
  final List<String> likedActions;
  final List<String> deletedActions;
  final String closeIcon;
}

class LabV6TabBar {
  const LabV6TabBar({required this.tabs, required this.callIcon});
  final List<LabV6TabBarTab> tabs;
  final String callIcon;
}

class LabV6TabBarTab {
  const LabV6TabBarTab({required this.id, required this.icon, required this.label});
  final String id;
  final String icon;
  final String label;
}

class LabV6Settings {
  const LabV6Settings({required this.title, required this.me, required this.partnerSection, required this.partner, required this.notificationsSection, required this.callAlerts, required this.highlightAlerts, required this.developerSection, required this.lab, required this.flowDemo, required this.rowIcon, required this.disconnect});
  final String title;
  final LabV6SettingsMe me;
  final String partnerSection;
  final LabV6SettingsPartner partner;
  final String notificationsSection;
  final String callAlerts;
  final String highlightAlerts;
  final String developerSection;
  final String lab;
  final String flowDemo;
  final String rowIcon;
  final LabV6SettingsDisconnect disconnect;
}

class LabV6SettingsDisconnect {
  const LabV6SettingsDisconnect({required this.label, required this.icon});
  final String label;
  final String icon;
}

class LabV6SettingsPartner {
  const LabV6SettingsPartner({required this.name, required this.phone, required this.initial, required this.status});
  final String name;
  final String phone;
  final String initial;
  final String status;
}

class LabV6SettingsMe {
  const LabV6SettingsMe({required this.name, required this.phone, required this.initial});
  final String name;
  final String phone;
  final String initial;
}

class LabV6Permissions {
  const LabV6Permissions({required this.title, required this.subtitle, required this.skip, required this.cta, required this.items});
  final String title;
  final String subtitle;
  final String skip;
  final String cta;
  final List<LabV6PermissionsItem> items;
}

class LabV6PermissionsItem {
  const LabV6PermissionsItem({required this.id, required this.icon, required this.title, required this.description});
  final String id;
  final String icon;
  final String title;
  final String description;
}

class LabV6Connected {
  const LabV6Connected({required this.message, required this.meInitialSample, required this.partnerPhoto});
  final String message;
  final String meInitialSample;
  final String partnerPhoto;
}

class LabV6Partner {
  const LabV6Partner({required this.title, required this.subtitle, required this.codePlaceholder, required this.myCodeLabel, required this.myCode, required this.copyIcon});
  final String title;
  final String subtitle;
  final String codePlaceholder;
  final String myCodeLabel;
  final String myCode;
  final String copyIcon;
}

class LabV6Profile {
  const LabV6Profile({required this.title, required this.subtitle, required this.placeholder, required this.cta});
  final String title;
  final String subtitle;
  final String placeholder;
  final String cta;
}

class LabV6Verify {
  const LabV6Verify({required this.title, required this.timerSample, required this.codePlaceholder, required this.resend, required this.successIcon});
  final String title;
  final String timerSample;
  final String codePlaceholder;
  final String resend;
  final String successIcon;
}

class LabV6Phone {
  const LabV6Phone({required this.title, required this.subtitle, required this.prefix, required this.placeholder, required this.cta});
  final String title;
  final String subtitle;
  final String prefix;
  final String placeholder;
  final String cta;
}

class LabV6Welcome {
  const LabV6Welcome({required this.wordmark, required this.tagline, required this.cta});
  final String wordmark;
  final String tagline;
  final String cta;
}

const LabV6 labV6 = LabV6(
  welcome: LabV6Welcome(
    wordmark: 'CAMEO',
    tagline: '통화하고, 함께 찍고, 모든 기록을 앨범으로 남겨보세요.',
    cta: '전화번호로 시작',
  ),
  phone: LabV6Phone(
    title: '전화번호를 입력해 주세요',
    subtitle: '인증번호를 문자로 보내 드릴게요.',
    prefix: '+82',
    placeholder: '010-0000-0000',
    cta: '인증번호 전송',
  ),
  verify: LabV6Verify(
    title: '인증번호를 입력해 주세요',
    timerSample: '02:58',
    codePlaceholder: '0',
    resend: '인증번호 재전송',
    successIcon: 'check',
  ),
  profile: LabV6Profile(
    title: '이름을 입력해 주세요',
    subtitle: '상대에게 이 이름으로 보여요.',
    placeholder: '이름',
    cta: '다음',
  ),
  partner: LabV6Partner(
    title: '커플 연결',
    subtitle: '상대의 코드 6자리를 입력해 주세요.',
    codePlaceholder: '0',
    myCodeLabel: '내 코드',
    myCode: '735102',
    copyIcon: 'copy',
  ),
  connected: LabV6Connected(
    message: '성공적으로 {partner}님과 연결됐어요!',
    meInitialSample: '이',
    partnerPhoto: LabImages.albumSungsuCover,
  ),
  permissions: LabV6Permissions(
    title: '권한을 허용해 주세요',
    subtitle: '앱을 사용하려면 아래 권한이 필요해요.',
    skip: '나중에',
    cta: '일괄 허용',
    items: <LabV6PermissionsItem>[
      LabV6PermissionsItem(
        id: 'microphone',
        icon: 'microphone',
        title: '마이크',
        description: '통화를 녹음하고 기록으로 정리해요.',
      ),
      LabV6PermissionsItem(
        id: 'camera',
        icon: 'camera',
        title: '카메라',
        description: '함께 사진을 공유해 보세요.',
      ),
      LabV6PermissionsItem(
        id: 'notifications',
        icon: 'notification',
        title: '알림',
        description: '상대가 활동하면 알려 드려요.',
      ),
    ],
  ),
  settings: LabV6Settings(
    title: '설정',
    me: LabV6SettingsMe(
      name: '이주영',
      phone: '+82 10 3929 8983',
      initial: '이',
    ),
    partnerSection: '상대',
    partner: LabV6SettingsPartner(
      name: '이유림',
      phone: '+82 10 3929 8983',
      initial: '이',
      status: '연결됨',
    ),
    notificationsSection: '알림',
    callAlerts: '통화 알림',
    highlightAlerts: '하이라이트 요약 알림',
    developerSection: '개발',
    lab: '개발용 화면 목록 (Lab)',
    flowDemo: '흐름 데모 보기',
    rowIcon: 'chevron-right',
    disconnect: LabV6SettingsDisconnect(
      label: '연결 해제',
      icon: 'link-off',
    ),
  ),
  tabBar: LabV6TabBar(
    tabs: <LabV6TabBarTab>[
      LabV6TabBarTab(
        id: 'history',
        icon: 'calendar-week',
        label: '추억',
      ),
      LabV6TabBarTab(
        id: 'camera',
        icon: 'live-photo',
        label: '지금',
      ),
      LabV6TabBarTab(
        id: 'settings',
        icon: 'user',
        label: '우리',
      ),
    ],
    callIcon: 'phone-call',
  ),
  album: LabV6Album(
    selectLabel: '선택',
    navActions: <String>[
      'plus',
      'heart',
      'history',
    ],
    selectActions: <String>[
      'share-2',
      'heart',
      'trash',
    ],
    likedActions: <String>[
      'share-2',
      'heart',
      'trash',
    ],
    deletedActions: <String>[
      'archive',
    ],
    closeIcon: 'x',
  ),
  emptyAlbum: LabV6EmptyAlbum(
    title: '아직 저장된 사진·영상이 없어요!',
    cta: '사진·영상 불러오기',
    ctaIcon: 'photo',
    meInitialSample: '이',
    partnerPhoto: LabImages.albumSungsuCover,
  ),
  viewer: LabV6Viewer(
    date: '오늘, 12시 00분',
    actions: <String>[
      'share-2',
      'heart',
      'trash',
    ],
    image: LabImages.albumSungsuGridR5c4Hires,
    closeIcon: 'x',
  ),
  transcript: LabV6Transcript(
    navActions: <String>[
      'phone-call',
      'heart',
    ],
    closeIcon: 'x',
  ),
  call: LabV6Call(
    navIcons: <String>[
      'chevron-down',
      'moon',
    ],
    barIcons: <String>[
      'volume',
      'microphone',
      'camera',
      'rewind-backward-15',
      'x',
    ],
    highlightToast: LabV6CallHighlightToast(
      text: '전후 15초 하이라이트가 저장됐어요!',
      icon: 'info-circle',
    ),
    sleepEnd: LabV6CallSleepEnd(
      label: '취침모드 종료',
      icon: 'sunrise',
    ),
  ),
  camera: LabV6Camera(
    partnerToast: LabV6CameraPartnerToast(
      text: 'Yurim님이 사진을 공유했어요!',
      icon: 'info-circle',
    ),
    viewfinder: LabImages.cameraViewfinderV5,
    thumbnail: LabImages.albumSungsuGridR5c4Hires,
    flipIcon: 'refresh',
  ),
  review: LabV6Review(
    discardIcon: 'trash',
    sendIcon: 'arrow-up',
  ),
);
const LabV6 labV6En = LabV6(
  welcome: LabV6Welcome(
    wordmark: 'CAMEO',
    tagline: 'Call, capture, and keep your moments together.',
    cta: 'Continue with phone',
  ),
  phone: LabV6Phone(
    title: 'Mobile number',
    subtitle: 'Get a code by text.',
    prefix: '+82',
    placeholder: '010-0000-0000',
    cta: 'Send code',
  ),
  verify: LabV6Verify(
    title: 'Enter your code',
    timerSample: '02:58',
    codePlaceholder: '0',
    resend: 'Resend code',
    successIcon: 'check',
  ),
  profile: LabV6Profile(
    title: 'Your name',
    subtitle: 'For your partner.',
    placeholder: 'Name',
    cta: 'Continue',
  ),
  partner: LabV6Partner(
    title: 'Partner',
    subtitle: 'Their 6-digit code',
    codePlaceholder: '0',
    myCodeLabel: 'My code',
    myCode: '735102',
    copyIcon: 'copy',
  ),
  connected: LabV6Connected(
    message: 'You\'re connected with {partner}!',
    meInitialSample: 'J',
    partnerPhoto: LabImages.albumSungsuCover,
  ),
  permissions: LabV6Permissions(
    title: 'Permissions',
    subtitle: 'Needed to use cameo.',
    skip: 'Later',
    cta: 'Allow all',
    items: <LabV6PermissionsItem>[
      LabV6PermissionsItem(
        id: 'microphone',
        icon: 'microphone',
        title: 'Microphone',
        description: 'Record calls and save your conversations.',
      ),
      LabV6PermissionsItem(
        id: 'camera',
        icon: 'camera',
        title: 'Camera',
        description: 'Capture and share photos together.',
      ),
      LabV6PermissionsItem(
        id: 'notifications',
        icon: 'notification',
        title: 'Notifications',
        description: 'Know when your partner is active.',
      ),
    ],
  ),
  settings: LabV6Settings(
    title: 'Settings',
    me: LabV6SettingsMe(
      name: 'Juyoung Lee',
      phone: '+82 10 3929 8983',
      initial: 'J',
    ),
    partnerSection: 'Partner',
    partner: LabV6SettingsPartner(
      name: 'Yurim Lee',
      phone: '+82 10 3929 8983',
      initial: 'J',
      status: 'Connected',
    ),
    notificationsSection: 'Notifications',
    callAlerts: 'Call alerts',
    highlightAlerts: 'Highlight summary alerts',
    developerSection: 'Developer',
    lab: 'Screen library (Lab)',
    flowDemo: 'Play flow demo',
    rowIcon: 'chevron-right',
    disconnect: LabV6SettingsDisconnect(
      label: 'Disconnect',
      icon: 'link-off',
    ),
  ),
  tabBar: LabV6TabBar(
    tabs: <LabV6TabBarTab>[
      LabV6TabBarTab(
        id: 'history',
        icon: 'calendar-week',
        label: 'Memories',
      ),
      LabV6TabBarTab(
        id: 'camera',
        icon: 'live-photo',
        label: 'Now',
      ),
      LabV6TabBarTab(
        id: 'settings',
        icon: 'user',
        label: 'Us',
      ),
    ],
    callIcon: 'phone-call',
  ),
  album: LabV6Album(
    selectLabel: 'Select',
    navActions: <String>[
      'plus',
      'heart',
      'history',
    ],
    selectActions: <String>[
      'share-2',
      'heart',
      'trash',
    ],
    likedActions: <String>[
      'share-2',
      'heart',
      'trash',
    ],
    deletedActions: <String>[
      'archive',
    ],
    closeIcon: 'x',
  ),
  emptyAlbum: LabV6EmptyAlbum(
    title: 'No photos or videos yet!',
    cta: 'Import media',
    ctaIcon: 'photo',
    meInitialSample: 'J',
    partnerPhoto: LabImages.albumSungsuCover,
  ),
  viewer: LabV6Viewer(
    date: 'Today, 12:00 PM',
    actions: <String>[
      'share-2',
      'heart',
      'trash',
    ],
    image: LabImages.albumSungsuGridR5c4Hires,
    closeIcon: 'x',
  ),
  transcript: LabV6Transcript(
    navActions: <String>[
      'phone-call',
      'heart',
    ],
    closeIcon: 'x',
  ),
  call: LabV6Call(
    navIcons: <String>[
      'chevron-down',
      'moon',
    ],
    barIcons: <String>[
      'volume',
      'microphone',
      'camera',
      'rewind-backward-15',
      'x',
    ],
    highlightToast: LabV6CallHighlightToast(
      text: 'Saved a highlight with 15 seconds before and after!',
      icon: 'info-circle',
    ),
    sleepEnd: LabV6CallSleepEnd(
      label: 'End sleep mode',
      icon: 'sunrise',
    ),
  ),
  camera: LabV6Camera(
    partnerToast: LabV6CameraPartnerToast(
      text: 'Yurim shared a photo!',
      icon: 'info-circle',
    ),
    viewfinder: LabImages.cameraViewfinderV5,
    thumbnail: LabImages.albumSungsuGridR5c4Hires,
    flipIcon: 'refresh',
  ),
  review: LabV6Review(
    discardIcon: 'trash',
    sendIcon: 'arrow-up',
  ),
);

const AlbumDayContent labAlbumDayEn = AlbumDayContent(
  screenNodeId: '2028:435',
  sections: <AlbumSectionContent>[
    AlbumSectionContent(
      id: 'sungsu',
      figmaName: '1',
      nodeId: '2042:2791',
      tone: LabTone.dark,
      cover: LabImages.albumSungsuCover,
      title: 'Seongsu → Hannam',
      subtitle: 'August 20, 2026 · 6 hours',
      stats: AlbumStatsContent(photos: '30', calls: '3'),
      callCards: <CallCardContent>[
        CallCardContent(
          nodeId: '2042:2804',
          direction: CallDirection.outgoing,
          icon: 'arrow-up-right',
          title: 'Planning our Seongsu date',
          subtitle: <LabTextSpan>[
            LabTextSpan('12:20 PM', LabTextWeight.medium),
            LabTextSpan(' ∙ Outgoing call, 21m 17s', LabTextWeight.regular),
          ],
        ),
        CallCardContent(
          nodeId: '2042:2809',
          direction: CallDirection.incoming,
          icon: 'arrow-down-left',
          title: 'Good morning',
          subtitle: <LabTextSpan>[
            LabTextSpan('8:12 AM', LabTextWeight.medium),
            LabTextSpan(' ∙ Incoming call, 5m 10s', LabTextWeight.regular),
          ],
        ),
        CallCardContent(
          nodeId: '2042:2814',
          direction: CallDirection.missed,
          icon: 'arrow-down-left',
          title: 'Juyoung, wake up!',
          subtitle: <LabTextSpan>[
            LabTextSpan('8:10 AM', LabTextWeight.medium),
            LabTextSpan(' ∙ Missed call', LabTextWeight.regular),
          ],
        ),
      ],
      grid: PhotoGridContent(
        columns: 5,
        rows: <List<String>>[
          <String>[LabImages.albumSungsuGridR1c1, LabImages.albumSungsuGridR1c2, LabImages.albumSungsuGridR1c3, LabImages.albumSungsuGridR1c4, LabImages.albumSungsuGridR1c5],
          <String>[LabImages.albumSungsuGridR2c1, LabImages.albumSungsuGridR2c2, LabImages.albumSungsuGridR2c3, LabImages.albumSungsuGridR2c4, LabImages.albumSungsuGridR2c5],
          <String>[LabImages.albumSungsuGridR3c1, LabImages.albumSungsuGridR3c2, LabImages.albumSungsuGridR3c3, LabImages.albumSungsuGridR3c4, LabImages.albumSungsuGridR3c5],
          <String>[LabImages.albumSungsuGridR4c1, LabImages.albumSungsuGridR4c2, LabImages.albumSungsuGridR4c3, LabImages.albumSungsuGridR4c4, LabImages.albumSungsuGridR4c5],
          <String>[LabImages.albumSungsuGridR5c1, LabImages.albumSungsuGridR5c2, LabImages.albumSungsuGridR5c3, LabImages.albumSungsuGridR5c4, LabImages.albumSungsuGridR5c5],
          <String>[LabImages.albumSungsuGridR6c1, LabImages.albumSungsuGridR6c2, LabImages.albumSungsuGridR6c3, LabImages.albumSungsuGridR6c4, LabImages.albumSungsuGridR6c5],
        ],
        photos: <GridPhotoContent>[
          GridPhotoContent(image: LabImages.albumSungsuGridR1c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c5, liked: false),
        ],
      ),
    ),
    AlbumSectionContent(
      id: 'empty-photo',
      figmaName: 'empty photo',
      nodeId: '2042:2856',
      tone: LabTone.light,
      cover: null,
      title: 'August 20, 2026',
      subtitle: 'Call summary',
      stats: AlbumStatsContent(photos: '0', calls: '2'),
      callCards: <CallCardContent>[
        CallCardContent(
          nodeId: '2042:2869',
          direction: CallDirection.outgoing,
          icon: 'arrow-up-right',
          title: 'A chat before bed',
          subtitle: <LabTextSpan>[
            LabTextSpan('11:10 PM', LabTextWeight.medium),
            LabTextSpan(' ∙ Outgoing call, 21m 17s', LabTextWeight.regular),
          ],
        ),
        CallCardContent(
          nodeId: '2042:2874',
          direction: CallDirection.incoming,
          icon: 'arrow-down-left',
          title: 'Good morning',
          subtitle: <LabTextSpan>[
            LabTextSpan('8:00 AM', LabTextWeight.medium),
            LabTextSpan(' ∙ Incoming call, 5m 10s', LabTextWeight.regular),
          ],
        ),
      ],
      grid: null,
    ),
    AlbumSectionContent(
      id: 'section-3',
      figmaName: '2',
      nodeId: '2042:2879',
      tone: LabTone.dark,
      cover: LabImages.album3Cover,
      title: 'August 20, 2026',
      subtitle: 'Photo summary',
      stats: AlbumStatsContent(photos: '2', calls: '0'),
      callCards: <CallCardContent>[],
      grid: PhotoGridContent(
        columns: 5,
        rows: <List<String>>[
          <String>[LabImages.album3Cover, LabImages.album3GridR1c2],
        ],
        photos: <GridPhotoContent>[
          GridPhotoContent(image: LabImages.album3Cover, liked: false),
          GridPhotoContent(image: LabImages.album3GridR1c2, liked: false),
        ],
      ),
    ),
  ],
);

const AlbumGangneungContent labAlbumGangneungEn = AlbumGangneungContent(
  screenNodeId: '2001:1126',
  title: 'Gangneung',
  date: 'August 20, 2026',
  cover: LabImages.albumSungsuCover,
  grid: PhotoGridContent(
    columns: 5,
    rows: <List<String>>[
      <String>[LabImages.albumSungsuGridR1c1, LabImages.albumSungsuGridR1c2, LabImages.albumSungsuGridR1c3, LabImages.albumSungsuGridR1c4, LabImages.albumSungsuGridR1c5],
      <String>[LabImages.albumSungsuGridR2c1, LabImages.albumSungsuGridR2c2, LabImages.albumSungsuGridR2c3, LabImages.albumSungsuGridR2c4, LabImages.albumSungsuGridR2c5],
      <String>[LabImages.albumSungsuGridR3c1, LabImages.albumSungsuGridR3c2, LabImages.albumSungsuGridR3c3, LabImages.albumSungsuGridR3c4, LabImages.albumSungsuGridR3c5],
      <String>[LabImages.albumSungsuGridR4c1, LabImages.albumSungsuGridR4c2, LabImages.albumSungsuGridR4c3, LabImages.albumSungsuGridR4c4, LabImages.albumSungsuGridR4c5],
      <String>[LabImages.albumSungsuGridR5c1, LabImages.albumSungsuGridR5c2, LabImages.albumSungsuGridR5c3, LabImages.albumSungsuGridR5c4, LabImages.albumSungsuGridR5c5],
      <String>[LabImages.albumSungsuGridR6c1, LabImages.albumSungsuGridR6c2, LabImages.albumSungsuGridR6c3, LabImages.albumSungsuGridR6c4, LabImages.albumSungsuGridR6c5],
    ],
    photos: <GridPhotoContent>[
      GridPhotoContent(image: LabImages.albumSungsuGridR1c1, liked: true),
      GridPhotoContent(image: LabImages.albumSungsuGridR1c3, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR1c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR1c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR2c3, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR2c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR2c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c1, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c2, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c3, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR3c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR4c1, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR4c2, liked: true),
      GridPhotoContent(image: LabImages.albumSungsuGridR4c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR4c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR5c1, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR5c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR5c5, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c1, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c2, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c3, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c4, liked: false),
      GridPhotoContent(image: LabImages.albumSungsuGridR6c5, liked: false),
    ],
  ),
  featured: <FeaturedTileContent>[
    FeaturedTileContent(nodeId: '2001:1168', image: LabImages.albumSungsuGridR1c1, row: 1, col: 1, rowSpan: 2, colSpan: 2, liked: true),
    FeaturedTileContent(nodeId: '2001:1171', image: LabImages.albumSungsuGridR4c2, row: 4, col: 2, rowSpan: 2, colSpan: 2, liked: true),
  ],
  quoteCard: QuoteCardContent(
    nodeId: '2015:1954',
    label: 'Highlight #1',
    labelAlign: LabAlign.left,
    lines: <QuoteLineContent>[
      QuoteLineContent(nodeId: '2015:1956', text: 'My exam is tomorrow. I really need that pen!', align: LabAlign.left, gradient: GradientTextContent(solidUntil: 0.46635)),
      QuoteLineContent(nodeId: '2015:1957', text: 'Got it. I\'ll make sure to bring it!', align: LabAlign.right, gradient: null),
    ],
  ),
  tabBar: TabBarContent(nodeId: '2001:1375', selectedIndex: 0, avatar: LabImages.tabbarAvatar),
);

const TranscriptContent labTranscriptEn = TranscriptContent(
  screenNodeIds: LabNodeIds(light: '2042:3219', dark: '2042:2933'),
  title: 'Planning our Seongsu date',
  date: 'August 20, 12:20 PM',
  darkBackground: LabImages.transcriptDarkBackground,
  lines: <TranscriptLineContent>[
    TranscriptLineContent(id: 'l1', nodeIds: LabNodeIds(light: '2042:3246', dark: '2042:3132'), text: 'Juyoung, want to go to Seongsu on Saturday?', side: LabAlign.left, inHighlight: false, current: false, gradient: null),
    TranscriptLineContent(id: 'l2', nodeIds: LabNodeIds(light: '2042:3257', dark: '2042:3135'), text: 'Yes! There\'s a place I\'ve been wanting to try', side: LabAlign.right, inHighlight: false, current: false, gradient: null),
    TranscriptLineContent(id: 'l3', nodeIds: LabNodeIds(light: '2042:3248', dark: '2042:3137'), text: 'That new cafe on Yeonmujang-gil,\nnot the Daelim Warehouse we talked about?', side: LabAlign.left, inHighlight: false, current: false, gradient: null),
    TranscriptLineContent(id: 'l4', nodeIds: LabNodeIds(light: '2042:3251', dark: '2042:3139'), text: 'They say there\'s no wait before 3! Let\'s meet at Seoul Forest around 1 on Saturday and walk there', side: LabAlign.left, inHighlight: true, current: false, gradient: null),
    TranscriptLineContent(id: 'l5', nodeIds: LabNodeIds(light: '2042:3252', dark: '2042:3141'), text: 'Sounds good! See you at exit 4 of Seoul Forest Station at 1!', side: LabAlign.right, inHighlight: true, current: true, gradient: GradientTextContent(solidUntil: 0.60577)),
    TranscriptLineContent(id: 'l6', nodeIds: LabNodeIds(light: '2042:3253', dark: '2042:3213'), text: 'Where should we have dinner?', side: LabAlign.left, inHighlight: true, current: false, gradient: null),
    TranscriptLineContent(id: 'l7', nodeIds: LabNodeIds(light: '2042:3254', dark: '2042:3215'), text: 'Let\'s decide after the cafe', side: LabAlign.right, inHighlight: true, current: false, gradient: null),
    TranscriptLineContent(id: 'l8', nodeIds: LabNodeIds(light: '2042:3255', dark: '2042:3217'), text: 'Great, I can\'t wait!', side: LabAlign.left, inHighlight: true, current: false, gradient: null),
  ],
  player: PlayerContent(
    nodeIds: LabNodeIds(light: '2042:3224', dark: '2042:3105'),
    currentTime: '00:00',
    duration: '07:23',
    durationSeconds: 443,
    playing: true,
    trackWidthPx: 155.0,
    trackWidthPxDark: 154.0,
    progressWidthPx: 36.0,
    progress: 0.232258,
    thumbLeftPx: 24.0,
    thumbSizePx: 24.0,
    thumbCenterPx: 36.0,
    thumbCenter: 0.232258,
    markers: <PlayerMarkerContent>[
      PlayerMarkerContent(nodeIds: LabNodeIds(light: '2042:3226', dark: '2042:3107'), leftPx: 80.0, widthPx: 19.0, start: 0.516129, width: 0.122581),
      PlayerMarkerContent(nodeIds: LabNodeIds(light: '2042:3227', dark: '2042:3108'), leftPx: 122.0, widthPx: 12.0, start: 0.787097, width: 0.077419),
    ],
  ),
);

const InCallContent labInCallEn = InCallContent(
  screenNodeIds: <String>['2042:2361', '2042:2504', '2042:2581', '2042:2650', '2004:1796'],
  name: 'Yurim',
  timer: '00:04',
  background: LabImages.callBackground,
  toasts: InCallToastsContent(
    systemMessage: ToastContent(
      screenNodeId: '2042:2361',
      nodeId: '2042:2498',
      text: 'System message.',
      icon: 'border-none',
      iconIsPlaceholder: true,
    ),
    sleepModeRequest: ToastContent(
      screenNodeId: '2004:1796',
      nodeId: '2004:1818',
      text: 'Sleep mode request sent to Yurim!',
      icon: 'moon-filled',
      iconIsPlaceholder: false,
    ),
  ),
);

const PhotoBoothSampleContent labPhotoBoothSampleEn = PhotoBoothSampleContent(nodeId: '2042:3117', image: LabImages.albumSungsuGridR4c2);

const CameraContent labCameraEn = CameraContent(
  screenNodeId: '2056:3280',
  placeholderNodeId: '2058:3415',
  placeholder: LabImages.cameraPlaceholder,
  initialMode: CameraModeId.photo,
  modes: <CameraModeContent>[
    CameraModeContent(id: CameraModeId.photo, nodeId: '2056:3394', labelNodeId: '2056:3410', label: 'Photo'),
    CameraModeContent(id: CameraModeId.video, nodeId: '2056:3412', labelNodeId: '2056:3414', label: 'Video'),
  ],
);

const InCallV5Content labInCallV5En = InCallV5Content(
  screenNodeIds: <String>['2170:8678', '2170:9065', '2176:9162', '2170:8774', '2170:8313'],
  name: 'Yurim',
  timer: '00:04',
  background: LabImages.albumSungsuCover,
  toasts: InCallV5ToastsContent(
    sleep: ToastContent(
      screenNodeId: '2170:8678',
      nodeId: '2170:8743',
      text: 'Yurim switched to sleep mode!',
      icon: 'moon-filled',
      iconIsPlaceholder: false,
    ),
    highlight: ToastContent(
      screenNodeId: '2176:9162',
      nodeId: '2176:9229',
      text: 'Saved a highlight with 15 seconds before and after!',
      icon: 'info-circle',
      iconIsPlaceholder: false,
    ),
  ),
  photoSheet: PhotoSheetContent(
    screenNodeId: '2170:8774',
    nodeId: '2170:9008',
    title: 'Photo',
    liveCell: SheetLiveCellContent(nodeId: '2170:9039', image: LabImages.photoSheetLiveCamera, row: 1, col: 1, rowSpan: 2),
    columns: 3,
    rows: <List<String>>[
      <String>[LabImages.albumSungsuGridR1c1, LabImages.albumSungsuGridR1c2, LabImages.albumSungsuGridR1c3],
      <String>[LabImages.albumSungsuGridR2c1, LabImages.albumSungsuGridR2c2, LabImages.albumSungsuGridR2c3],
      <String>[LabImages.albumSungsuGridR3c1, LabImages.albumSungsuGridR3c2, LabImages.albumSungsuGridR3c3],
      <String>[LabImages.albumSungsuGridR4c1, LabImages.albumSungsuGridR4c2, LabImages.albumSungsuGridR4c3],
    ],
    photos: <SheetPhotoContent>[
      SheetPhotoContent(image: LabImages.albumSungsuGridR1c2, selected: true),
      SheetPhotoContent(image: LabImages.albumSungsuGridR1c3, selected: true),
      SheetPhotoContent(image: LabImages.albumSungsuGridR2c2, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR2c3, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR3c1, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR3c2, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR3c3, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR4c1, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR4c2, selected: false),
      SheetPhotoContent(image: LabImages.albumSungsuGridR4c3, selected: false),
    ],
  ),
  capturedCard: CapturedCardContent(nodeId: '2170:8607', image: LabImages.albumSungsuGridR3c2Hires, orientation: CapturedOrientation.portrait),
);

const CameraV5Content labCameraV5En = CameraV5Content(
  screenNodeId: '2170:5682',
  viewfinderNodeId: '2170:5760',
  viewfinder: LabImages.cameraViewfinderV5,
  thumbnailNodeId: '2170:5904',
  thumbnail: LabImages.albumSungsuGridR5c4Hires,
  toast: ToastContent(
    screenNodeId: '2170:5682',
    nodeId: '2170:9152',
    text: 'Yurim shared a moment!',
    icon: 'info-circle',
    iconIsPlaceholder: false,
  ),
);

const ViewerV5Content labViewerV5En = ViewerV5Content(
  photo: ViewerContent(screenNodeId: '2170:7914', cardNodeId: '2170:8068', image: LabImages.albumSungsuGridR5c4Hires, date: 'Today, 12:00 AM', actions: <String>['share-2', 'heart', 'trash']),
  instant: ViewerContent(screenNodeId: '2170:6159', cardNodeId: '2170:6162', image: LabImages.albumSungsuGridR5c4Hires, date: 'Today, 12:00 AM', actions: <String>['share-2', 'heart']),
);

const TabBarV5Content labTabBarV5En = TabBarV5Content(nodeId: '2166:5444', avatar: LabImages.albumSungsuGridR1c1Hires);

const AlbumV5Content labAlbumV5En = AlbumV5Content(
  screenNodeId: '2170:6590',
  contentNodeId: '2232:2109',
  nav: AlbumV5NavContent(selectLabel: 'Select', actions: <String>['phone-call', 'heart', 'history']),
  selectNav: AlbumV5SelectNavContent(actions: <String>['share-2', 'trash']),
  sections: <AlbumV5SectionContent>[
    AlbumV5SectionContent(
      id: 'sungsu',
      figmaName: '1',
      nodeId: '2170:7307',
      kind: AlbumSectionKind.photosCalls,
      tint: 'album/section-1',
      heroGradient: 'albumHeroV5',
      cover: LabImages.albumSungsuCover,
      title: 'Seongsu → Hannam',
      subtitle: 'August 20, 2026 · 6 hours',
      stats: AlbumStatsContent(photos: '30', calls: '3'),
      callCards: <CallCardV5Content>[
        CallCardV5Content(
          nodeId: '2170:7320',
          variant: 'scrim',
          direction: CallDirection.outgoing,
          icon: 'arrow-up-right',
          title: 'Planning our Seongsu date',
          subtitle: <LabTextSpan>[
            LabTextSpan('12:20 PM', LabTextWeight.regular),
            LabTextSpan(' ∙ Outgoing call, 21m 17s', LabTextWeight.regular),
          ],
        ),
        CallCardV5Content(
          nodeId: '2170:7321',
          variant: 'scrim',
          direction: CallDirection.incoming,
          icon: 'arrow-down-left',
          title: 'Good morning',
          subtitle: <LabTextSpan>[
            LabTextSpan('8:12 AM', LabTextWeight.regular),
            LabTextSpan(' ∙ Incoming call, 5m 10s', LabTextWeight.regular),
          ],
        ),
        CallCardV5Content(
          nodeId: '2170:7322',
          variant: 'failed',
          direction: CallDirection.missed,
          icon: 'arrow-down-left',
          title: 'Missed',
          subtitle: <LabTextSpan>[
            LabTextSpan('8:10 AM', LabTextWeight.regular),
          ],
        ),
      ],
      grid: PhotoGridContent(
        columns: 5,
        rows: <List<String>>[
          <String>[LabImages.albumSungsuGridR1c1, LabImages.albumSungsuGridR1c2, LabImages.albumSungsuGridR1c3, LabImages.albumSungsuGridR1c4, LabImages.albumSungsuGridR1c5],
          <String>[LabImages.albumSungsuGridR2c1, LabImages.albumSungsuGridR2c2, LabImages.albumSungsuGridR2c3, LabImages.albumSungsuGridR2c4, LabImages.albumSungsuGridR2c5],
          <String>[LabImages.albumSungsuGridR3c1, LabImages.albumSungsuGridR3c2, LabImages.albumSungsuGridR3c3, LabImages.albumSungsuGridR3c4, LabImages.albumSungsuGridR3c5],
          <String>[LabImages.albumSungsuGridR4c1, LabImages.albumSungsuGridR4c2, LabImages.albumSungsuGridR4c3, LabImages.albumSungsuGridR4c4, LabImages.albumSungsuGridR4c5],
          <String>[LabImages.albumSungsuGridR5c1, LabImages.albumSungsuGridR5c2, LabImages.albumSungsuGridR5c3, LabImages.albumSungsuGridR5c4, LabImages.albumSungsuGridR5c5],
          <String>[LabImages.albumSungsuGridR6c1, LabImages.albumSungsuGridR6c2, LabImages.albumSungsuGridR6c3, LabImages.albumSungsuGridR6c4, LabImages.albumSungsuGridR6c5],
        ],
        photos: <GridPhotoContent>[
          GridPhotoContent(image: LabImages.albumSungsuGridR1c1, liked: true),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR1c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR2c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR3c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR4c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR5c5, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c1, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c2, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c3, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c4, liked: false),
          GridPhotoContent(image: LabImages.albumSungsuGridR6c5, liked: false),
        ],
      ),
      featured: <FeaturedTileContent>[
        FeaturedTileContent(nodeId: '2170:8302', image: LabImages.albumSungsuGridR1c1, row: 1, col: 1, rowSpan: 2, colSpan: 2, liked: true),
      ],
    ),
    AlbumV5SectionContent(
      id: 'calls-only',
      figmaName: 'empty photo',
      nodeId: '2170:7360',
      kind: AlbumSectionKind.callsOnly,
      tint: 'album/section-calls',
      heroGradient: null,
      cover: null,
      title: 'August 20, 2026',
      subtitle: 'Call summary',
      stats: AlbumStatsContent(photos: '0', calls: '2'),
      callCards: <CallCardV5Content>[
        CallCardV5Content(
          nodeId: '2170:7373',
          variant: 'default',
          direction: CallDirection.outgoing,
          icon: 'arrow-up-right',
          title: 'A chat before bed',
          subtitle: <LabTextSpan>[
            LabTextSpan('11:10 PM ∙ Outgoing call, 21m 17s', LabTextWeight.regular),
          ],
        ),
        CallCardV5Content(
          nodeId: '2170:7374',
          variant: 'default',
          direction: CallDirection.incoming,
          icon: 'arrow-down-left',
          title: 'Good morning',
          subtitle: <LabTextSpan>[
            LabTextSpan('8:00 AM ∙ Incoming call, 5m 10s', LabTextWeight.regular),
          ],
        ),
      ],
      grid: null,
      featured: <FeaturedTileContent>[],
    ),
    AlbumV5SectionContent(
      id: 'section-2',
      figmaName: '2',
      nodeId: '2170:7375',
      kind: AlbumSectionKind.photosOnly,
      tint: 'album/section-3',
      heroGradient: 'albumHeroV5Section2',
      cover: LabImages.album3Cover,
      title: 'August 20, 2026',
      subtitle: 'Photo summary',
      stats: AlbumStatsContent(photos: '2', calls: '0'),
      callCards: <CallCardV5Content>[],
      grid: PhotoGridContent(
        columns: 5,
        rows: <List<String>>[
          <String>[LabImages.album3Cover, LabImages.album3GridR1c2],
        ],
        photos: <GridPhotoContent>[
          GridPhotoContent(image: LabImages.album3Cover, liked: false),
          GridPhotoContent(image: LabImages.album3GridR1c2, liked: false),
        ],
      ),
      featured: <FeaturedTileContent>[],
    ),
  ],
);

const SettingsV5Content labSettingsV5En = SettingsV5Content(
  screenNodeId: '2176:11011',
  hero: LabImages.albumSungsuCover,
  names: 'Juyoung Lee, Yurim Lee',
  days: 200,
  dayCount: 'Day 200',
  daySuffix: ' together',
  editProfile: SettingsActionContent(nodeId: '2176:11374', label: 'Edit profile', icon: 'pencil'),
  disconnect: SettingsActionContent(nodeId: '2176:11483', label: 'Disconnect', icon: 'link-off'),
);

const TranscriptV5Content labTranscriptV5En = TranscriptV5Content(
  screenNodeId: '2176:9241',
  variantNodeIds: <String>['2232:2862', '2232:2932', '2194:13374'],
  title: 'Planning our Seongsu date',
  date: 'August 20, 12:20 PM',
  navActions: <String>['phone-call', 'heart'],
  lines: <TranscriptV5LineContent>[
    TranscriptV5LineContent(id: 'l1', nodeId: '2176:10929', text: 'Juyoung, want to go to Seongsu on Saturday?', side: LabAlign.left, inHighlight: false, current: false),
    TranscriptV5LineContent(id: 'l2', nodeId: '2176:10931', text: 'Yes! There\'s a place I\'ve been wanting to try', side: LabAlign.right, inHighlight: false, current: false),
    TranscriptV5LineContent(id: 'l3', nodeId: '2176:10933', text: 'That new cafe on Yeonmujang-gil,\nnot the Daelim Warehouse we talked about?', side: LabAlign.left, inHighlight: false, current: false),
    TranscriptV5LineContent(id: 'l4', nodeId: '2176:10937', text: 'They say there\'s no wait before 3! Let\'s meet at Seoul Forest around 1 on Saturday and walk there', side: LabAlign.left, inHighlight: true, current: false),
    TranscriptV5LineContent(id: 'l5', nodeId: '2176:10938', text: 'Sounds good! See you at exit 4 of Seoul Forest Station at 1!', side: LabAlign.right, inHighlight: true, current: true),
    TranscriptV5LineContent(id: 'l6', nodeId: '2176:10939', text: 'Where should we have dinner?', side: LabAlign.left, inHighlight: true, current: false),
    TranscriptV5LineContent(id: 'l7', nodeId: '2176:10940', text: 'Let\'s decide after the cafe', side: LabAlign.right, inHighlight: true, current: false),
    TranscriptV5LineContent(id: 'l8', nodeId: '2176:10941', text: 'Great, I can\'t wait!', side: LabAlign.left, inHighlight: true, current: false),
  ],
  inlinePhoto: InlinePhotoContent(nodeId: '2176:10934', image: LabImages.transcriptInlinePhoto, afterLineId: 'l3'),
  player: PlayerV5Content(
    nodeId: '2176:10994',
    currentTime: '00:00',
    duration: '07:23',
    durationSeconds: 443,
    playing: true,
    trackWidthPx: 157.0,
    progressWidthPx: 47.0,
    progress: 0.299363,
    thumbLeftPx: 32.5,
    thumbSizePx: 28.0,
    thumbCenterPx: 46.5,
    thumbCenter: 0.296178,
    markers: <PlayerV5MarkerContent>[
      PlayerV5MarkerContent(nodeId: '2176:11006', leftPx: 75.0, widthPx: 16.0, start: 0.477707, width: 0.101911),
      PlayerV5MarkerContent(nodeId: '2176:11007', leftPx: 112.0, widthPx: 16.0, start: 0.713376, width: 0.101911),
    ],
  ),
);

class LabSamples {
  const LabSamples({required this.labAlbumDay, required this.labAlbumGangneung, required this.labTranscript, required this.labInCall, required this.labPhotoBoothSample, required this.labCamera, required this.labInCallV5, required this.labCameraV5, required this.labViewerV5, required this.labTabBarV5, required this.labAlbumV5, required this.labSettingsV5, required this.labTranscriptV5});
  final AlbumDayContent labAlbumDay;
  final AlbumGangneungContent labAlbumGangneung;
  final TranscriptContent labTranscript;
  final InCallContent labInCall;
  final PhotoBoothSampleContent labPhotoBoothSample;
  final CameraContent labCamera;
  final InCallV5Content labInCallV5;
  final CameraV5Content labCameraV5;
  final ViewerV5Content labViewerV5;
  final TabBarV5Content labTabBarV5;
  final AlbumV5Content labAlbumV5;
  final SettingsV5Content labSettingsV5;
  final TranscriptV5Content labTranscriptV5;
  static LabSamples of(BuildContext context) => Localizations.of<LabSamples>(context, LabSamples) ?? labSamples;
  static const delegate = ContentLocaleDelegate<LabSamples>(ko: labSamples, en: labSamplesEn);
}
const labSamples = LabSamples(labAlbumDay: labAlbumDay, labAlbumGangneung: labAlbumGangneung, labTranscript: labTranscript, labInCall: labInCall, labPhotoBoothSample: labPhotoBoothSample, labCamera: labCamera, labInCallV5: labInCallV5, labCameraV5: labCameraV5, labViewerV5: labViewerV5, labTabBarV5: labTabBarV5, labAlbumV5: labAlbumV5, labSettingsV5: labSettingsV5, labTranscriptV5: labTranscriptV5);
const labSamplesEn = LabSamples(labAlbumDay: labAlbumDayEn, labAlbumGangneung: labAlbumGangneungEn, labTranscript: labTranscriptEn, labInCall: labInCallEn, labPhotoBoothSample: labPhotoBoothSampleEn, labCamera: labCameraEn, labInCallV5: labInCallV5En, labCameraV5: labCameraV5En, labViewerV5: labViewerV5En, labTabBarV5: labTabBarV5En, labAlbumV5: labAlbumV5En, labSettingsV5: labSettingsV5En, labTranscriptV5: labTranscriptV5En);
